### ISSUE TITLE
Space items do not work on secondary display

### ISSUE THREAD

**Issue by cxa** [FelixKratz/SketchyBar#116]
Suppose I have 2 spaces, each on different display.

```sh
 sketchybar -m \
    --add space home left \
    --set home \
    associated_space=1 associated_display=1 \
    script="a.sh"

 sketchybar -m \
    --add space misc left \
    --set misc \
    associated_space=2 associated_display=2 \
    script="a.sh"
```

Switch spaces between displays will not trigger `a.sh`.

**Comment by cxa** [comment]
`--subscribe [item_name] space_change` does not work for normal items either.

**Comment by FelixKratz** [comment]
If you have only two spaces on two different displays why would the script ever be executed? The space_change event is only triggered if the selected space of a specific display is changed, e.g. you switch from space 1 to space 2 on display 1. It is not executed if you move between displays, or if you move a space to a different display. This is the same behavior you also see in yabai. If you want to hook to these events you can do so by creating a custom event for that.

**Comment by cxa** [comment]
Thanks for your explanation. Then `space` item is not usable for me. I solved by adding custom event by listening both `display_changed` and `space_changed` of yabai.
