### ISSUE TITLE
customize which corners get rounded

### ISSUE THREAD

**Issue by es183923** [FelixKratz/SketchyBar#117]
with the `corner_radius` option, all four corners get rounded. I just want the top two corners rounded.

**Comment by es183923** [comment]
This could be done by:
```sh
sketchybar -m bar \
    corner_radius.top_right=3 \
    corner_radius.top_left=3 \
    corner_radius.bottom_left=3 \
    corner_radius.bottom_right=3
```

**Comment by FelixKratz** [comment]
I am working on something like that for #102, all backgrounds will have more terminator properties including the bar itself (individual rounding will also be possible).

**Comment by FelixKratz** [comment]
While this is technically simple, I believe the syntax would get very cluttered. Background Images can contain arbitrary shapes already, thus I am closing this.

**Comment by cxa** [comment]
@es183923 I made a patch without changing the syntax, but it requires corner_radius to be set as `0xTL_TR_BR_BL`, e.g., `background.corner_radius=0x0A100A0A`, meaning the radii for top-left, top-right, bottom-right, and bottom-left are 10, 16, 10, and 10, respectively:

https://github.com/cxa/SketchyBar/commit/26c4900a09edb6d121a199822562f6f27ffef86b

Not sure if @FelixKratz would accept this syntax—if so, I can submit a pull request.
