### ISSUE TITLE
Better notch handling

### ISSUE THREAD

**Issue by FelixKratz** [FelixKratz/SketchyBar#120]
Center Items make no sense on notched screens. Items can already be placed anchored left and right on the notch with the experimental positions `position=q` and `position=e` where the naming is subject to change. 
The width of the notch can be adjusted via:
```bash
sketchybar --bar notch_width=<positive_integer>
```
The y-offset applied to the notched screen excusively can be set since fcef6cc611b4814b87d866f0c1c14f8ebd851cae via:
```bash
sketchybar --bar notch_offset=<positive_integer>
```
This thread can be used to collect further ideas for better notch handling. 

It is frustrating when items get below the notch so there should be a method in place to prevent that, possibly by creating an "overflow item" like #119.

**Comment by typkrft** [comment]
I'm just going through and rewriting my bar with the notch in mind. Mostly just playing with ideas right now, but I was thinking it would be nice to have a fade in and out animation. On hover or when triggered this would look really cool. My goal is to almost completely fade out most of the items on the bar so it looks almost like capacitive buttons on the bezel. The bar needs to be dynamic now that there's a notch and information needs to be shown uniformly in certain places when it's relevant.  I was thinking about writing a script but wasn't sure how to do this elegantly or without blocking processes with sleep commands. 

Faded In
<img width="2056" alt="Screen Shot 2021-12-12 at 11 58 02 PM" src="https://user-images.githubusercontent.com/12100960/145754865-5bb29eda-258f-4025-9781-586826c05714.png">

Faded out
<img width="2056" alt="Screen Shot 2021-12-13 at 12 08 03 AM" src="https://user-images.githubusercontent.com/12100960/145755661-e147d8da-9f11-4120-b05c-9d1c0c13f820.png">

**Comment by FelixKratz** [comment]
Animations are on my todo list, simple transitions between colors and positions should be no problem to implement, maybe I will look into some nice easing functions for that as well. But in preparation for this I need to work on the core logic a bit to make this resource efficient. Maybe I will have some time for this over the holidays, as I already have the syntax for this sketched out roughly.

**Comment by FelixKratz** [comment]
I think #132 will also aid the notch handling, because many information can now be put into a popup window.

**Comment by FelixKratz** [comment]
The `notch_width` property is broken in the current release, but since it is undocumented so far I will not create a new release for this. It has been fixed on master.

**Comment by FelixKratz** [comment]
> I'm just going through and rewriting my bar with the notch in mind. Mostly just playing with ideas right now, but I was thinking it would be nice to have a fade in and out animation. On hover or when triggered this would look really cool. My goal is to almost completely fade out most of the items on the bar so it looks almost like capacitive buttons on the bezel. The bar needs to be dynamic now that there's a notch and information needs to be shown uniformly in certain places when it's relevant. I was thinking about writing a script but wasn't sure how to do this elegantly or without blocking processes with sleep commands.
> 
> Faded In <img alt="Screen Shot 2021-12-12 at 11 58 02 PM" width="2000" src="https://user-images.githubusercontent.com/12100960/145754865-5bb29eda-258f-4025-9781-586826c05714.png">
> 
> Faded out <img alt="Screen Shot 2021-12-13 at 12 08 03 AM" width="2000" src="https://user-images.githubusercontent.com/12100960/145755661-e147d8da-9f11-4120-b05c-9d1c0c13f820.png">

The fade in, fade out animation should now be possible on latest master with the new animation feature and the global mouse entered and exited events (#178).

**Comment by B1T3X** [comment]
Personally, I use a program called "forehard" to hide the notch, and use y_offset to lower my bar to be fully visible.

**Comment by FelixKratz** [comment]
As these features will be included in the upcoming release officially and are now documented I will close this for now.
