### ISSUE TITLE
Querying default menu items

### ISSUE THREAD

**Issue by alex-jerechinsky** [FelixKratz/SketchyBar#125]
I seem to be unable to query the default menu items. This is the output I'm getting. Am I doing something wrong? 

```
alexandrjerechinsky@MacBook-Air-2 ~ % sketchybar -m --query default_menu_items

Total Windows: 668
Menu Item -> Owner: Window Server; with PID:358, Name: Menubar Bottom Edge
Menu Item -> Owner: Window Server; with PID:358, Name: Menubar Bottom Edge
Menu Item -> Owner: Window Server; with PID:358, Name: Menubar Bottom Edge
Menu Item -> Owner: Window Server; with PID:358, Name: Menubar Bottom Edge
Menu Item -> Owner: Window Server; with PID:358, Name: Menubar Bottom Edge
Menu Item -> Owner: Window Server; with PID:358, Name: Menubar Bottom Edge
Menu Item -> Owner: Window Server; with PID:358, Name: Menubar Bottom Edge
Menu Item -> Owner: Window Server; with PID:358, Name: Menubar Bottom Edge
Menu Item -> Owner: Window Server; with PID:358, Name: Menubar Bottom Edge
```
<br />
P.S. thanks for this great software!

**Comment by FelixKratz** [comment]
Have you created an alias at some point before running this command? I think screen capture permissions are required to get the correct names of menu items. So you might try to add an alias and grant the permissions and then try querying again

**Comment by FelixKratz** [comment]
Fixed in 56862e90dd8c5a54e592a7a004fce448dfa01b14

**Comment by alex-jerechinsky** [comment]
Thanks for a quick response. I added an alias of battery like you suggested and sketchybar asked for permission. I granted the permission, but it didn't seem to work. Sketchybar is still asking for permission each time I launch it and the alias item didn't show up.

I tried rebooting the computer, but that didn't help.
Please let me know if there's some debug info I could provide.

![sketchybar_record_permission](https://user-images.githubusercontent.com/75733878/145565045-9c874b2e-6ea1-4331-8b56-ace6dbd72646.gif)

**Comment by FelixKratz** [comment]
Can you try to disable sketchybar via brew and execute it explicitly from terminal? Then your terminal application will ask for the permissions and it should in theory work. I saw in the yabai issue for monterey https://github.com/koekeishiya/yabai/issues/1054 that this seems to be a problem with monterey and brew changing some behavior regarding the permission system. I will look into this issue in more depth.

**Comment by FelixKratz** [comment]
I tried to fix it in the brew install formula: https://github.com/FelixKratz/homebrew-formulae/commit/893804b71c030da31a71ec62b866983158e70cd8, could you try it out by running:
```bash
brew uninstall sketchybar
brew untap FelixKratz/formulae
brew tap FelixKratz/formulae
brew install sketchybar
``` 
Thank you for the bug report!

**Comment by alex-jerechinsky** [comment]
That fixed it for me. Everything works now. Thanks a lot for resolving this one so quickly!
