### ISSUE TITLE
ask for screen capture permission when calling `-m --query default_menu_items`

### ISSUE THREAD

**Issue by yqrashawn** [FelixKratz/SketchyBar#127]
seems sketchybar can't get the correct menu bar items without the permission 

![image](https://user-images.githubusercontent.com/15090582/145920306-db6eb8d8-e241-4b02-b0ad-5b4dbeb297ed.png)

**Comment by es183923** [comment]
Sketchybar requires the screen recording permission in order to find out what the menu bar items are.

**Comment by yqrashawn** [comment]
Sorry for my unclear description. I mean sketchybar should ask for the permission when calling `sketchybar -m --query default_menu_items`
It currently ask it when set alias item

**Comment by FelixKratz** [comment]
This was fixed in 56862e90dd8c5a54e592a7a004fce448dfa01b14 just not yet released. It will be included in v2.2.4. #94
