### ISSUE TITLE
man page

### ISSUE THREAD

**Issue by FelixKratz** [FelixKratz/SketchyBar#130]
Since this is a command line program it should contain a man page.

**Comment by FelixKratz** [comment]
[felixkratz.github.io/sketchybar/](https://felixkratz.github.io/SketchyBar/)

**Comment by ralphptorres** [comment]
Any chance to implement a local man page? We can tweak the contents of the online documentation then feed to [scdoc](https://git.sr.ht/~sircmpwn/scdoc) to simplify the process.

**Comment by FelixKratz** [comment]
I am all for a man page and I will gladly accept pull requests for it.

**Comment by ralphptorres** [comment]
Sent a pr.
