### ISSUE TITLE
Clickable Aliases

### ISSUE THREAD

**Issue by FelixKratz** [FelixKratz/SketchyBar#131]
At some point I want to invest some time to try and get aliases to be clickable and show their original popup content. This is probably not a simple task so if anyone has any idea on how to achieve this please let me know so I can save some time on that.

**Comment by aidan-gibson** [comment]
Was there no way to implement this? I would very much love if this were possible but totally understand if it isn't.

**Comment by FelixKratz** [comment]
I have looked a bit into implementing it back then and it became painfully clear that this would not be simple. My original idea was to use the AX api to parse the AX tree and then imitate a mouse click on the original menu bar item and move the resulting popup via the AX api to below the sketchybar alias. This does not work robustly. Some menubar apps spawn a new window with custom content, there my approach works, however, some menubar apps only open a context menu and this context menu can not be moved.

There might be a way to still do this stuff by using private functions, but I am not sure wether we would actually have the right set of permissions to successfully call these functions. There is some more detail in this discussion: https://github.com/FelixKratz/SketchyBar/discussions/236
