### ISSUE TITLE
Easy way to hide popups along with bar

### ISSUE THREAD

**Issue by es183923** [FelixKratz/SketchyBar#134]
How can I easily hide all popups that may be currently shown, along with the bar itself?
This would either require manually putting them into a hide bar script, or require querying all the items to hide all the popups (which isn't implemented yet).
Either way, this is not a trivial task.

An option could be to add a `popups=on/off/toggle` option, similar to how `hidden` currently works.

Example:
`sketchybar -m --bar hidden=off` hides the bar.
`sketchybar -m --bar hidden=off popups=off` hides both the bar and the popups.

**Comment by FelixKratz** [comment]
I think `hidden=on` should automatically close all popups, everything else seems a bit buggy. I want to implement regex support for the set command (#122) at some point, this way the popups of all items could be set via something like:
```bash
sketchybar --set .\* popup.drawing=off
```

**Comment by FelixKratz** [comment]
The regex syntax above now works on HEAD (becbddcba6d38991ecef21d58cb39a5de67870f5)
