### ISSUE TITLE
Script not running when using script parameter

### ISSUE THREAD

**Issue by davidc360** [FelixKratz/SketchyBar#137]
I've been trying to debug this for hours and can't figure it out and I'm hoping I can get some help,

I have the below in my rc:

```
sketchybar -m --add space lc_all left\
                --set lc_all \
                                 update_freq=10 \
                                 script="~/.config/sketchybar/plugins/leetcode.sh" \
                                 icon.padding_left=0 \
                                 icon.padding_right=4 \
                                 label.padding_left=0 \
                                 label.padding_right=4 \
```

and in leetcode.sh: 

```
#!/usr/bin/env bash

d=$(python3 ~/store_lc_stats.py davidc360 all)

sketchybar -m \
    --set lc_all\
            label=$d
```

lc_stats.py is just a python script that calls the Leetcode api and returns the number of LC problems I've solved. However, the script doesn't seem to run in sketchybar, actually, `lc_all` becomes empty whenever the script is called.

But when I run `~/.config/sketchybar/plugins/leetcode.sh` manually in the terminal, it works perfectly and updates the label correctly, so I ruled out that the problem is with the scripts. Is there something obvious that I'm missing? Thanks in advance

**Comment by davidc360** [comment]
After more hours of digging, i found out that my python script errored out when I tried to write to a local file,

```
counts = ','.join([str(x) for x in [all, easy, medium, hard]])
f = open('lc_stats.txt', 'w')
f.write(counts)
f.close()
```

I'm guessing the path `lc_stats.txt` is not able to resolve when it's run under sketchy bar. Getting the home directory and doing 

```
from os.path import expanduser
home = expanduser("~")
f = open(home+'/lc_stats.txt', 'w')
```

Works

**Comment by FelixKratz** [comment]
Scripts should always be used with absolute paths, otherwise write permissions to a relative file could be denied. I will state this more clearly in the readme, such that others do not have to go through the frustration you encountered.
