### ISSUE TITLE
Feature Requset: Enable / Disable Plugins without Restarting

### ISSUE THREAD

**Issue by typkrft** [FelixKratz/SketchyBar#14]
I know you are refactoring somethings currently, but I thought I would mention that a way to remove or add plugins on the fly would be great. I could write conditional logic into the the config and plugin scripts, but for some tasks it gets a little messy. 

Example 1. Turn on/off X plugin at 1600 every day. 
Example 2. Turn on/off Y plugin with SKHD hotkey.
Example 3. Some program opens, remove xyz plugins and add abc plugins. 
Example 4. Reminders plugin count is 0 remove itself from the bar. 
Example 5. Additional Space is created add a new default space icon and label. 

These are just some ideas, the bar is great as is though. Thanks for you work on this!

**Comment by FelixKratz** [comment]
Enabling and disabling should work now 2dc711f22f4bc4398ce67839b63682a91d7b89b8. Combined with the new event system this might do the job for what you want to do?

**Comment by typkrft** [comment]
Awesome I'll check it out and see if I can knock out these examples.

**Comment by typkrft** [comment]
Enabling and Disabling works very well so far. I did notice one thing, even after I disabled the reminders plugin, if I clicked where the icon was the click script still activated. Once I fill that space with another plugin or re-enable the reminders plugin the issue seems to resolve. Maybe the click scripts aren't getting removed when the plugin is disabled. I will try to test this with a few other plugins to see if it's reproducible.

**Comment by FelixKratz** [comment]
Should be fixed 3862b91271b686f4eb6239cffd87b68628f47d18

**Comment by typkrft** [comment]
Everything is working great! I think most of these use cases can be addressed except for example 1 and example 4. There's a lot of programs that can be queried but cant necessarily send a command. You could work around this by writing a separate script that is always running, but it would be great if we could poll for something. Maybe something that exits with 0. 

I tried to set a simple conditional that would turn off the window title on Tuesday and turn it on any other day. However once a plugin is turned off it has to be turned back on by something else. Maybe a command to leave subscribed events active while the plugin is not shown would be beneficial. e.g.: `sketchybar -m set a_plugin events always # always || on || off`

Problem:
```SHELL
if [[ $(date) = *"Tue"* ]]; then
  sketchybar -m set title enabled off
else 
  sketchybar -m set title enabled on
fi
```
---
Idea of what polling would look like: 

sketchybarrc

```SHELL
# P O L L  E V E N T
sketchybar -m add poll dns_down
sketchybar -m set dns_down update_freq 10
sketchybar -m set dns_down script "~/.config/sketchybar/plugins/dns_down.sh"

# R E M I N D E R S 
sketchybar -m add item reminders
sketchybar -m subscribe reminders dns_down
```

dns_down.sh
```SHELL
#!/bin/zsh  
# Assuming 8.8.8.8 is up this should exit 0
if [[ ! $(ping -t 2 8.8.8.8) =~ ".*Timeout.*" ]]; then
  :
else
  exit 1
fi
```
\> `./dns_down.sh; echo $?`
`0`

**Comment by FelixKratz** [comment]
I could imagine differentiating between *hidden* and *disabled*. *hidden* would only deactivate drawing, while *disabled* would also stop all event callbacks. Then your first problem could be solved by setting the title to *hidden* on thu and *shown* on all other days.

I am not sure I get the polling thing, isn‘t this just a custom event triggered by a simple script? I could imagine the following syntax to accomplish „polling“:

sketchybarrc:
sketchybar -m add event dns_down
sketchybar -m add item dns_trigger
sketchybar -m set dns_trigger update_freq 10
sketchybar -m set dns_trigger script "~/.config/sketchybar/plugins/dns_down.sh"

sketchybar -m add item reminders
sketchybar -m subscribe reminders dns_down

And in your script simply
#!/bin/zsh  
if [[ ! $(ping -t 2 8.8.8.8) =~ ".*Timeout.*" ]]; then
   sketchybar -m trigger dns_down
fi

**Comment by FelixKratz** [comment]
I have added item hiding now d3a2194f6776adbc7958350551c8703a131e4137

```bash
sketchybar -m set <item> hidden on
```

**Comment by typkrft** [comment]
That's my fault I didn't even realize I could set properties properties like update_freq and script for custom events. Hidden is a good idea though too. Thanks!
