### ISSUE TITLE
backgrounds don't work with clone

### ISSUE THREAD

**Issue by es183923** [FelixKratz/SketchyBar#141]
```
sketchybar --add item orig left --set orig label="orig"
sketchybar --clone dupe orig --set dupe background.image="$UTIL_DIR/a.png"
```
Even though a valid image is at `$UTIL_DIR/a.png`, it isn't shown. 
The result is something like: 
![Screen Shot 2021-12-30 at 6 05 34 PM](https://user-images.githubusercontent.com/72744903/147793443-493da502-72f4-4a9b-8f93-f3af69cdfe5d.png)

**Comment by FelixKratz** [comment]
Dont forget to set `background.drawing=on`
