### ISSUE TITLE
crash when entering mission control

### ISSUE THREAD

**Issue by es183923** [FelixKratz/SketchyBar#143]
in `zsh`, if i run `sketchybar`, if I were to enter and exit mission control, I would see: 
```sh
[1]    19904 segmentation fault  sketchybar
```

This happens on the latest version of sketchybar from HEAD.
It doesn't matter what the config is, even if it is blank.

**Comment by FelixKratz** [comment]
I am not able to reproduce this behavior, what OS version are you running and if you are using yabai, does disabling it make this issue go away?

**Comment by es183923** [comment]
I don't know why, but this crash doesn't happen anymore.

**Comment by FelixKratz** [comment]
The window server in monterey can be a bit unstable at times, possibly that is the root cause of the issue you have encountered.
