### ISSUE TITLE
Images not centered

### ISSUE THREAD

**Issue by andreicorpo** [FelixKratz/SketchyBar#149]
Images don't seem to be centered within the background. This can be observed when an item/label/icon has a fixed width.

![image](https://user-images.githubusercontent.com/12585256/148657688-8e785e93-2555-4c82-b218-30dacdc171a6.png)

```sh
sketchybar --add item bg_issue center \
--set bg_issue \
 background.drawing=on \
 background.border_color=0xff00ff00 \
 background.border_width=2 \
 background.image="$HOME/.local/app-icons/kitty.png" \
 background.image.drawing=on \
 width=60

```

**Comment by FelixKratz** [comment]
I need to do some work on the images feature to make it work nicely, until then I have marked the image section experimental.

**Comment by FelixKratz** [comment]
945a430d447b667d07d2f6568198b5aee4eb0e6a introduces a new align property for the item content when its width is set to be larger than the actual content size. You would need to set the image as the background for the icon or label, then it should get centered fine.
