### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by FelixKratz** [FelixKratz/SketchyBar#16]
I would like to have a better documentation and maybe a wiki where everything is explained a bit clearer.
Along the way it would maybe be nice to have a more instructive and cleaner default sketchybarrc.

**Comment by typkrft** [comment]
I'd be happy to commit some time to this on the weekend and open a PR if you're looking for assistance. I'm going to rewrite all of my plugins to showcase the new functionality as well.
