### ISSUE TITLE
Respect shebang line or commit to using bash instead of sh

### ISSUE THREAD

**Issue by basbebe** [FelixKratz/SketchyBar#163]
When SketchyBar executes scripts, it ignores the shebang line.

While this is OK for most users, it breaks if you

- have a script using another shell / scripting language
- use a `sh` implementation other than `bash` (e.g. the POSIX-compliant `dash`,\
  see https://scriptingosx.com/2020/06/about-bash-zsh-sh-and-dash-in-macos-catalina-and-beyond/)

But since there are indicators that macOS _might_ drop `bash` as default `sh` interpreter in the future (see link above) and people use different shells and scripting languages, respecting the shebang line would make SketchyBar and its plugins more portable.

I use `fish` as my user shell and `/bin/sh` is linked to `dash` (to improve speed, see link above).

The current workaround involves adding the interpreter to the script call:
```bash
--set script="$PLUGIN_DIR/myscript.sh"
```
becomes
```bash
--set script="bash $PLUGIN_DIR/myscript.sh"
```
(see https://github.com/FelixKratz/SketchyBar/issues/150)

Adding an interpreter to many plugins adds a lot of overhead since it has to be invoked on every script call additionally to `sh`.

And using `sh` as interpreter for SketchyBar makes assumptions about the system SketchyBar runs on.
While this is save in most cases, `sh` is originally meant to be an interpreter to POSIX-compliant shell scripts.
Nearly none of the SketchyBar plugins are POSIX-compliant, most even have a shebang asking for `bash`.

In my case (and I assume in most cases), it would probably be fine (and maybe the best solution) to just use `bash` as interpreter for all of SketchyBar instead of `sh` and / or add an option to respect shebang lines.

Some version of Bash is (still) installed on all mac systems.\
Another future-proof choice would be ZSH.

**Comment by FelixKratz** [comment]
Yes this is a valid concern and something that is worth discussing about.

I think the best way would be to respect the shebang line for scripts by calling
`execve` with the file path. Then it will natively evaluate the shebang and continue with the appropriate interpreter.
This would, however, break on cached scripts (or direct string scripts without a file), these would need to be executed via
the current method as a fallback.

I will probably delete the `cache_scripts` property anyways going forward, as the system does that automatically for frequently used files.

**Comment by basbebe** [comment]
I think it might be a good idea additionally to internally use / start with bash instead of sh to avoid unnecessary calls of nested shells.

But then again I don't really know what happens when a script runs another script with a shebang:  will the same interpreter be used if the shebang is the same?  
Will it be the same instance or a nested one?
  
(so would it then be better to start with bash if someone some `sh` shebangs and many bash scripts that she / he isn't intending to change?)

**Comment by FelixKratz** [comment]
The shebang should now (1b6cbaeeb823b897f8518b1ea419e289a2145963) be respected more consistently, before it was only respected when `cache_scripts=off`.

This should solve the work around you where employing before.
I hope I didn't brick something else I was not thinking about...

You can try by install from head:
```bash
brew services stop sketchybar
brew uninstall sketchybar
brew install sketchybar --head
sketchybar
```
then you can set a script which calls: `ps -p $$`
there you should see that the shebang is now respected.

**Comment by basbebe** [comment]
So far this seems to work fine for me!

Thanks!
