### ISSUE TITLE
Is there any special operation required to install on the M1 mac?

### ISSUE THREAD

**Issue by ati46** [FelixKratz/SketchyBar#168]
I'm using SketchyBar on my M1 mac, but nothing works.
Install bar with brew install sketchybar
After starting with brew services start sketchybar, the bar does not appear

<img width="568" alt="image" src="https://user-images.githubusercontent.com/33859622/153707176-be227cd2-5d42-491c-9d8a-6b5ce284138f.png">

Can anyone help me, thanks

**Comment by FelixKratz** [comment]
I think you must have installed a very old config file, with the old syntax. Could you try the default config, or mine that I have linked here: https://github.com/FelixKratz/SketchyBar/discussions/47#discussioncomment-2027233?

**Comment by ati46** [comment]
> I think you must have installed a very old config file, with the old syntax. Could you try the default config, or mine that I have linked here: [#47 (comment)](https://github.com/FelixKratz/SketchyBar/discussions/47#discussioncomment-2027233)?

Thank you for your suggestion. After using your configuration, I found that the bar was covered behind the original menu bar. I would like to ask why margin_top cannot take effect in M1?
So how to use sketchybar without hiding the menu bar？
icon_color is valid under inter
<img width="243" alt="image" src="https://user-images.githubusercontent.com/33859622/153714837-8afe820f-a856-416b-815b-badd08b0fdcc.png">

**Comment by FelixKratz** [comment]
macOS does not report the height of the default menu bar for notched displays, you can set a
```bash
sketchybar --bar y_offset 35
```
for example.
"icon_color" was the syntax before v2.0.0 see: https://github.com/FelixKratz/SketchyBar/blob/master/UPDATE.md
Those commands are deprecated a long time now and they are replaced by the new syntax.
