### ISSUE TITLE
Top-level menus (File, Edit, View, etc.)

### ISSUE THREAD

**Issue by sealevelcain** [FelixKratz/SketchyBar#170]
Is it possible for SketchyBar to draw functioning top-level menus? I've seen apps like menuwhere recreate them successfully, but unfortunately menuwhere only allows you to access them via a right-click menu as opposed to a docked/floating bar.

**Comment by FelixKratz** [comment]
Yes. It is possible and I could imagine doing that, however, I am not sure how this would be included in the current syntax.
The top menus could either be another alias, or a new component altogether...

**Comment by sealevelcain** [comment]
I’m not a developer in any sense of the word so I wouldn’t really know which way would be best. Although, given how wildly the number of menus can vary between apps (e.g Finder vs Cinema4D), I feel like it would be cleaner to implement it as a separate module? 

Either that, or a set number of aliases for the universal menus (File, Edit, Help etc), plus an “overhang” menu that contains all app-specific menus.

**Comment by gronk-droid** [comment]
I don't know much about `.app` development for MacOS, but I assume each .app file has to keep a stored location of the commands that the application has in the menu bar. Is it something that can be queried in C, or are they usually encapsulated within the application itself? Could they then be included in the current popup menu implementation?

**Comment by FelixKratz** [comment]
Although this is possible, I struggle to find a good way to include this, there is simply to much variability in these menu items and I believe it is better to just have the original bar on autohide and go with the mouse to the top of the screen to interact with them or create some script that toggle specific actions via osascript

**Comment by donaldguy** [comment]
\[ Coming over to add on from xref in https://github.com/FelixKratz/SketchyBar/discussions/236#discussioncomment-3414316 \]  

my solution for this particular problem is to instead use https://appmakes.io/paletro to have a ~"Command Pallete" approach 

I tend to prefer that standalone one (by the same indie dev as Typora) specifically, but there is also a similar functionality in [Raycast](https://www.raycast.com/) under the Navigation "extension" that ships in core and I've also seen it done in some [Alfred](https://www.alfredapp.com/) Workflows (and if you are an all-OSS type, maybe there's similar for [Quicksilver](https://github.com/quicksilver/Quicksilver), etc. just haven't come across it myself)

I am not a mouse-hater by any means - but if you are gonna use mouse, I agree with Felix that the native menubar on autohide does a pretty good job 

but lest you haven't tried it out cause unaware it was an option or just ~mental set about the task, I wanted to encourage the people on this issue to think about trying (having the option of) making menu navigation/selection a keyboard-driven operation instead :-)

\[You could also split the difference and use <kbd><kbd>Ctrl</kbd><kbd>F2</kbd></kbd>, etc from [Full Keyboard Access](https://support.apple.com/guide/mac-help/navigate-your-mac-using-full-keyboard-access-mchlc06d1059/mac) to get up there (like I remember doing with Alt when I was a windows user) and then use the mouse for the last mile \]

**Comment by hunterliao29** [comment]
Come across this issue while working on my setup. 

My solution is using Alfred workflow that can query and toggle top-level menus items. (https://github.com/BenziAhamed/Menu-Bar-Search)

Inside the workflow there is a binary that might be useful if anyone want to create a component for top level menu.
