### ISSUE TITLE
space index in `$INFO` for `space_change` event 

### ISSUE THREAD

**Issue by teelahti** [FelixKratz/SketchyBar#175]
I'm building my own bar, and since the current spaces implementation doesn't support what I need started to build my own. I was surprised to find that the SketchyBar `space_change` event doesn't contain any useful payload. If SketchyBar internally knows the space index wouldn't it be easy to send that as `$INFO` payload?

**Comment by FelixKratz** [comment]
Yes that would be easy and I would accept a pull request for something like this. Some care has to be taken to properly handle multiple displays, as an item can show on arbitrarily many screens. So probably a json payload with dids and sids would be the best solution.

This is an example of how to easily add env_vars to the script call:
https://github.com/FelixKratz/SketchyBar/blob/88a7fffba566dfc98e927c2404f3f0ac6776ab68/src/bar_manager.c#L465

and this is the function that would need to generate the payload JSON:
https://github.com/FelixKratz/SketchyBar/blob/88a7fffba566dfc98e927c2404f3f0ac6776ab68/src/bar_manager.c#L475

Have you looked at the space components? They send `$SID` and `$DID` as env vars to their scripts already.

**Comment by teelahti** [comment]
> have you looked at the space components? They send `$SID` and `$DID` as env vars to their scripts already.

I started from them, but I was unable to configure them as I wanted: Show all spaces of all displays on my primary display SketchyBar (which is the only bar I have, trying to use the notch area to something useful). 

RE: PR for the `$INFO`: my C is so rusty that I probably won't create a PR.

**Comment by FelixKratz** [comment]
Ah, yes that is not possible with the space components and must be created from scratch. If you use yabai this is very simple already.

Alright, then I will look into implementing this once I get some free time, as this is definitely an oversight by me. Will do the same for the display_change event when I am at it.

**Comment by teelahti** [comment]
I'm using Yabai so nothing too bad but not trivial either. It requires some tweaking since Yabai's space changed is triggered only if you actually switch a space, not when you change focus from display and app to another. So you need to collect both `space_changed` and `window_focused`, like:

```bash
yabai -m signal --add event=window_focused active=yes \
    action="sketchybar --trigger yabai_space_changed ORIGIN=window_focused SPACE=\$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq '.space') &> /dev/null"

yabai -m signal --add event=space_changed active=yes \
    action="sketchybar --trigger yabai_space_changed ORIGIN=space_changed SPACE=\$(yabai -m query --spaces | jq -c '.[] | select(.id == \$YABAI_SPACE_ID).index') &> /dev/null"
```

...but right now the above segfaults SketchyBar in case the SPACE env variable is empty. With a bit of polishing I can make this work.

**Comment by FelixKratz** [comment]
Thank you for reporting the segfault, should be fixed by bcb8b664429fa347ec7b4bfe372a279b085cf847

**Comment by FelixKratz** [comment]
With fa7c8c9c4c2fe0037188226b21afb2af38922c12 you can ignore the display and space association for any item, so if you want to show the space components on all displays you can set the `ignore_association` boolean:
```bash
sketchybar  --set <space name> ignore_association=on
```
This is something that was on my todo already, but it might help you to achieve what you are aiming for while using the space components.

**Comment by teelahti** [comment]
Thanks! I might test that when it is on next Brew release. I got my own version fully working literally 5 minutes ago and I'm happy with it: Yabai events based space change indicator is almost immediate.
