### ISSUE TITLE
Aliases with click_script property

### ISSUE THREAD

**Issue by cagdassalur** [FelixKratz/SketchyBar#177]
Is this achievable? I tried adding a click script to my alias `Control Center,Sound` but found that it's not working.

```
sketchybar --add alias "Control Center,Sound" left click_script="~/.config/sketchybar/plugins/muter-click.sh"
```

**Comment by FelixKratz** [comment]
My aliases are all clickable: https://github.com/FelixKratz/dotfiles/blob/master/.config/sketchybar/items/system.sh.
The minimal example will not work because it misses the --set command, if you do it like this it should be working:
```bash
sketchybar --add alias "Control Center,Sound" left \
           --set "Control Center,Sound" click_script="~/.config/sketchybar/plugins/muter-click.sh"
```

**Comment by cagdassalur** [comment]
Ah great! Initially i tried setting a name for alias and using that for `set`(which failed), never occured to me that i can use that identifier string as a name. Thanks for the quick reply! ❤️
