### ISSUE TITLE
Items don't show on right hand side

### ISSUE THREAD

**Issue by rhyses-pieces** [FelixKratz/SketchyBar#183]
Hello! I'm really glad to find this since I was using spacebar previously, but it didn't have all the functionality I wanted out of it.

However, I've noticed something strange when I was setting up my sketchbar config file. I can't seem to add items to the right-hand side of the bar? The behavior seems inconsistent whenever I'm trying to fix my config file and restart the sketchybar homebrew service.

Here's a screenshot of the behavior in question:
<img alt="Screen Shot 2022-05-14 at 5 02 23 AM" src="https://user-images.githubusercontent.com/10332868/168418982-4ebb0be4-c23f-4c85-a704-120c1a63aa49.png">

And here's my (really messy) config file:
https://gist.github.com/rhyses-pieces/7a325a5df99d5ac7cea810ebdfc39b15

**Comment by FelixKratz** [comment]
There should be no empty lines between concatenated lines. I think you will have to remove line 83.

**Comment by rhyses-pieces** [comment]
So I did what you suggested and I've updated my gist with the (sorta) cleaned up config. But I keep seeing an error on line 98. Not sure what could be wrong there?

<img width="682" alt="Screen Shot 2022-05-14 at 11 51 23 AM" src="https://user-images.githubusercontent.com/10332868/168439240-3f550bc8-c7ba-4149-8240-f7f3f9342205.png">

**Comment by FelixKratz** [comment]
Check if there is a space after the „/„ in the line before, the bash line concatenation breaks if there are whitespaces after the escape character. I will have a closer look at the file later. I will also add a debugging section to the website.

**Comment by FelixKratz** [comment]
There are two trailing whitespaces on line 97 after the "\" this is the problem.

**Comment by FelixKratz** [comment]
I will close this as it is not an issue that I can fix. Please report back here if you need further assistance.

**Comment by rhyses-pieces** [comment]
Man... it turns out there was some sneaky whitespace after the escape character. I cleaned that up and now  Thanks for the help!

**Comment by FelixKratz** [comment]
I have added some debugging steps to the website, as I can imagine other people might also run into this problem. In fact, I also stumbled over it a couple of times and it is very hard to spot without proper syntax highlighting. 
https://felixkratz.github.io/SketchyBar/config/tricks#debugging-problems
