### ISSUE TITLE
topmost is broken

### ISSUE THREAD

**Issue by es183923** [FelixKratz/SketchyBar#185]
I am unable to set the bar as topmost now.

With the following config: 
```sh
#!/bin/zsh
sketchybar --bar height=40 topmost=on color=0xFF000000
echo "sketchybar configuration loaded.."
```

I just get this:
![CleanShot 2022-05-16 at 17 33 35](https://user-images.githubusercontent.com/72744903/168686251-7069d2b2-707b-4bae-8d2e-2abbda86c406.png)

Instead, the top 40 pixels should all be black, not just the stuff under the menu bar.

device: 2020 13" M1 MacBook Pro
os: macOS Monterey 12.4 (same issue on 12.3.1 tho)
sketchybar version: latest, b59b58499fc34734f61fe27555f08daffa7b5064

**Comment by es183923** [comment]
It works on commit cef5342, but nothing after that.

**Comment by FelixKratz** [comment]
Thanks for reporting. Should be fixed now.

**Comment by es183923** [comment]
Thanks for the quick fix! I spent a long time thinking that sketchybar was completely broken, since the sketchybar height is the same as the normal menu bar height 😄

**Comment by FelixKratz** [comment]
It was a silly typo that led to this, and since I don't use the property in my own config I didn't get it. I have since made a new hotfix release where this should be fixed.

If I have bricked something else please report it, I will fix it ASAP. Also good example why we need #138.
