### ISSUE TITLE
After uninstall, brew upgrade fails

### ISSUE THREAD

**Issue by ibehnam** [FelixKratz/SketchyBar#189]
I followed the instructions in the documentation page to uninstall via `brew`. But now when I do `brew upgrade`, I get this error:
```
brew:4: command not found: sketchybar
```
What should I do?

**Comment by FelixKratz** [comment]
Remove the brew command overloads from .zshrc

**Comment by ibehnam** [comment]
> Remove the brew command overloads from .zshrc

Thanks for your reply. I checked my .zshrc and there is no brew command overload there.

**Comment by FelixKratz** [comment]
You might need to open a new terminal for the changes to take effect

**Comment by ibehnam** [comment]
Thanks, I just restarted terminal and the problem is solved.
