### ISSUE TITLE
build failure on darwin with -fno-common toolchains: duplicate symbol '_g_bar_manager' in bin/workspace.om sketchybar-f11c76.o

### ISSUE THREAD

**Issue by trofi** [FelixKratz/SketchyBar#192]
When building with `llvm-11` or later (`llvm-11` changed `-fcommon` flag to `-fno-common`) `sketchybar` fails as: https://hydra.nixos.org/log/njx9rird6za4wy46297nbff23w89170c-sketchybar-2.5.2.drv

```
...
duplicate symbol '_g_mach_server' in:
    /private/tmp/nix-build-sketchybar-2.5.2.drv-0/sketchybar-f11c76.o
    bin/workspace.om
duplicate symbol '_g_bar_manager' in:
    /private/tmp/nix-build-sketchybar-2.5.2.drv-0/sketchybar-f11c76.o
    bin/workspace.om
duplicate symbol '_g_event_loop' in:
    /private/tmp/nix-build-sketchybar-2.5.2.drv-0/sketchybar-f11c76.o
    bin/workspace.om
```

I think multiple definition happens in https://github.com/FelixKratz/SketchyBar/blob/master/src/bar_manager.h#L45

```c
struct bar_manager g_bar_manager;
```

`gcc-10` did a similar change (`-fno-common` section): https://gcc.gnu.org/gcc-10/porting_to.html

The usual fix is to move definitions of globals to .c files and leave only `extern` declarations in .h files.

**Comment by FelixKratz** [comment]
I have not created the nix formula, I believe it was created by @azuwis, maybe he can help updating it. This fix will be available in the next release.

**Comment by azuwis** [comment]
When next release is ready, I'll update the sketchybar nix package.
