### ISSUE TITLE
[Feature request] Option to provide different y_offset for different monitors

### ISSUE THREAD

**Issue by B1T3X** [FelixKratz/SketchyBar#195]
Hi,
First of all I'd like to say that I'm absolutely LOVING SketchyBar. It's been a game changer for me. Actually got to it from SketchyVim.
One thing that I encountered is that I hid the notch on the main built-in display using a program called Forehead and just used `y_offset` to seamlessly draw the bar beneath it.

However, this offsets it on all of the other displays and I'm left with a bar that draws much lower than the screen height.
Would it be possible to implement different y_offset for different monitors? Is there any other option that I'm unaware of that could solve my problem?

Thanks in advance!
Orel

**Comment by FelixKratz** [comment]
I have just added this feature: fcef6cc611b4814b87d866f0c1c14f8ebd851cae

If you install from the current head version:
```bash
brew uninstall sketchybar
brew install sketchybar --head
brew services restart sketchybar
```
you have access to the new `notch_offset` property:
```bash
sketchybar --bar notch_offset=32
```

**Comment by B1T3X** [comment]
Thank you so much! Works like a charm :)
