### ISSUE TITLE
Aliases on Catalina: No screen recording prompt shown

### ISSUE THREAD

**Issue by Verneri** [FelixKratz/SketchyBar#196]
I can't seem to get sketchybar to request screen recording permissions. I tried using the example setup from https://github.com/FelixKratz/SketchyBar/discussions/47#discussion-3587958 but the "Control Center, *" items do not appear on the bar and sketchybar keeps telling "could not retrieve window details." when run from terminal. System language is Finnish if this might have something to do with the problem.

**Comment by Verneri** [comment]
macOS version is 10.15.17

**Comment by FelixKratz** [comment]
Can you post the result of the following command: `sketchybar —query default_menu_items`. This might bring us closer to the solution.

**Comment by FelixKratz** [comment]
Sadly I have no machine running Catalina, so everything provided here is mostly untested for catalina, but I know that I had to version check for >= 11.0 here:
https://github.com/FelixKratz/SketchyBar/blob/fcef6cc611b4814b87d866f0c1c14f8ebd851cae/src/alias.c#L58
because the code would otherwise not compile. You could try to add the binary of sketchbar to the screen capture permission pane manually, by checking where it is installed via: which sketchybar

**Comment by Verneri** [comment]
> ```shell
> sketchybar --query default_menu_items
> ```

```
[
	"Window Server,Menubar Bottom Edge", 
	"Window Server,Menubar Bottom Edge", 
	"Window Server,Menubar Bottom Edge", 
	"Window Server,Menubar Bottom Edge"
]
```

I tried manually add by drag and dropping but it does not accept the sketchybar

**Comment by FelixKratz** [comment]
I will try adding something tomorrow that should bring up the prompt on catalina as well.

**Comment by FelixKratz** [comment]
Can you try installing the current master version and see if the prompt is shown now, by executing the following snippet?
```bash
brew uninstall sketchybar
brew install sketchybar --head
brew services restart sketchybar
```
and after that, if you want to go back to the stable release v2.6.0:
```bash
brew uninstall sketchybar
brew install sketchybar
brew services restart sketchybar
```

**Comment by FelixKratz** [comment]
Then aliases are not supported with catalina, I have too little information on this to really find out what the root cause of this is.
