### ISSUE TITLE
toggling `hidden` is broken

### ISSUE THREAD

**Issue by es183923** [FelixKratz/SketchyBar#197]
No sketchybar:

![CleanShot 2022-06-12 at 19 49 37](https://user-images.githubusercontent.com/72744903/173258622-5a18a61c-261c-4996-a4f0-9d1308216a3b.png)
 
sketchybar started (with topmost=on):
![CleanShot 2022-06-12 at 19 49 50](https://user-images.githubusercontent.com/72744903/173258628-67412407-f7f6-42ec-9a50-8bb0e1067275.png)
 

Sketchybar started: (with topmost=on, hidden=on):
![CleanShot 2022-06-12 at 19 49 58](https://user-images.githubusercontent.com/72744903/173258641-5e283d9b-c022-4d96-bc9e-5f2d9c8711d8.png)

This happens after the merge of picky_redraw.

**Comment by FelixKratz** [comment]
Thanks for the report, should be fixed on master.
