### ISSUE TITLE
Padding of the bar itself

### ISSUE THREAD

**Issue by ssate** [FelixKratz/SketchyBar#20]
Would love to have the ability to add padding / screen margin around the bar itself.

**Comment by FelixKratz** [comment]
This should work as of 0bfd62d6f53d1c0e7efd321aec68d16cb152cf33 with the commands:
```bash
sketchybar -m config y_offset             5
sketchybar -m config margin               7
```

**Comment by ssate** [comment]
Awesome, thanks for this! Since this isn't currently homebrew official, how do you recommend going about the process of updating to the latest version?

**Comment by FelixKratz** [comment]
Just pull from master and run make update

**Comment by FelixKratz** [comment]
It is now also possible to add a border radius to the bar 0c08ca88c43935eb8b06452a39cacadbbb2f4178:
```bash
sketchybar -m config border_radius 10
```
