### ISSUE TITLE
Add `blur_radius` property to all items, brackets and popups

### ISSUE THREAD

**Issue by FelixKratz** [FelixKratz/SketchyBar#201]
With the new drawing logic in v2.7.0 it is possible to give each item a background blur, this could be used for nice blurred sections or to blur an image, e.g. a `popup.background.image` below other items or brackets.

Current implementation on master:
For item/bracket blur, e.g.:
```bash
sketchybar --set <name> blur_radius=50 background.drawing=on background.color=0x15000000
```
For popup blur, e.g.:
```bash
sketchybar --set <name> popup.blur_radius=50 popup.background.drawing=on popup.background.color=0x15000000
```

**Comment by FelixKratz** [comment]
This looks very nice, on the screenshot the blur is only half as strong as on screen.
![Screen Shot 2022-06-16 at 00 41 35](https://user-images.githubusercontent.com/22680421/173953805-dca4862f-b991-42d7-a7d0-8d6528b81b13.png)

**Comment by es183923** [comment]
It doesn't seem possible to set a background blur for an item, but not the bar.

<img width="729" alt="CleanShot 2022-06-15 at 22 17 43" src="https://user-images.githubusercontent.com/72744903/173976998-6bf9ed49-9e1c-4840-b68f-e1d2f5341833.png">

**Comment by FelixKratz** [comment]
Works fine here, how do you set the blur? The background of the item must have a non-transparent color, otherwise the blur is not applied: e.g. background.color=0x15000000

**Comment by FelixKratz** [comment]
With c07737dc4bad53339a6b92c5c08121d2afe682b2 the popups have a `blur_radius` property as well:
For item/bracket blur:
```bash
sketchybar --set <name> blur_radius=50 background.drawing=on background.color=0x15000000
```
For popup blur:
```bash
sketchybar --set <name> popup.blur_radius=50 popup.background.drawing=on popup.background.color=0x15000000
```

**Comment by es183923** [comment]
> Works fine here, how do you set the blur? The background of the item must have a non-transparent color, otherwise the blur is not applied: e.g. background.color=0x15000000

`background.color` is set as `0x30FFFFFF`

**Comment by es183923** [comment]
Thanks! I got the blur radius working. I had put `blur_radius` in the `--bar` config, instead of under `--default`.
