### ISSUE TITLE
Single bar - two monitors

### ISSUE THREAD

**Issue by PhrantiK** [FelixKratz/SketchyBar#212]
I have a main monitor in front of me and a side monitor at 90 degrees. Only the main screen has the bar displayed. 

Main screen has spaces 1-3 and side screen has spaces 4-6. 

Is there a way to make an icon highlight the space that has focus on the side monitor?

For example I have 6 icons on the bar on monitor one. If I switch to space 4 which is on the side monitor, I want only the 4th icon to highlight. Currently only 1-3 change color.

**Comment by FelixKratz** [comment]
Yes, try to set `ignore_association=on` for the space items that you want to show on all displays.
