### ISSUE TITLE
Possible to remove shadow?

### ISSUE THREAD

**Issue by AjayShanker-geek** [FelixKratz/SketchyBar#215]
Hi, love your project!

Btw I am having issue to switch off the shadow, which allow me to see SketchyBar clearing on my workspace

<img width="1728" alt="Screenshot 2022-07-16 at 6 18 01 PM" src="https://user-images.githubusercontent.com/26241915/179350778-953fa046-36d4-47c3-b105-6aab98815580.png">

**Comment by FelixKratz** [comment]
Could you possibly try to state again what you are trying to achieve? What shadow are you trying to disable? What commands did you try to disable the shadow and which of them did not work as expected?

Generally speaking, any shadow property is adjustable and can hence be disabled.

**Comment by AjayShanker-geek** [comment]
The SketchyBar is "darken" by my apps shadows. I been figuring to remove the shadow of the apps so that I am able to see SketchyBar.

**Comment by erics118** [comment]
yabai can disable all window shadows.

**Comment by FelixKratz** [comment]
Ah ok, try to set sketchybar to be topmost:
```bash
sketchybar --bar topmost=on
```
then sketchybar will draw on top of everything, including the shadows of other apps. You could also disable window shadows with yabai.

**Comment by AjayShanker-geek** [comment]
It worked, Cheers 👍🏾
