### ISSUE TITLE
Brackets effecting "click" for click scripts

### ISSUE THREAD

**Issue by robbierobs** [FelixKratz/SketchyBar#216]
I've noticed significant issues while trying to execute click scripts on bracketed items. It almost seems like the click is happening on the bracket itself and possibly not the item. 

Clicking multiple times or across the items to find a "sweet spot" works mostly.

**Comment by FelixKratz** [comment]
Thanks for reporting. I think I know why that is:
https://github.com/FelixKratz/SketchyBar/blob/92188903425c8a26cb189b99cbf3926a5fb44a21/src/event.c#L116
In this function I first get the bar item by its wid (which is only the pixel perfect rendering region without the transparent regions) and if that fails I get the item by its bounding rectangle. In a bracket the second step is never executed, as it will instead register the click for the bracket wid if the cursor is not perfectly above the rendering of a bracketed item.

Should be a fairly easy fix, will take care of this as soon as I can.
