### ISSUE TITLE
Animations are not running within brackets

### ISSUE THREAD

**Issue by robbierobs** [FelixKratz/SketchyBar#217]
First off, thank you for the quick fix to bracket click registration!

I am having an issue where the animate command is not functioning on an item inside of a bracket. The action just applies as if there were no animation being used.

This is not happening to icons, but to labels specifically.

**Comment by FelixKratz** [comment]
Could you provide a minimal example so I can reproduce this behavior?

**Comment by robbierobs** [comment]
After doing some digging and playing with it I've discovered that the animation does not take effect on labels or icons (The name itself). This was due to some ignorance on my part for assuming that positive integer values in icons/labels would take an effect and presuming it would work on text/glyph change as well. 

Sorry for the confusion and for opening up an issue. Everything is working as if should be.
