### ISSUE TITLE
Segmentation Fault on Click

### ISSUE THREAD

**Issue by FelixKratz** [FelixKratz/SketchyBar#219]
It seems the bar will crash in some cases on a click event.
Due to the crash report by @MathewBlanc I know where this is happening, but It seems I am not able to reproduce this at the moment.

_Originally posted by @MathewBlanc in https://github.com/FelixKratz/SketchyBar/discussions/218_
Here's the crash report from Console:
[sb_crashreport.txt](https://github.com/FelixKratz/SketchyBar/files/9177889/sb_crashreport.txt)

As for where it's happening, I have minimally modified the default config file:
[sb_config.txt](https://github.com/FelixKratz/SketchyBar/files/9177900/sb_config.txt)

**Comment by FelixKratz** [comment]
@MathewBlanc could you try the current master version? I think it should fix the segmentation fault. The curious thing is, that it should not be possible for the adid to be < 1 in the first place.

**Comment by MathewBlanc** [comment]
Forgive my ignorance, but how would I install the master version? I used homebrew to install it the first time

**Comment by FelixKratz** [comment]
You can install the current master version by:
```bash
brew services stop sketchybar
brew uninstall sketchybar
brew install sketchybar --head
brew services start sketchybar
```

and after testing you can switch back to the stable branch via:
```bash
brew services stop sketchybar
brew uninstall sketchybar
brew install sketchybar
brew services start sketchybar
```

Once this problem is resolved I will create a hotfix release.

**Comment by MathewBlanc** [comment]
Hi Felix, that seems to have fixed it, now I can click everywhere and nothing happens. Should I just stick with the master version for now? 

Also, is there anything else you'd like me to test to get more info on the bug? 🙂

**Comment by FelixKratz** [comment]
I will create a new release once #220 is resolved and then you could switch back to the stable branch. Could you check if clicks on items that you have created a `click_script` for still work? Now that I know it is the adid that is causing the problem I can investigate the bug in more detail by tracing it through the code.

**Comment by MathewBlanc** [comment]
Yeah, I've put in your [Simple Popup Menu](https://github.com/FelixKratz/SketchyBar/discussions/12?sort=new#discussioncomment-1843975) and the click seems to work without any issues now 👍

**Comment by FelixKratz** [comment]
The new release is out, you can safely switch back to the stable branch.
