### ISSUE TITLE
Remove spaces

### ISSUE THREAD

**Issue by andreicorpo** [FelixKratz/SketchyBar#23]
Is it possible to somehow remove all spaces?

**Comment by FelixKratz** [comment]
Can you explain a bit more what you mean? Do you want to remove the space items after some event occurs? Or do you want to remove them from the beginning? Or do you want to remove the actual macOS spaces?

**Comment by andreicorpo** [comment]
Yeah, so I wanted to remove all the `space` components with one command.

I wanted to remove them because  I sometimes move my spaces around and I wanted the bar to reflect this.

I did manage to do differently tho. 😄
