### ISSUE TITLE
Bracket `background.border_color`?

### ISSUE THREAD

**Issue by johnallen3d** [FelixKratz/SketchyBar#233]
According to the documentation [here](https://felixkratz.github.io/SketchyBar/config/components#item-bracket----group-items-in-eg-colored-sections).

> Brackets currently only support all background features

And [here](https://felixkratz.github.io/SketchyBar/config/items#background-properties) I see that background supports `border_color`. However when I try to set a border color on a bracket (e.g. `background.border_color=0xffffffff`) I do not see a border. Is this expected?

**Comment by FelixKratz** [comment]
Yes, this is to be expected, because the default `border_width` is 0. You will need to change the border width to something > 0 to see the border.

**Comment by johnallen3d** [comment]
🤦‍♂️ my bad, sorry!
