### ISSUE TITLE
Default Menu Items broke

### ISSUE THREAD

**Issue by matthewshammond** [FelixKratz/SketchyBar#237]
I updated to 2.8.4 today and now my items that are sourced form default_menu_items no longer work.

the output of `sketchybar --query default_menu_items` produces
```
[

]
```

**Comment by FelixKratz** [comment]
The output you receive is what you get if the screen capture permission is not given.

It works here:
```bash
 # sketchybar --query default_menu_items
[
	"Control Center,Battery",
	"Control Center,WiFi",
	"LinkedNotesUIService,Window",
	"Control Center,Clock",
	"TextInputMenuAgent,Item-0",
	"Control Center,Sound",
	"Control Center,NowPlaying",
	"Control Center,UserSwitcher",
	"Control Center,BentoBox",
	"SystemUIServer,AppleTimeMachineExtra",
	"Control Center,Clock",
	"LuLu,Item-0",
	"WireGuard,Item-0"
]
```

Make sure you have given screen recording permissions. Maybe it helps to remove sketchybar from the list and let it re-request these permissions. Also keep in mind that the terminal (e.g. Alacritty) will need those permissions granted as well if sketchybar is run directly from there.

**Comment by matthewshammond** [comment]
Thank you and my apologies.  I did not realize when I updated that Sketchybar was no longer given access to screen recording.  It's working again.

**Comment by FelixKratz** [comment]
This has to do with the way I chose to distribute the code and the binary. When brew installs sketchybar, it does not load a precompiled and signed binary, rather I have chosen to compile the actual source code during the brew install and sign it with an ad-hoc certificate on device.

While this is elegant from a FOSS and transparency point of view it means that the code signature will be different after every update. The gatekeeper will recognize the updated binary as a completely unknown binary without any permissions.
