### ISSUE TITLE
If bar is not `sticky` associated items are not drawn properly

### ISSUE THREAD

**Issue by ninjaguppy** [FelixKratz/SketchyBar#239]
I've been traveling most of the summer so I haven't  been at my laptop. When I updated sketchybar---I couldn't tell you what version I was on, but the =lazy= property was still valid---I had to fix a ton of issues. I was able to get almost all of them except for the plugins that are associated with specific spaces. When I initialize sketchybar on a space with one of these plugins, it appears, but as soon as I change spaces, none of them are visible (even the one I could see before).

[[https://github.com/ninjaguppy/dotfiles/tree/main/.config/sketchybar][Here is a link]] to my setup! I am running yabai and skhd as well and (if its relevant) my config files for them are in the same directory!

**Comment by FelixKratz** [comment]
The new hotfix release fixes this.
