### ISSUE TITLE
blur

### ISSUE THREAD

**Issue by es183923** [FelixKratz/SketchyBar#24]
It would be nice to set a blur for the bar, so that the bar won't have to be completely transparent with a bit of color. It would be similar to the Big Sur menu bar.
```sh
sketchybar -m config blur_radius 4
```

**Comment by FelixKratz** [comment]
This is possible since d83c698fb82986fb31afaad149c3d1dbc0b2654d. I will create a new brew release when I am done with some other improvements I want to make, till then you can install from HEAD if you want to try it out.
