### ISSUE TITLE
Cannot animate popup properties

### ISSUE THREAD

**Issue by crissNb** [FelixKratz/SketchyBar#252]
I've tried the following command:
`sketchybar --animate sin 30 --set mypopup popup.height=50`

The height of the popup changes to 50 instantly without using the animation curve. It seems like I'm unable to animate other popup properties as well (I've tried popup.y_offset).

**Comment by FelixKratz** [comment]
I forgot to implement the animations for popups when I designed the animation system. It is possible to animate those properties now.
