### ISSUE TITLE
Commands exit with 1 when seemingly no error occurred

### ISSUE THREAD

**Issue by net** [FelixKratz/SketchyBar#254]
After a recent update a lot of my sketchybar commands are exiting with 1 even though they still perform their action and don't output anything to stdout or stderr.

Example of commands that perform their action but exit with 1 for me:

```
sketchybar -m \
    --set 3 associated_space=1 \
           associated_display=1 \
           icon="􀃋" \
           label="1" \
           click_script="yabai -m space --focus 1
```

```
sketchybar -m --move 5 after 3
```

I'm on commit [44fd3a1](https://github.com/FelixKratz/SketchyBar/commit/44fd3a138d42fa7a11194b785cbfbf4c9e481fed).

**Comment by FelixKratz** [comment]
I think this commit fixed the problem: https://github.com/FelixKratz/SketchyBar/commit/bf3d88da880b705b17063cfe6a7037bcd63a4558 it is a change in the client program, thus the fix will only be available when the new binary is installed to PATH. It will be contained in v2.9.1, which will be released very soon.

**Comment by FelixKratz** [comment]
New release is out, should be fixed now.

**Comment by net** [comment]
Thank you!
