### ISSUE TITLE
Blinking animation

### ISSUE THREAD

**Issue by AjayShanker-geek** [FelixKratz/SketchyBar#255]
Hi, I notice an active application display blinking on SketchyBar when switching work space. Btw, I used base on your experimental dotfile branch.

https://user-images.githubusercontent.com/26241915/193386563-1297565c-56d9-409f-ae72-94f2ca3a1e7f.mov

**Comment by FelixKratz** [comment]
I would need a bit more detail to debug this. Could you share your config? Do you notice the blinking as well if you use my unmodified experimental dotfiles?

**Comment by AjayShanker-geek** [comment]
Hi, I'm currently reinstall using unmodified experimental dotfiles and the issue is still seen. 

Model: MacBook Pro M1 Max
macOS: Version 13.0 Beta (22A5358e)

**Comment by FelixKratz** [comment]
> macOS: Version 13.0 Beta (22A5358e)
Thats probably why. I will upgrade to Ventura as soon as it is released and release a fix for SketchyBar. Beta software will always have quirks and since I am using private frameworks, there can be changes made to those during beta phase. In this case I am fairly certain that window ordering groups are not working as expected anymore.

**Comment by AjayShanker-geek** [comment]
Yup I assume too, thanks man. Love your project!

I will close the issue for now till the official release👍🏽.

**Comment by shndowbots** [comment]
This happens to me too, but only on the sketchybar

**Comment by AjayShanker-geek** [comment]
Hi @FelixKratz, is there a better way to test your latest commit?

**Comment by FelixKratz** [comment]
> Hi @FelixKratz, is there a better way to test your latest commit?

Normally you could install the current master version of sketchybar via:
```bash
brew install sketchybar --head
```
but it seems brew refuses to make the binary currently since the new commandline tools for macOS 13.0 are not yet available.

So currently it is best to clone the repo and run
```bash
make
./bin/sketchybar
```
in the cloned repository.

**Comment by AjayShanker-geek** [comment]
Thanks, I was trying to reinstall with head flag but facing errors.

`32d85ff` commit build is working for me.
