### ISSUE TITLE
sketchybar: could not acquire lock-file! abort..

### ISSUE THREAD

**Issue by yawarakaides** [FelixKratz/SketchyBar#261]
I've tried compiling Sketchybar by source and also tried installing it via Homebrew. However it keeps showing this error every time I run it. `sketchybar: could not acquire lock-file! abort..`

**Comment by FelixKratz** [comment]
See https://github.com/FelixKratz/SketchyBar/discussions/235. SketchyBar is probably already running as a brew service.
