### ISSUE TITLE
Window indicator in space component

### ISSUE THREAD

**Issue by azuwis** [FelixKratz/SketchyBar#27]
https://github.com/kkga/nibar has a nice feature that it will show a `°` symbol next to the space label if the space has window.

![](https://github.com/kkga/nibar/blob/master/ss.png?raw=true)

Just for your reference.

**Comment by FelixKratz** [comment]
I would believe that this is already possible by attaching a script to each space component that querys yabai and subscribes to window events, changing the space icon based on the result from the yabai query.

**Comment by FelixKratz** [comment]
This will probably also get easier when I am done with #32.

**Comment by azuwis** [comment]
Space window indicator
<img width="206" alt="Screen Shot 2021-09-06 at 21 41 31" src="https://user-images.githubusercontent.com/9315/132226232-3e77e65e-a5e9-44e8-bf09-13bfafe57dbd.png">

~/.config/sketchybar/sketchybarrc
```
for i in {1..8}
do
  sketchybar -m add component space space$i left
  sketchybar -m set space$i associated_display 1
  sketchybar -m set space$i associated_space $i
  sketchybar -m set space$i icon $i
done

sketchybar -m add item dummy left
sketchybar -m subscribe dummy space_change
```

~/.config/sketchybar/plugins/space.sh
```
#!/bin/bash

yabai -m query --spaces | jq -r '.[] | [.index, .windows[0]] | @sh' | \
  while read -r index window
  do
    if [ "$window" = "null" ]
    then
      sketchybar -m set "space${index}" icon "${index}"
    else
      sketchybar -m set "space${index}" icon "${index}°"
    fi
  done
```

_Originally posted by @azuwis in https://github.com/FelixKratz/SketchyBar/discussions/12#discussioncomment-1286504_

**Comment by azuwis** [comment]
Can I subscribe an event, but not associate it to any bar item?

**Comment by FelixKratz** [comment]
In your example you are missing the line
```bash
sketchybar -m set dummy script "~/.config/sketchybar/plugins/space.sh"
```
I believe.

Only items can subscribe to events currently. What exactly do you want to achieve by subscribing an event and not associate an item? There would be no script that is executed.

**Comment by azuwis** [comment]
I forgot the script line.

I want to run script for event without adding a bar item, like the space.sh script above.

Also, I have one script to manage multiple bar items, it feels odd to associate only one of them.
