### ISSUE TITLE
Garbage data in notification's $INFO

### ISSUE THREAD

**Issue by izeau** [FelixKratz/SketchyBar#271]
Hi Felix, thanks for this software, loving it so far!

I'm having a problem with notifications however, which you may be able to reproduce using e.g. your `spotify.sh` plugin.

It looks like the buffer passed to `$INFO` is improperly cleaned after a notification, which means the resulting JSON in `com.spotify.client.PlaybackStateChanged` may be invalid. This does not happen all the time but it's quite easy to reproduce by playing a song with e.g. a long band name then quickly switching to a song with a shorter one.

For instance, playing [I'll Make Everything — The World Is A Beautiful Place & I Am No Longer Afraid To Die](https://open.spotify.com/track/40rLFR9ZZiMMLnye9nJnxU) then [Directions — Mat Kerekes](https://open.spotify.com/track/3iFOzfUrSSyfvs2HzJ5GhL?si=c5e16729b76d4aba) (or about any other title really 😛) produces the following `INFO` env vars:

```json
{
  "Player State" : "Playing",
  "Name" : "I'll Make Everything",
  "Track ID" : "spotify:track:40rLFR9ZZiMMLnye9nJnxU",
  "Album" : "Always Foreign",
  "Disc Number" : 1,
  "Play Count" : 0,
  "Popularity" : 18,
  "Has Artwork" : true,
  "Duration" : 146560,
  "Artist" : "The World Is A Beautiful Place & I Am No Longer Afraid To Die",
  "Album Artist" : "The World Is A Beautiful Place & I Am No Longer Afraid To Die",
  "Playback Position" : 0.030999999493360519,
  "Track Number" : 1
}
{
  "Player State" : "Playing",
  "Name" : "Direction",
  "Track ID" : "spotify:track:3iFOzfUrSSyfvs2HzJ5GhL",
  "Album" : "Luna & the Wild Blue Everything",
  "Disc Number" : 1,
  "Play Count" : 0,
  "Popularity" : 48,
  "Has Artwork" : true,
  "Duration" : 170306,
  "Artist" : "Mat Kerekes",
  "Album Artist" : "Mat Kerekes",
  "Playback Position" : 0.027000000700354576,
  "Track Number" : 2
}No Longer Afraid To Die",
  "Playback Position" : 0.030999999493360519,
  "Track Number" : 1
}
```

Your script handles it just fine because jq just drops the remaining data (and prints an error to stderr), however a stricter parser such as Python's needs a bit of persuasion:

```py
info = os.environ.get("INFO", "{}")

try:
  info = json.loads(info)
except json.JSONDecodeError as e:
  info = json.loads(info[:e.pos])
```

I'm using SketchyBar v2.10.1 with MacOS 12.5 on an M1 MBP.

**Comment by FelixKratz** [comment]
I think I had decided some time ago that this is a problem originating from spotify. I am not reusing the previous buffer anywhere, so the info passed from spotify to the distributed notification center must be garbage already, but I may look at this again to prove myself wrong.

**Comment by izeau** [comment]
I did not check further to see if it was coming from Spotify (could not find a way to do that without compiling something and I am not familiar with MacOS APIs to be honest); guess I can keep this workaround :)

Thanks for the quick response!

**Comment by FelixKratz** [comment]
I think I have found the culprit, it is a subtle detail I got wrong that leads to this:
Accessing the bytes of an `NSData` object and casting it to a `char*` is actually not safe, because the bytes in NSData are `char`s but the bytes of `NSData` are not terminated by `0x0`.

It is a trivial fix, I will look into it later.

**Comment by neutonfoo** [comment]
@FelixKratz Any idea when the fix might be in next release / on Homebrew? 👀

**Comment by FelixKratz** [comment]
> @FelixKratz Any idea when the fix might be in next release / on Homebrew? 👀

I have released a hotfix just now. Was planning to add some other things to the new release, but they are not ready just yet.
