### ISSUE TITLE
Ventura Support

### ISSUE THREAD

**Issue by FelixKratz** [FelixKratz/SketchyBar#272]
macOS Ventura is currently not supported fully. There are some bugs lurking, which I will have to fix.
This issue can be used to track issues and support for Ventura.

Known Bugs:
- #255
- Further problems related to window ordering
- Occasional White Flickering
- Mouse exited/exited.global events not properly handled
- Client dies with segmentation fault on invalid command
- It is not possible to install sketchybar via brew, because the latest stable xCode CLT does not support Ventura

**Comment by izeau** [comment]
It introduces an bug (at least on Monterey): when changing the bar height (which forces a full redraw I guess), the bar background is drawn on top of the items.

**Comment by FelixKratz** [comment]
> It introduces an bug (at least on Monterey): when changing the bar height (which forces a full redraw I guess), the bar background is drawn on top of the items.

Thanks for the feedback, I think I have mitigated this effect in this commit: c47bac42b43b2f753ac300e602b4423799912f3e

Sadly some private functions have changed their behavior from Monterey to Ventura, which makes it a bit cumbersome to properly test this.

**Comment by FelixKratz** [comment]
Ventura is fully supported on current master, I am still waiting with the release till Apple publishes 14.1 command line tools.
