### ISSUE TITLE
How about adding a configurable log destination for executions of scripts?

### ISSUE THREAD

**Issue by davidh-unmind** [FelixKratz/SketchyBar#277]

**Comment by FelixKratz** [comment]
You can already do something like this, just set the script up this way in sketchybar, i.e. to append to the output:
```bash
sketchybar --set <name> script="$PLUGIN_DIR/script.sh >> $HOME/output.txt"
```
or to reset the output:
```bash
sketchybar --set <name> script="$PLUGIN_DIR/script.sh > $HOME/output.txt"
```
I think this is easier than some property backed into sketchybar directly
