### ISSUE TITLE
How does the sketchybar-app-font work?

### ISSUE THREAD

**Issue by jayson** [FelixKratz/SketchyBar#278]
I've noticed that my bar at the top shows all these `:firefox:` and `:calendar:` sections. I tried to install the sketchybar-app-font but I'm not sure how to make it work. How is everyone else getting their icons to show up in the bar?

**Comment by FelixKratz** [comment]
Have a look at my dotfiles. You only need to install the font:
```bash
curl https://github.com/kvndrsslr/sketchybar-app-font/releases/download/v1.0.3/sketchybar-app-font.ttf > $HOME/Library/Fonts/sketchybar-app-font.ttf
```
and everything should be working. Now you can see the font in Font Book and use its ligatures to display app icons.
