### ISSUE TITLE
Flicker (redraw/refresh) on workspace change (master, Ventura)

### ISSUE THREAD

**Issue by steven-lang** [FelixKratz/SketchyBar#283]
Hey there,

I'm on Ventura and just installed the latest master head (default config). When switching workspaces I'm experiencing a flickering (I guess the bar is redrawing?). I'm using yabai with SIP disabled. Here is a video showcasing the behavior:

https://user-images.githubusercontent.com/17625341/200246320-6efd68ed-b71b-4080-8b0e-128709fb0900.mov

**Comment by FelixKratz** [comment]
This is because in the default config the bar is set to `sticky=off` because of a problem with how the WindowServer handles sticky windows in animations #220.

What you want to do is set the bar to be sticky if you have disabled space changing animations:
```bash
sketchybar --bar sticky=on
```

**Comment by steven-lang** [comment]
That fixed it, thanks :-)
