### ISSUE TITLE
Does Sketchybar work without yabai?

### ISSUE THREAD

**Issue by bassamsdata** [FelixKratz/SketchyBar#286]
Since I'm using Amethyst instead of Yabai, does Sketchybar work without Yabai? 
Particularly I'm interested in **spaces**, because I read some scripts and found that they rely on Yabai.

As I couldn't find an answer in the Q&A, I posted this question here.
As a note, I use Amethyst and karabiner.

I appreciate your help and Thanks a lot in advance.

**Comment by FelixKratz** [comment]
Yes, sketchybar works without yabai. Some of the scripts posted in the plugins discussion use yabai functionality but it is not needed generally. For example the default config doesn't use yabai for anything except for focusing spaces on click, but that can be changed as well.
