### ISSUE TITLE
There are no sound and brightness popups when sketchybar is started

### ISSUE THREAD

**Issue by andynameistaken** [FelixKratz/SketchyBar#297]
## Issue
When `sketchybar` is started there are no sound and brightness popup
## Workaround
Stop service and restart computer

**Comment by FelixKratz** [comment]
Could you provide an example, because I think I don‘t understand what you mean.

**Comment by FelixKratz** [comment]
I believe I understand now, you mean the on screen macOS ui that show volume and brightness change? If you run my config I have disabled it in sketchybarrc: 
https://github.com/FelixKratz/dotfiles/blob/e9d4a7bd18b59aaa0360803847cf5829c9a1d25c/.config/sketchybar/sketchybarrc#L18
This has nothing to do with sketchybar, but rather with my config.
