### ISSUE TITLE
Can sketchybar be hidden in expose?

### ISSUE THREAD

**Issue by bashu** [FelixKratz/SketchyBar#304]
Can sketchybar be hidden in an expose?

Same question for fullscreen videos on youtube, I placed the bar at the bottom and it hides media player's control.

**Comment by FelixKratz** [comment]
sketchybar can be hidden with the command:
```bash
sketchybar --bar hidden=on
```
I use Safari and have no problems with fullscreen videos. I think I have explicitly checked for native fullscreen spaces and they are ignored by sketchybar:
https://github.com/FelixKratz/SketchyBar/blob/1e4725e1a91ecb9d5f2c6cfcfca747719c6df17e/src/bar_manager.c#L786

Hiding sketchybar by default could be done, I believe it would require accessibility permissions though.
I am trying to not require any additional permissions by default, i.e. screen capture access is only needed when actually using aliases.

The relevant AX keys for this are:
```bash
AXExposeShowAllWindows
AXExposeShowDesktop
AXExposeShowFrontWindows
AXExposeExit
```

If you are using yabai this is easily scriptable, as yabai has those permissions and event emits an event for it:
```bash
yabai -m signal --add event=mission_control_enter action="sketchybar --bar hidden=on"
yabai -m signal --add event=mission_control_exit action="sketchybar --bar hidden=off"
```

**Comment by bashu** [comment]
> I use Safari and have no problems with fullscreen videos

Yes, I can confirm that it works in safari, but in firefox "full screen" mode on youtube give me this:

![Screenshot 2022-12-18 at 10 53 46 PM](https://user-images.githubusercontent.com/144783/208310003-f251ace7-ec28-41bd-8146-aa8fedac81b7.png)

**Comment by bashu** [comment]
Google Chrome also works, so it's only FF

**Comment by bashu** [comment]
> I use Safari and have no problems with fullscreen videos.

**Comment by FelixKratz** [comment]
It only happens if sketchybar is in `topmost` mode.

Disable sketchybar as topmost:
```bash
sketchybar --bar topmost=off
```

**Comment by bashu** [comment]
> It only happens if sketchybar is in topmost mode.

Yes, it was topmoste mode

**Comment by FelixKratz** [comment]
I have found a window tag bit that I can set to hide sketchybar in expose via the WindowServer, on current master the bar will disappear and reappear when entering/exiting expose.
