### ISSUE TITLE
v2.12.1 completely broke my bar

### ISSUE THREAD

**Issue by manc1n1** [FelixKratz/SketchyBar#306]
`v2.12.0`
<img width="629" alt="Screen Shot 2022-12-22 at 11 50 06 AM" src="https://user-images.githubusercontent.com/18316547/209185578-f93597e6-5233-46e5-aa2f-e96beee2a252.png">

`v2.12.1`
<img width="1728" alt="Screen Shot 2022-12-22 at 11 49 08 AM" src="https://user-images.githubusercontent.com/18316547/209185393-2e04f942-f643-453a-82b0-574a7e005f6f.png">

**Comment by manc1n1** [comment]
> Which OS? Works for my Big Sur and Ventura machines, possibly some api is broken. Maybe I have to partially revert the changes....

<img width="245" alt="Screen Shot 2022-12-22 at 12 09 54 PM" src="https://user-images.githubusercontent.com/18316547/209189106-95f4c96e-c661-4010-a9c1-cedf45e6f712.png">

**Comment by FelixKratz** [comment]
Ok, I didn't test for Monterey... I'll revert the window system back to the previous method for every operating system below Ventura, as I have no way to test retrocompatibility otherwise, give me a second.

**Comment by manc1n1** [comment]
Thank you! I could just revert to `v2.12.0` if you could help me do that with `brew` if that makes it easier.

**Comment by FelixKratz** [comment]
Could you try the newest version? I have reverted to the old window system for all version prior to ventura, so it should be fixed

**Comment by manc1n1** [comment]
Yes, I will get back to you. Thank you!

**Comment by FelixKratz** [comment]
It is so odd that it would work on Big Sur and Ventura but not on Monterey, but I guess thats what I have to expect when using apples private and undocumented frameworks to do this stuff. Glad that it is working again.

**Comment by manc1n1** [comment]
Glad to do my part! Thanks for the quick response and action. Yeah, it's always tough trying to do this stuff with Apple products for sure. Great repo though, keep up the great work!

**Comment by FelixKratz** [comment]
I really would like to have the new window system work on Monetery, this would drastically reduce the divergence of code for system versions. I think I know what was causing the problems in 2.12.1 and 2.12.2 is probably a too drastic revert.

Could you try the current HEAD version on Monterey and tell me if it is working properly? You can do so via brew:

```bash
brew uninstall sketchybar
brew install sketchybar --head
brew services restart sketchybar
```
and after testing it you can switch back to the current 2.12.2 release via:
```bash
brew uninstall sketchybar
brew install sketchybar
brew services restart sketchybar
```

**Comment by manc1n1** [comment]
I will try this now. Will get back to you shortly.

**Comment by FelixKratz** [comment]
Thanks! Thats good news, 2.12.3 will contain the new window system for all other macOS versions, but I will wait a bit with the new release since it is not critical and I have some other changes in mind.

**Comment by FelixKratz** [comment]
The latest release v2.12.3 now contains these changes, hope it works fine on Monterey.

**Comment by manc1n1** [comment]
Just upgraded, seems to be working. Thanks!
