### ISSUE TITLE
Bug: Popups always on top, even if menubar is not

### ISSUE THREAD

**Issue by chrisgrieser** [FelixKratz/SketchyBar#309]
how the status bar looks right now (second row being popups, [as discussed here](https://github.com/FelixKratz/SketchyBar/discussions/308).)

<img width="320" alt="Pasted image 2023-01-02 23 17 24" src="https://user-images.githubusercontent.com/73286100/210281533-e011510d-7b62-487c-a196-c30ffb4bff0e.png">

this is how it status bar looks when maximizing a window
<img width="498" alt="Pasted image 2023-01-02 23 17 06" src="https://user-images.githubusercontent.com/73286100/210281560-c38bec1f-e27a-4816-ad60-e1bd3909bbe5.png">

**Comment by FelixKratz** [comment]
Thats not a bug, it is the expected behavior. I.e. imagine a popup with some contextual content that is available on click, it should always be on top of all other windows. Thats the same way popups in the macOS bar work.

I could make it configurable though, allowing for popups that are not topmost, but these would not be „popup menu“ anymore but rather some kind of widget.

**Comment by chrisgrieser** [comment]
okay, in case anyone else finds this issue upon search:

I could make due by adding some code to my window manager (in my case hammerspoon) to hide the popups when moving a window to the left or maximizing it. 

```lua
---@param arg string|hs.geometry "show"|"hide"|hs.geometry obj
local function sketchybarPopup(arg)
	local mode
	if type(arg) == "string" then
		mode = (arg == "show") and "true" or "false"
	elseif type(arg) == "table" then
		if arg == maximized or arg == leftHalf then
			mode = "false"
		else
			mode = "true"
		end
	end
	hs.execute(
		"export PATH=/usr/local/lib:/usr/local/bin:/opt/homebrew/bin/:$PATH ; "
			.. "sketchybar --set clock popup.drawing="
			.. mode
	)
end
```

and then I added `sketchybarPopup()` to all my functions that move windows.

**Comment by chrisgrieser** [comment]
fantastic, thank you! will delete my hammerspoon snippets as soon as the next release comes out 🙂
