### ISSUE TITLE
Bug: `popup.topmost=false` is being ignored with the new version

### ISSUE THREAD

**Issue by chrisgrieser** [FelixKratz/SketchyBar#311]
follow-up to #309:

I updated to the newest version, and the new option `popup.topmost=false` does not seem to work for me

![2023-01-08 14 18 19](https://user-images.githubusercontent.com/73286100/211198180-b8b4d58a-cbeb-4546-925a-36f7c745d184.gif)

**Comment by FelixKratz** [comment]
Thats not how the defaults work. Defaults only apply to items you add *after* setting a default value. Try setting it directly for that item. Should work fine.

**Comment by chrisgrieser** [comment]
When appyling it to the respective item, it still does not work:

![2023-01-08 14 29 27](https://user-images.githubusercontent.com/73286100/211198693-1caaf8e0-3d2f-42b5-959f-e1a560ce5ec9.gif)

**Comment by FelixKratz** [comment]
Ah I think I know what to problem is...

**Comment by FelixKratz** [comment]
Updated the release for this. It is a macOS ventura specific bug. v2.13.1 contains the fix

**Comment by chrisgrieser** [comment]
Thank you for the quick fix. Can confirm, it works with the new version now. 😊
