### ISSUE TITLE
"Background Items added" notification on every start since 13.2

### ISSUE THREAD

**Issue by chrisgrieser** [FelixKratz/SketchyBar#322]
(Sorry that I am bothering you yet again 😅 )

While there is apparently [this background items added notification that you cannot really get rid off](https://www.macrumors.com/2023/02/02/macos-background-items-added-notification-bug/), since upgrading to 13.2, sketchybar also started getting such a notification. Annoyingly, this happens every time sketchybar is launched. 

<img width="374" alt="Pasted image 2023-02-03 16 21 00" src="https://user-images.githubusercontent.com/73286100/216640826-a90e468a-3c2c-4f10-bbd2-cec6d67f1dd0.png">

I do fear that this isn't fixable on your end, but I on the off-chance that you can do anything about it, I wanted to report this.

**Comment by FelixKratz** [comment]
I am running macOS 13.2 as well and I dont seem to have this problem. This is how my login item preference pane looks like:
![allowinbackground](https://user-images.githubusercontent.com/22680421/216666878-5f50a037-5b7c-4ee0-9f5b-7b887f658fba.png)

SketchyBar itself does not register the login item. It is purely done by brew and I fear that there is no way for me to fix this.

**Comment by chrisgrieser** [comment]
just for whoever finds this issue later on via search, the problem seems to have been fixed with macOS 13.3
