### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by santilococo** [FelixKratz/SketchyBar#327]
Hello, I want to set an icon on the top right corner of the space icon when the space has apps inside it.

Something like this:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/27114158/218440637-ad51de6d-9164-4cc2-85ad-996395a98b8b.png">

I tried this on your `plugins/yabai.sh` `windows_on_spaces()` function:

```bash
![full_dot](https://user-images.githubusercontent.com/27114158/218441620-eb662f4d-86cb-40be-8d8c-534f0d61f64a.png)

windows_on_spaces () {
  CURRENT_SPACES="$(yabai -m query --displays | jq -r '.[].spaces | @sh')"

  args=()
  while read -r line
  do
    for space in $line
    do
      apps=$(yabai -m query --windows --space $space | jq -r ".[].app")
      if [ "$apps" != "" ]; then
        args+=(--set space.$space background.image="/Users/slococo/Desktop/full_dot.png" background.drawing=on)
      fi
    done
  done <<< "$CURRENT_SPACES"

  sketchybar -m "${args[@]}"
}
```

Where `full_dot.png` is:

![full_dot](https://user-images.githubusercontent.com/27114158/218441716-fb88bd7b-1bb6-4d7c-913f-8a1d1873fa54.png)

But it doesn't seem to work. Do you know if I'm doing something wrong?

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/27114158/218442311-b31c1b9a-30a1-4b06-9e7f-8db3cdb34194.png">

(1, 2 and 10 have apps)

Thanks.

**Comment by santilococo** [comment]
Thanks a lot!

**Comment by santilococo** [comment]
Hello Felix, I currently have this (with two background images):

<img width="387" alt="image" src="https://user-images.githubusercontent.com/27114158/218706036-60011665-dc3c-4c5e-8ed7-d7af110350fb.png">

But maybe it is not very efficient to read the image every time, isn't it?

I want to ask how can I do it with an icon or label as you recommended. I read the docs but didn't see anything that could help me.

Thanks.

**Comment by FelixKratz** [comment]
Here is an example how to do something like this with the icon/label:

When creating the spaces like this:
```bash
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10" "11" "12" "13" "14" "15")

sid=0
spaces=()
for i in "${!SPACE_ICONS[@]}"
do
  sid=$(($i+1))

  space=(
    associated_space=$sid
    icon=${SPACE_ICONS[i]}
    icon.padding_left=10
    label.font="Hack Nerd Font:Regular:8"
    label.y_offset=8
    padding_left=2
    padding_right=2
    icon.highlight_color=$RED
    script='sketchybar --set $NAME icon.highlight=$SELECTED'
  )

  sketchybar --add space space.$sid left    \
             --set space.$sid "${space[@]}" \
             --subscribe space.$sid mouse.clicked
done
```
we set the `label` to have a small font and set a `y_offset` for it. The space script now only changes the highlight of the icon.

Next, in the function where we check wether there are windows on a space or not we can populate the label with an arbitrary font symbol:
```bash
windows_on_spaces () {
  CURRENT_SPACES="$(yabai -m query --displays | jq -r '.[].spaces | @sh')"

  args=()
  while read -r line
  do
    for space in $line
    do
      icon_strip=" "
      apps=$(yabai -m query --windows --space $space | jq -r ".[].app")
      if [ "$apps" != "" ]; then
        args+=(--set space.$space label=⬤)
      else
        args+=(--set space.$space label=◯)
      fi
    done
  done <<< "$CURRENT_SPACES"

  sketchybar -m "${args[@]}"
}
```

The result will look like this, but can be adopted to whatever you wish for (you could swap the role of the icon and label if you want to have the indication on the left of the space for example):
<img width="148" alt="Screenshot 2023-02-14 at 22 26 06" src="https://user-images.githubusercontent.com/22680421/218866747-f9f64421-9971-413b-b723-ad4601f02072.png">

**Comment by santilococo** [comment]
Thanks a lot! That's exactly what I wanted.
