### ISSUE TITLE
Large text is cut off.

### ISSUE THREAD

**Issue by Tnixc** [FelixKratz/SketchyBar#328]
![image](https://user-images.githubusercontent.com/85466117/218621438-af940a5f-acda-49b6-9067-5ad27218198b.png)
Look at the top, the font shouldn't be cut off like that.
Using Left Align filling the whole screen.

**Comment by FelixKratz** [comment]
What exactly is missing? For me it looks like the font is broken? There are missing lines in the E, the D, the A, the U.

**Comment by Tnixc** [comment]
![image](https://user-images.githubusercontent.com/85466117/218679183-6c8e799c-99a6-49bc-be2d-2d783573f5e8.png)
Nope, even with Helvetica it's cut off at the top

**Comment by FelixKratz** [comment]
I can only assume what you are doing:
```bash
sketchybar --bar y_offset=200 margin=200 height=100 color=0x00000000 shadow=off \
 --add item date left \
 --set date label.font="SF Pro:Regular:100" label=Tuesday
```
This works completely fine unless you have a too small bar height. Try setting `--bar color=0xff000000` to see the screen bounds of the bar.

**Comment by Tnixc** [comment]
Ok it works if I change the background height higher, thanks.
