### ISSUE TITLE
Unload OSDUIHelper - HUDs

### ISSUE THREAD

**Issue by santilococo** [FelixKratz/SketchyBar#329]
Hello, when I start sketchybar the com.apple.OSDUIHelper is unloaded/killed and therefore I can no longer see the MacBook volume/brightness animations on the screen (I think they are called HUDs).

Is this intentional? I have SIP disabled.

**Comment by FelixKratz** [comment]
I have killed the process in my personal config here:
https://github.com/FelixKratz/dotfiles/blob/acb27e93221f105a64684b3405309f54585fa9aa/.config/sketchybar/sketchybarrc#L19

SketchyBar itself does not touch this.
