### ISSUE TITLE
No active space highlight

### ISSUE THREAD

**Issue by braun-steven** [FelixKratz/SketchyBar#334]
Hey there,

I was going to move from Übersicht to sketchybar again and started with the [default config](https://github.com/FelixKratz/SketchyBar/blob/master/sketchybarrc) provided on the root of this repo.

<img width="2560" alt="Screenshot 2023-03-03 at 09 01 39" src="https://user-images.githubusercontent.com/17625341/222664827-a4dc3b68-6df9-477d-ae04-42e04255ce12.png">

My issue is that active spaces are not highlighted (see screenshot above). If I read the docs correctly on [that topic](https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item), config does not need any additional changes since:

> By default the space component invokes the following script:
>
> ```sh
> sketchybar --set $NAME icon.highlight=$SELECTED
> ```

Here are my Tabak and sketchybar configs:
- [yabairc](https://github.com/braun-steven/dotfiles/blob/master/configs/yabai/.config/yabai/yabairc)
- [sketchybarrc (default)](https://github.com/braun-steven/dotfiles/blob/master/configs/sketchybar/.config/sketchybar/sketchybarrc)

How can I start debugging why the highlight of the `$SELECTED` space does not work?

Edit: Clicking on the space labels does change the space so the association of space->label/button seems to work.

**Comment by FelixKratz** [comment]
Did you copy the `plugins` directory as well?

**Comment by braun-steven** [comment]
Whoops, that's embarrassing. No, I forgot about that, I just assumed that would be some additional stuff. I copied them and now everything works, thanks! :-)

Maybe it would be good if you could highlight the need for the plugins when the "default" config is mentioned here

https://github.com/FelixKratz/SketchyBar/blob/ce4724ff2236e8166a99ef8e88bca02e397dc599/README.md?plain=1#L53

Somehow, when I skimmed through the README, it sounded like simply copying the default config file would be enough for an initial setup and I totally ignored the need for the plugins. 

Anyway, thanks for your insanely fast response, I'm closing this :)

**Comment by FelixKratz** [comment]
Thats a very good point, I have updated the README.
