### ISSUE TITLE
ER: Support for associating a bar with a particular display

### ISSUE THREAD

**Issue by peterhajas** [FelixKratz/SketchyBar#354]
It would be great to associate a bar with a particular display, rather than having a bar that's either on the main display or all displays. This could be done by display ID, or index. `yabai` supports addressing displays by their "arrangement index", which may be a good model to follow.

(this was part of #353, but was asked to be pulled out into its own issue).

**Comment by FelixKratz** [comment]
I will add the same display selectors as for the `associated_display` option for items.

I.e. a comma separated list of display ids, `active`, `main` and `all` and possibly even combinations.

**Comment by FelixKratz** [comment]
Should be working now, e.g.:
```bash
sketchybar --bar display=2,3,5,7,11,13
```
Please report any bugs you come across with this new implementation.

**Comment by peterhajas** [comment]
This is working great. I can use the display index to target the bar to a different display. Thanks, Felix.
