### ISSUE TITLE
Switch space - bar blinking

### ISSUE THREAD

**Issue by capitanBOBO** [FelixKratz/SketchyBar#359]
First of all, cool project, no jokes
Now to biz. I'm not disable SIP at this moment and when i'm switching spaces bar do this annoying blink

https://user-images.githubusercontent.com/29453809/231702440-d948c0ba-c5e9-49e8-91aa-295ab4e7f30f.mov

Can I do with that something, or only disabling of SIP will help?

**Comment by FelixKratz** [comment]
```bash
sketchybar --bar sticky=on
```

**Comment by capitanBOBO** [comment]
> ```shell
> sketchybar --bar sticky=on
> ```

it's work only for disabled SIP? I did try it, but it didn't help
