### ISSUE TITLE
ERROR:property 'safeAreaInsets' not found on object of type 'NSScreen *'

### ISSUE THREAD

**Issue by ninfranko** [FelixKratz/SketchyBar#360]
i have been trying to install for a few weeks now and every time i install i get this error

copied from terminal=

 make
rm -rf bin
/Library/Developer/CommandLineTools/usr/bin/make x86
mkdir bin
cc -c -o bin/alias.o src/alias.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/background.o src/background.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/bar_item.o src/bar_item.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/custom_events.o src/custom_events.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/event.o src/event.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/graph.o src/graph.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/image.o src/image.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/mouse.o src/mouse.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/shadow.o src/shadow.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/font.o src/font.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/text.o src/text.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/message.o src/message.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/bar.o src/bar.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/window.o src/window.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/bar_manager.o src/bar_manager.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/display.o src/display.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/event_loop.o src/event_loop.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/group.o src/group.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/mach.o src/mach.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/popup.o src/popup.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/animation.o src/animation.c -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
cc -c -o bin/workspace.om src/workspace.m -std=c99 -Wall -Ofast -ffast-math -fvisibility=hidden -fno-common -target x86_64-apple-macos10.13
src/workspace.m:36:29: error: property 'safeAreaInsets' not found on object of type 'NSScreen *'
            height = screen.safeAreaInsets.top;
                            ^
1 error generated.
make[1]: *** [bin/workspace.om] Error 1
make: *** [universal] Error 2

**Comment by FelixKratz** [comment]
Try to update your xcode commandline tools
