### ISSUE TITLE
Partial crash

### ISSUE THREAD

**Issue by andreicorpo** [FelixKratz/SketchyBar#37]
After `Sketchybar` runs for some time, I get this logs ⬇️ :

```sh
sh: cannot make pipe for command substitution: Too many open files
sh: pipe error: Too many open files
syntax error -1757.  Couldn't get error text because of error -1757.
syntax error -1757.  Couldn't get error text because of error -1757.
syntax error -1757.  Couldn't get error text because of error -1757.
syntax error -1757.  Couldn't get error text because of error -1757.
syntax error -1757.  Couldn't get error text because of error -1757.
syntax error -1757.  Couldn't get error text because of error -1757.
syntax error -1757.  Couldn't get error text because of error -1757.
syntax error -1757.  Couldn't get error text because of error -1757.
syntax error -1757.  Couldn't get error text because of error -1757.
syntax error -1757.  Couldn't get error text because of error -1757.
syntax error -1757.  Couldn't get error text because of error -1757.
syntax error -1757.  Couldn't get error text because of error -1757.
sketchybar-msg: failed to send data..
sketchybar-msg: failed to send data..
sketchybar-msg: failed to send data..
sketchybar-msg: failed to send data..
sh: cannot make pipe for command substitution: Too many open files
sh: pipe error: Too many open files
sh: line 5: [: -gt: unary operator expected
sh: line 5: [: -gt: unary operator expected
```

Any idea why this happens?

**Comment by FelixKratz** [comment]
Just a wild guess: Could it be that in one of your scripts you open a " but never close it?
If not, can you try with the default config for a while and see if it happens again?

**Comment by koekeishiya** [comment]
You need to close the file descriptor after the call to `mmap` returns here: https://github.com/FelixKratz/SketchyBar/blob/master/src/misc/helpers.h#L110

**Comment by FelixKratz** [comment]
Thanks for the hint, should be fixed 96a31a1d908a8ea5433644c4c07f8d87a80060f0.

**Comment by FelixKratz** [comment]
I think there might be more to it: When a client connection errors out while writing data it does not close the socket.
See https://github.com/koekeishiya/yabai/blob/8777db43b8551e0bc4e5c55d1e15bcbed52501a1/src/yabai.c#L88.

**Comment by koekeishiya** [comment]
When a process is terminated the OS takes care of releasing resources, so that is not really an issue.

Sent from my iPhone

On 7 Sep 2021, at 18:18, Felix Kratz ***@***.***> wrote:

﻿

I think there might be more to it: When a client connection errors out while writing data it does not close the socket.
See https://github.com/koekeishiya/yabai/blob/8777db43b8551e0bc4e5c55d1e15bcbed52501a1/src/yabai.c#L88.

**Comment by andreicorpo** [comment]
It works fine for now after the update. You can close the issue and thanks. 😄
