### ISSUE TITLE
querying a space doesn't provide popup info?

### ISSUE THREAD

**Issue by dsanson** [FelixKratz/SketchyBar#371]
With ordinary items, I can use `sketchybar --query <item> | jq '.popup.drawing'` to determine whether or not the popup is currently activated. But it appears that spaces don't return any popup information when queried, even though they can have popup windows associated with them.

**Comment by FelixKratz** [comment]
Popup info is only supplied if an item is contained in the popup, this holds for all items not only spaces:
https://github.com/FelixKratz/SketchyBar/blob/7b0f41bddf6dd3c65d3310177b0dcc47c0d4bb59/src/bar_item.c#L891-L895
