### ISSUE TITLE
Shell Files: Permission Denied

### ISSUE THREAD

**Issue by figurativly1984** [FelixKratz/SketchyBar#376]
When I start Sketchybar, some of the icons appear but nothing is filled out:
<img width="1466" alt="Screenshot 2023-05-28 at 10 03 27 AM" src="https://github.com/FelixKratz/SketchyBar/assets/127815982/dab2c9a9-9277-4a14-8e40-72d024031053">
I ran the command Sketchybar and I got this:
<img width="458" alt="Screenshot 2023-05-28 at 10 05 08 AM" src="https://github.com/FelixKratz/SketchyBar/assets/127815982/4e90b1b9-44f1-449e-bf1d-5a5eb5dc2e35">
I've enabled screen recording for Sketchybar are there any other permissions I have to grant?

**Comment by cagdassalur** [comment]
Can you try making the scripts executable?
`chmod +x ~/.config/sketchybar/plugins*/*`

**Comment by figurativly1984** [comment]
Yep that did it! Thanks for the help
