### ISSUE TITLE
Alias redraw issue

### ISSUE THREAD

**Issue by capitanBOBO** [FelixKratz/SketchyBar#377]
I have outline vpn item as alias and after i'm closing outline, alias item stayed at bar. Maybe I should add something?[](url)

https://github.com/FelixKratz/SketchyBar/assets/29453809/9d9fba73-8415-4a9c-863b-33e5f4aae8cb

**Comment by FelixKratz** [comment]
Aliases are not designed to work properly with applications that are not constantly running. If the app is not running when sketchybar is launched, sketchybar will search for it continuously (which is resource intensive). After the app is found it will not check if the app has been quit before updating the alias, but silently fail to update the content, which results in the alias not updating at all.

**Comment by cagdassalur** [comment]
@capitanBOBO You might be interested in this if only you care about seeing the vpn connection status: 
https://github.com/FelixKratz/SketchyBar/discussions/12#discussioncomment-1216869

You can also set up something to hide/show the icon based on the application running and show a different icon when it's actually connected to vpn

**Comment by FelixKratz** [comment]
It should be fixed on master: 4058ffe
