### ISSUE TITLE
Sketchybar shows nothing

### ISSUE THREAD

**Issue by daothanhminh** [FelixKratz/SketchyBar#379]
<img width="1470" alt="Screenshot 2023-06-23 at 6 01 12 AM" src="https://github.com/FelixKratz/SketchyBar/assets/119743748/ae163c0f-1614-4b39-b2cc-d1bc57109f1a">
I'm using macOS Ventura. I have installed Sketchybar and its packages on the documentation site but it shows nothing, just a blank top bar. Is there a solution to this issue?

**Comment by FelixKratz** [comment]
Try running the bar from the commandline, you will see the full error log. The reason is probably that the configuration is missing or not executable (`~/.config/sketchybar/`). Make sure to copy it with the commands listed in the caveats section after the brew install.

**Comment by daothanhminh** [comment]
> Try running the bar from the commandline, you will see the full error log. The reason is probably that the configuration is missing or not executable (`~/.config/sketchybar/`). Make sure to copy it with the commands listed in the caveats section after the brew install.
Ah, yes, appreciate it. I thought it was configured before because y'know... my first time using it.
