### ISSUE TITLE
Getting sketchybar to display only on extended display

### ISSUE THREAD

**Issue by priyanshuppal** [FelixKratz/SketchyBar#382]
Hey Everyone, i am currently using my macbook as a secondary display with my monitor. i only want sketchy bar to display on my mac and not on my monitor. is there any way to specify which monitor to display on.

**Comment by FelixKratz** [comment]
Have a look at the `display` options in the `--bar` domain: https://felixkratz.github.io/SketchyBar/config/bar

You can specify a list of display numbers, the main display or all displays.
Maybe I could add the option `builtin` for the internal display, but it would only be a shorthand for specifying the internal displays display id.
