### ISSUE TITLE
Extra gap in between menu bar and window after uninstalling.

### ISSUE THREAD

**Issue by maxdalat** [FelixKratz/SketchyBar#384]
Hello,

I am currently using a config with yabai and skhd, but I decided to uninstall sketchybar as I preferred the original menu bar (nothing against sketchybar just personal preference), but when I uninstalled sketchybar there is now a gap between the menu bar and my windows that was not there before I uninstalled sketchybar. 
<img width="1470" alt="Screenshot 2023-07-17 at 2 34 26 PM" src="https://github.com/FelixKratz/SketchyBar/assets/63883235/46ce00ad-337a-48e8-88ad-49c0aece4ea6">

**Comment by FelixKratz** [comment]
Check your yabai config, sketchybar does not do anything that is persistent.
