### ISSUE TITLE
Question About sketchybar with dynamic island plugin MacOS

### ISSUE THREAD

**Issue by plyght** [FelixKratz/SketchyBar#388]
hello,

I was wondering (and yes i know this is not the [dynamic-island-sketchybar](https://github.com/crissNb/Dynamic-Island-Sketchybar)  github) why it isn’t showing up in full screen apps, such as Arc, Warp, etc. i am not proficient in unix  at ALL so i don’t know if sketchybar can even do that. 

I also don’t know how to hide that weird shadow, as i’m not fully using sketchybar (because, like i said, i had only heard of unix 2 times before downloading sketchybar), i’m just using dynamic-island-sketchybar and the normal menu bar.

one last thing: if anyone knows of a nice UI for people like me to customize sketchybar, that would be greatly appreciated if you gave me the link to that)

(MacOS Ventura 13.5; 2017 Macbook Pro 4 Thunderbolt 3 ports)

let me know if you need a video/screenshot of the issue!

Thanks, plyght

**Comment by FelixKratz** [comment]
When you say fullscreen, do you mean the fullscreen mode you get by clicking the green button on the application handle? 

In principle it is possible the draw over native-fullscreen apps, but for various reasons I dont want to do that (see #383 ).

Could you provide further detail what you mean by „strange shadow“? All shadows sketchybar throws can be turned off in principle, so we would need to find out which one it is that you want to turn off. A screenshot might already help.

**Comment by plyght** [comment]
here is a screenshot of the dynamic island and the "shadow" i was talking about. 

[Screenshot](https://ibb.co/JdT6dZY)

also, for fullscreen, i meant when you press the green button on the "traffic lights" to fulscreen the application (i believe it is the same thing as F11, but i'm not sure) Second screenshot of "Traffic Lights": {Screenshot 2](https://ibb.co/5YL3kHm)

**Comment by FelixKratz** [comment]
You can simply add
```bash
sketchybar --bar color=0x00000000
```
then the bar will not be visible anymore (the "shadow" you see is the default look of the bar when not configuring it at all).

Then the fullscreen behavior is on purpose like stated here #383 .

**Comment by plyght** [comment]
Thanks for letting me know how to fix the shadow!

is there any way to override #383 ?

**Comment by FelixKratz** [comment]
Sure, if you are willing to modify the source code you can override this. You would want to make sketchybar windows sticky without removing the super sticky tag bit, i.e.:
```c
set_tags |= kCGSStickyTagBit
clear_tags = 0
```
which makes them appear on fullscreen spaces. There is an additional logic that determines wether a bar is currently shown and it is updated by checking the current space type:
https://github.com/FelixKratz/SketchyBar/blob/e05fca28cfd0318317d6b0de4dd0b2eef11e7fc3/src/bar_manager.c#L905

This would probably need to be changed as well.
