### ISSUE TITLE
SketchyBar overlapped by app windows on external monitor

### ISSUE THREAD

**Issue by chuanhhoang** [FelixKratz/SketchyBar#390]
I am using Macbook Air M2 but sketchbar is overlapped by app window on external monitors like this:

<img width="642" alt="Screenshot 2023-08-24 at 18 23 06" src="https://github.com/FelixKratz/SketchyBar/assets/19351207/a2af4116-0940-4cfe-be6d-d2f223bede88">

**Comment by FelixKratz** [comment]
If you are using yabai you can simply set an "external_bar" property to keep this space free from windows like this
```bash
yabai -m config external_bar all:35:0
```

Most other window managers seem to have a way to adjust the top padding to accommodate an external bar. Alternatively you could set sketchybar to draw on top of all windows by setting:
```bash
sketchybar --bar topmost=window
```
but this would of course hide parts of your window below the bar.
