### ISSUE TITLE
Different bar position for each display

### ISSUE THREAD

**Issue by Asilvorcarp** [FelixKratz/SketchyBar#394]
I want to set the bar position to “bottom” for display 1, and to “top” for display 2. 
Can I achieve that now? 
If not, which part of the code needs to be changed?

**Comment by FelixKratz** [comment]
This is something you can achieve with the "multiple bars" feature. You would have a top and a bottom bar and for those you can set their respective display: https://felixkratz.github.io/SketchyBar/config/tricks#multiple-bars
