### ISSUE TITLE
Make font both bold and italic

### ISSUE THREAD

**Issue by math-1** [FelixKratz/SketchyBar#396]
I want to make the font I'm using both bold and italic, but I'm not sure how to do this using `label.font`.

For instance, something like `label.font="<font>:Bold,Italic:<size>"` does not work.

Is there a way to do this?

**Comment by FelixKratz** [comment]
If there exists a `Bold Italic` font variant you can simply set it like this: `label.font="<font>:Bold Italic:<size>"`
This works for all font variants listed in the `Font Book` app.
