### ISSUE TITLE
Blinking sometimes

### ISSUE THREAD

**Issue by capitanBOBO** [FelixKratz/SketchyBar#401]
Hi! After last updates (macos, sketchybar, yabai, skhd, everything) bar blinking sometime, after change active window, change active display, opening app.

Maybe I can find logs for sketchybar, maybe it's not sketchybar problem at all? 

mac m2, ventura 13.5.2, sketchybar 2.16.3

**Comment by capitanBOBO** [comment]
It's not just blinking. It's reload. Sometimes it's take couple seconds

**Comment by FelixKratz** [comment]
That sound like a hotload event or a crash. Are you using the hotload feature of sketchybar? Are you possibly changing a file inside of the sketchybar folder? This would trigger a hotload event and reload the bar.

Try `sketchybar --hotload off`

If it is a crash, could you share the crash log from Console.app ?

**Comment by capitanBOBO** [comment]
> That sound like a hotload event or a crash. Are you using the hotload feature of sketchybar? Are you possibly changing a file inside of the sketchybar folder? This would trigger a hotload event and reload the bar.
> 
> Try `sketchybar --hotload off`
> 
> If it is a crash, could you share the crash log from Console.app ?

I'd like to share log files, but I can't understand how to get them, sorry) Where sketchybar put them?

**Comment by FelixKratz** [comment]
You can simply start sketchybar directly from the commandline, then you will see all outputs and you will see if it crashes:
```bash
brew services stop sketchybar
sketchybar
```

In case it crashes you can recover the crash logs from the `Console` app located in Applications -> Utilities -> Console.app. There you go to the tab „Crash Reports“

**Comment by capitanBOBO** [comment]
> You can simply start sketchybar directly from the commandline, then you will see all outputs and you will see if it crashes:
> 
> ```shell
> brew services stop sketchybar
> sketchybar
> ```
> 
> In case it crashes you can recover the crash logs from the `Console` app located in Applications -> Utilities -> Console.app. There you go to the tab „Crash Reports“

Thanks! Was something with image load for window_title plugin. I'm cleared it and now it's working
