### ISSUE TITLE
Spamming spaces highlight with animation messes up colors

### ISSUE THREAD

**Issue by erics118** [FelixKratz/SketchyBar#404]
basically, have a config where space highlight changes with an animation, then spam switching spaces (eg with hotkeys set with skhd)

video:

the white box is a window that i put on each space, so it is guaranteed to show the correct space.

https://github.com/FelixKratz/SketchyBar/assets/52634785/6563548a-3eec-48ce-b3d8-b0ec188c1545

<details>
<summary>same video, 1/4 the speed</summary>

https://github.com/FelixKratz/SketchyBar/assets/52634785/d173a343-bade-41d0-9917-4c7f011c8743

</details>

<details>
<summary>sample config (the one used for the video)</summary>

`~/.config/sketchybar/demo/sketchybarrc`:
```bash
#!/bin/bash

bar=(
    height=30
    color=0xff000000
    position=top
    sticky=on
    topmost=on
)
sketchybar --bar "${bar[@]}"

# spaces
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")

sid=0
spaces=()
for i in "${!SPACE_ICONS[@]}"; do
    sid=$(($i + 1))

    space=(
        associated_space=$sid
        icon="${SPACE_ICONS[i]}"
        icon.highlight_color=0xffff0000
        script="~/.config/sketchybar/demo/space.sh"
    )

    sketchybar --add space space.$sid left \
        --set space.$sid "${space[@]}"
done
# end spaces

sketchybar --update

echo "sketchybar configuration loaded.."
```

`~/.config/sketchybar/demo/space.sh`:
```bash
#!/bin/bash

sketchybar \
    --animate sin 10 \
    --set $NAME icon.highlight=$SELECTED
```
</details>

**Comment by SuperBo** [comment]
I also had this issue, have to restart sketchy bar every day to fix it.

**Comment by FelixKratz** [comment]
Should be fixed on master, you can test by running:
```bash
brew services stop sketchybar
brew uninstall sketchybar
brew install sketchybar --head
brew services start sketchybar
```
and then go back to the stable release with
```bash
brew services stop sketchybar
brew uninstall sketchybar
brew install sketchybar
brew services start sketchybar
```

**Comment by SuperBo** [comment]
Thank you for quick fix @FelixKratz
