### ISSUE TITLE
[Documentation] Menu Bar setting location has changed in Sonoma

### ISSUE THREAD

**Issue by bustinbung** [FelixKratz/SketchyBar#411]
The setting to change the menu bar has moved under Control Center in Sonoma, docs say it's under Display.
<img width="827" alt="image" src="https://github.com/FelixKratz/SketchyBar/assets/22670587/cee50a4b-b8e7-42e3-b2c4-30af1aa2f538">

**Comment by FelixKratz** [comment]
I have updated the docs, thanks for the report!
