### ISSUE TITLE
Multiple Bars in 3 Displays (2 bars .config)

### ISSUE THREAD

**Issue by rgsaura** [FelixKratz/SketchyBar#412]
Hi! I'm trying to create a tridisplay set up with:
- 1º bar in the main display
- 2º bar duplicated in left and right display

I tried the multiple bars set up but only achived 1º bar in main screen and 2º bar in left screen.

Problem: I want to use the 2º bar in left and right display, only showing in left
<img width="297" alt="Screenshot 2023-10-10 at 00 03 59" src="https://github.com/FelixKratz/SketchyBar/assets/16281075/4c455bee-d7c0-487e-a59f-77333f7ac68b">

**Comment by FelixKratz** [comment]
You have set the `display` field to only show on display 2, you would need to specify both displays you want the bar to show on, e.g. `display=2,3`

**Comment by rgsaura** [comment]
You are right! Okey, sorry I tried putting two Display variables (display=2, display=3 below), and of course it didnt work, I tried that way (display=2,3) but the color change with the ",3" drove me off.

Lastly, Could you tell me how to launch a second brew service or how to aproach the automatic launch of the second bar?

Thank you so much! 😄

**Comment by FelixKratz** [comment]
> Lastly, **Could you tell me how to launch a second brew service or how to aproach the automatic launch of the second bar?**

You don't need a second brew service to launch the second bar, you can simply launch it from the `sketchybarrc` of the main bar as a daugther process, i.e. at the very bottom of your main `sketchybarrc` add the command to launch your second bar e.g.
```bash
bottom_bar
```
this will take care of starting and stopping the secondary bar with the default service. If you want to start more than one additional bar you could either daisy chain the startup or launch the process in the background.
