### ISSUE TITLE
`default_menu_items` returning nothing

### ISSUE THREAD

**Issue by ituri** [FelixKratz/SketchyBar#415]
When I run sketchybar with the `default_menu_items` parameter, I get an empty output:
```
    ~  sketchybar --query default_menu_items                                                                                                                                               ✔  09:19:33 


    ~                                                                                                                                                                                      ✔  09:19:49 
```
I've looked at other issues on GitHub with the same problem and made sure that both sketchybar and my Terminal (wezterm) are allowed to record the screen:
![CleanShot 2023-10-12 at 09 21 43](https://github.com/FelixKratz/SketchyBar/assets/871297/9032d2bc-d912-4ddf-9f4e-37be1a204aa2)
Is there anything else I might be missing?

**Comment by FelixKratz** [comment]
Make sure the bar is running when issuing the query command, else it will return nothing. Feel free to reopen if this was not the problem.

**Comment by ituri** [comment]
Worked, thank you!
