### ISSUE TITLE
Remove sketchybar automation

### ISSUE THREAD

**Issue by gldtn** [FelixKratz/SketchyBar#419]
How to remove sketchybar from Privacy & Security > Automation

I have 5 entries inside there even after uninstalling sketchybar

![sketchybar](https://github.com/FelixKratz/SketchyBar/assets/981383/6629f801-b216-4dff-b8a7-815a6d55f561)

**Comment by FelixKratz** [comment]
https://apple.stackexchange.com/questions/339363/how-can-i-remove-applications-from-security-privacy

**Comment by gldtn** [comment]
I ran into that while searching but I can't find the id of sketchybar, do you happen to know what it is?

When I run:
```
osascript -e 'id of app "skechybar"'
```

It does not find it, probably because it's not installed, can you tell me the output of the command above?

Thanks!

**Comment by gldtn** [comment]
I ran into that while searching but I can't find the id of sketchybar, do you happen to know what it is?

When I run:

osascript -e 'id of app "sketchybar"'

It does not find it, probably because it's not installed, can you tell me the output of the command above?

Thanks!
