### ISSUE TITLE
Crash when loading app icon

### ISSUE THREAD

**Issue by FelixKratz** [FelixKratz/SketchyBar#423]
### Discussed in https://github.com/FelixKratz/SketchyBar/discussions/420

<div type='discussions-op-text'>

<sup>Originally posted by **OrneryCash** October 13, 2023</sup>

https://github.com/FelixKratz/SketchyBar/assets/60810240/5ffb219b-e7f4-40b8-aef5-cde3e1b0dcf3

I have no idea what happened.</div>

**Comment by FelixKratz** [comment]
I think it should be fixed, can you try it:
```bash
brew uninstall sketchybar
brew install sketchybar --head
brew services restart sketchybar
```
and then go back to stable release via:
```bash
brew uninstall sketchybar
brew install sketchybar
brew services restart sketchybar
```

**Comment by OrneryCash** [comment]
It doesn't crash now. Thank you for your work!
