### ISSUE TITLE
Dynamic padding for yabai for different screens

### ISSUE THREAD

**Issue by BishBish123** [FelixKratz/SketchyBar#432]
Hello there, big fan of sketchy bar and fyabai. I just started using it for a few days now, but I hit an issue where yabai tiles over the sketchybar when switching from macbook screen to monitor (the notch on the 14-inch macbook pro is set up differently from a normal monitor). When I increased top padding to work for monitor, it did work but now there is a gap on the macbook screen. here are screenshots of what I mean:

top padding 6 (default):
mac:
<img width="1510" alt="image" src="https://github.com/FelixKratz/SketchyBar/assets/61472235/15800747-8fe9-4a49-a63b-c47ad0c21314">

monitor
![image](https://github.com/FelixKratz/SketchyBar/assets/61472235/3125b7c3-281d-4aae-ad50-1b31e7b62bbf)

top padding 45:

mac:
<img width="1506" alt="image" src="https://github.com/FelixKratz/SketchyBar/assets/61472235/c9917019-b586-4cc0-b4b6-f1d61b871fbf">

monitor:
![image](https://github.com/FelixKratz/SketchyBar/assets/61472235/e4945ae0-099e-41c6-8f15-6a45cca96dd2)

Is there a way to get yabai to dynamically pad depending on screen or is there a way for sketchybar to include itself as a window to be tiled in yabai? Thank you.

**Comment by FelixKratz** [comment]
This is exactly what
```bash
yabai -m config external_bar all:35:0
```
does. It creates room for SketchyBar at the top, which is the same on all displays.
