### ISSUE TITLE
availability of commands (`brew services start sketchybar` vs `sketchybar`)

### ISSUE THREAD

**Issue by rwijtvliet** [FelixKratz/SketchyBar#433]
I'm using an external script in my sketchybar config, which is on my path (in `/usr/local/bin/`), and I've noticed it is working fine when starting the app with `sketchybar`, but it's failing when using `brew services start sketchybar`. I can probably work around it, but was wondering if this is a known issue with a known solution. 

As an aside, I noticed that `yabai` and `skhd` recently changed from using `brew services start yabai` to `yabai --start-service`. But this could be for unrelated reasons.

**Comment by FelixKratz** [comment]
Try placing it in `/usr/local/bin` instead of `/user/local/bin` then it should work.

**Comment by rwijtvliet** [comment]
Thanks for the fast reply. I made a typo; the script is actually in `/usr/local/bin`.

**Comment by FelixKratz** [comment]
I edited the response too, I could imagine adding /usr/local/bin to the default search paths, I don't see any problems with that.

**Comment by rwijtvliet** [comment]
Ah, ok - I'll try that and give you a feedback!

**Comment by rwijtvliet** [comment]
> I edited the response too, I could imagine adding /usr/local/bin to the default search paths, I don't see any problems with that.

I think that would be a good idea. The others (`/bin/`, `/sbin/`, `/usr/bin/`, `/usr/sbin/`) are all read-only file systems, and it's probably not ideal to manually add binaries to the homebrew prefix.

**Comment by koekeishiya** [comment]
Having the service file installed by running `yabai --start-service` allows me to set the service path equal to the value of $PATH of the user that runs the command. Not sure if you can access that during brew installation.

**Comment by FelixKratz** [comment]
On second thought, I think I will leave it as is for now. You can always use the absolute path for any binaries that reside outside of the service search path and I think this makes the configs created for sketchybar a bit better reproducible.
