### ISSUE TITLE
SketchyBar doesn't start?

### ISSUE THREAD

**Issue by maelp** [FelixKratz/SketchyBar#444]
I'm on a normal osX install (latest version), did the brew install, copied the rc file and the plugins in ~/.config/sketchybar, and when I start the CLI `sketchybar` it hangs, but no UI is displayed, am I doing something wrong?

**Comment by FelixKratz** [comment]
Is it possibly below the macOS menu bar? You can check by calling something like
```bash
sketchybar --bar y_offset=50
```
while the bar is running.

**Comment by maelp** [comment]
indeed 😅

and is there a way to have a "z-index" so it is on top, or should I hide the original bar?

**Comment by maelp** [comment]
<img width="715" alt="image" src="https://github.com/FelixKratz/SketchyBar/assets/15458/e5c0a7ba-e672-4d10-8b9b-9dadd67011da">

I see this when removing the windows?

**Comment by erics118** [comment]
There is a `topmost` config property for the bar to do that

**Comment by maelp** [comment]
Thanks! although for some reason my SketchyBar seems to be shown "on the desktop" and not on a bar for some reason, not sure what I did

I cannot click on the items in the bar

**Comment by schronck** [comment]
I am facing a similar problem.

I used brew to install sketchybar, then followed the instructions in the caveats section.
After running sketchybar / starting the service nothing happens, it just hangs.
(I have the macOS menu bar hidden so this can't be the problem)
