### ISSUE TITLE
$INFO output with hidden bar

### ISSUE THREAD

**Issue by PhrantiK** [FelixKratz/SketchyBar#446]
Trying to figure out the best way to hide a bar for a specific space. Noticed we can do it by display (#42) and also saw another issue with a bunch of yabai signals (https://github.com/FelixKratz/SketchyBar/issues/175#issuecomment-1084409282). 

Is it possible to do it with an item & space_change event to keep things a bit faster & leaner? 

ITEM:
````
sketchybar --add item hide2 right \
            --set hide2 script="$PLUGIN_DIR/hide2.sh" \
            --subscribe hide2 space_change
````

PLUGIN:
````
hide() {
  # sketchybar --bar hidden=on
  echo "turn it off"
}

unhide() {
  # sketchybar --bar hidden=off
  echo "turn it on"
}

case $(echo "$INFO" | jq '.[]') in
  "2") hide
  ;;
  *) unhide
  ;;
esac
````

It works great but when the bar is hidden, $INFO stops outputting so the bar stays hidden. Not sure if that's by design, a bug or feature request. Thanks!

**Comment by FelixKratz** [comment]
This will work perfectly if you set `sketchybar --set hide2 updates=on` because I presume it is currently set to `when_shown`, hence it will not call its script when the item is not drawn to screen.

**Comment by PhrantiK** [comment]
PEBKAC - Thanks Felix!
