### ISSUE TITLE
[Discussion/improvement] Event when display count changes 

### ISSUE THREAD

**Issue by rwijtvliet** [FelixKratz/SketchyBar#448]
When connecting my machine to an external display, the spaces are distributed to occupy both spaces. In the process, the first space on the secondary display loses its yabai label (a macos issue, apparently), causing it to be displayed incorrectly on my sketchy bar. 

An workaround would be, if I could subscribe my sketchybar items to an event which is triggered when a display is connected or disconnected.

**Comment by FelixKratz** [comment]
I will close this as not planned currently because I will probably not work on this event myself. Feel free to post a PR though.
