### ISSUE TITLE
Sketchybar Permission Denied

### ISSUE THREAD

**Issue by jstn-swm** [FelixKratz/SketchyBar#449]
Hi Im just having trouble with running/permission to the plugins. Have not found this particular issue solved before. Is there a problem with how I setup sketchybar?

justin@Justins-MacBook-Pro Documents % sketchybar
[2023-11-22 13:20:35] [!] Item (defaults): Invalid property 'cache_scripts'
[!] Item (defaults): Invalid property 'cache_scripts'
[2023-11-22 13:20:35] [?] Event: 'window_focus' not found
[2023-11-22 13:20:35] [?] Event: 'title_change' not found
[?] Event: 'window_focus' not found
[?] Event: 'title_change' not found
sh: /Users/justin/.config/sketchybar/plugins/window_title.sh: Permission denied
sketchybar configuration loaded..
sh: /Users/justin/.config/sketchybar/plugins/date_time.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/mic.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/window_title.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/cpu.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/cpu.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/mic.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/cpu.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/mic.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/cpu.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/cpu.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/mic.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/cpu.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/cpu.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/mic.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/cpu.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/mic.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/cpu.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/cpu.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/mic.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/date_time.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/cpu.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/mic.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/cpu.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/cpu.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/mic.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/cpu.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/mic.sh: Permission denied
sh: /Users/justin/.config/sketchybar/plugins/cpu.sh: Permission denied
^C

**Comment by FelixKratz** [comment]
Try `chmod +x /Users/justin/.config/sketchybar/plugins/*`
