### ISSUE TITLE
Bar showing after sleep when program is fullscreen

### ISSUE THREAD

**Issue by andynameistaken** [FelixKratz/SketchyBar#451]
![image](https://github.com/FelixKratz/SketchyBar/assets/15692002/1fdf2067-8324-4b64-8e1d-606d266d12e5)

`sketchybar` version: 2.19.4

## Steps to reproduce:
1. put computer on sleep 
2. login through lockscreen
3. bar is shown on fulscreen program

**Comment by andynameistaken** [comment]
macOS: 13.6.0.1

Command doesn't show the bar:
<img width="1680" alt="Screenshot 2023-12-05 at 02 15 43" src="https://github.com/FelixKratz/SketchyBar/assets/15692002/69818a25-2814-4d03-af0f-e365cab23526">

**Comment by FelixKratz** [comment]
The original problem should go away when you set `sticky=on`. On Sonoma the sticky property is always enabled an can not be deactivated, such that this bug will only appear on older macOS versions.
