### ISSUE TITLE
Bar not showing

### ISSUE THREAD

**Issue by filipmilo** [FelixKratz/SketchyBar#457]
Im currently using the macbook pro M2 on ventura 13.6 and having an issue where the bar doesn't show up even though i setup everything following the setup and the default configs. When i run it directly in the terminal it doesn't throw any errors but its now showing.

**Comment by FelixKratz** [comment]
So it is showing when you run the bar from the commandline and not showing when run as a brew service?

**Comment by filipmilo** [comment]
Its not showing at all

**Comment by FelixKratz** [comment]
Could you provide the output of the following command:
```bash
ls -la $HOME/.config/sketchybar
```

**Comment by filipmilo** [comment]
`total 16
drwxr-xr-x@  4 filipmilosevic  staff   128 Dec 12 13:35 .
drwxr-xr-x@ 14 filipmilosevic  staff   448 Dec 11 12:17 ..
drwxr-xr-x@  7 filipmilosevic  staff   224 Dec 12 13:37 plugins
-rwxr--r--@  1 filipmilosevic  staff  5305 Dec 12 13:34 sketchybarrc`

**Comment by FelixKratz** [comment]
Ok, now:
```bash
sketchybar --query bar
```
when the bar is running but not showing.

**Comment by filipmilo** [comment]
```
{
	"position": "top",
	"topmost": "off",
	"sticky": "off",
	"shadow": "off",
	"font_smoothing": "off",
	"blur_radius": 30,
	"margin": 0,
	"drawing": "on",
	"color": "0x15ffffff",
	"border_color": "0xffff0000",
	"border_width": 0,
	"height": 32,
	"corner_radius": 0,
	"padding_left": 10,
	"padding_right": 10,
	"y_offset": 0,
	"clip": 0.000000,
	"image": {
		"value": "(null)",
		"drawing": "off",
		"scale": 1.000000
	},
	"items": [
		 "space.1",
		 "space.2",
		 "space.3",
		 "space.4",
		 "space.5",
		 "space.6",
		 "space.7",
		 "space.8",
		 "space.9",
		 "space.10",
		 "space_separator",
		 "front_app",
		 "clock",
		 "volume",
		 "battery"
	]
}
```

**Comment by filipmilo** [comment]
Ok for some reason it started showing up right away when i queried... Now its hiding whenever a window is open

**Comment by filipmilo** [comment]
Thank you and sorry for bothering...

**Comment by FelixKratz** [comment]
I still think there is an issue here. It should not only show after the query command.

**Comment by filipmilo** [comment]
Okay i thought i did something wrong, im here to provide any help

**Comment by FelixKratz** [comment]
Could you try the following:
```bash
brew services stop sketchybar
killall sketchybar
brew uninstall sketchybar
brew install sketchybar  --head
sketchybar
```

**Comment by filipmilo** [comment]
Did the commands, its now showing but there is still the issue with it being hidden when a window is open.

Im using yabai as the wm.

**Comment by FelixKratz** [comment]
Is the bar covered by another window or is it not rendering at all?

**Comment by filipmilo** [comment]
Its not rendering at all

**Comment by filipmilo** [comment]
[zip.zip](https://github.com/FelixKratz/SketchyBar/files/13648804/zip.zip)
Here is the zip of the config folder you mentioned above

**Comment by FelixKratz** [comment]
When you run sketchybar from the commandline, does it keep running or does it crash when a window is open and it stops showing?

**Comment by filipmilo** [comment]
Actually its being rendered sorry

**Comment by FelixKratz** [comment]
Ok, then try:
```bash
sketchybar --bar topmost=on
```

**Comment by filipmilo** [comment]
![image](https://github.com/FelixKratz/SketchyBar/assets/56317457/2ca64a3a-05d5-4906-ad0d-59cdc52ae466)
Its now like this, covering the other windows

**Comment by FelixKratz** [comment]
To keep yabai from putting windows where sketchybar is use:
```bash
yabai -m config external_bar all:40:0
```

**Comment by filipmilo** [comment]
Now it works, thank you so much and sorry for the hassle... im still a bit new to this

**Comment by FelixKratz** [comment]
Now try:
```bash
brew services stop sketchybar
killall sketchybar
brew uninstall sketchybar
brew install sketchybar
brew services start sketchybar
yabai -m config external_bar all:40:0
sketchybar --bar topmost=on
```
does this still work as expected?

**Comment by FelixKratz** [comment]
Great! Have a nice day.
