### ISSUE TITLE
[Bug?]volume_change event is not triggered in some cases.

### ISSUE THREAD

**Issue by WantToLearnJapanese** [FelixKratz/SketchyBar#458]
When another output source is connected to the system than the built-in speaker, the volume_change event is not triggered.

**Comment by WantToLearnJapanese** [comment]
I confirmed that it only happens when the setting is as the following screenshot.
If I choose the "Selected Sound Output Source" option, the "volume_change" event is triggered correctly.
<img width="715" alt="image" src="https://github.com/FelixKratz/SketchyBar/assets/88884927/33356d09-25d5-48d3-b1d7-e61152fae5ff">

**Comment by FelixKratz** [comment]
I think the event is not fired when the volume of both devices is the same, I have changed the behavior such that the event is always fired when a new device is connected.
