### ISSUE TITLE
whether the labels for the space component are automatically assigned

### ISSUE THREAD

**Issue by marsjane** [FelixKratz/SketchyBar#471]
hi, I am looking into some shared dotfiles, this one (thanks the author!) https://github.com/FelixKratz/dotfiles/blob/e6288b3f4220ca1ac64a68e60fced2d4c3e3e20b/.config/sketchybar/items/spaces.sh

I couldn't locate where the label for the space component (representing all app titles in that space) is defined. I am somewhat confused as I reviewed the documentation, which categorizes "space" as a "Special Component." However, the documentation does not specify whether the labels for the space component are automatically assigned. Could you please clarify how the label for the space component is configured?

Second question is about the "yabai" component, what is it used for? It seems not shown on my side, can you also help explain?

Thanks!

**Comment by FelixKratz** [comment]
No label or icon is automatically assigned, it is all through scripts,e.g. here: https://github.com/FelixKratz/dotfiles/blob/master/.config/sketchybar/plugins/space_windows.sh

**Comment by marsjane** [comment]
thanks！
