### ISSUE TITLE
How to disable a specific app as to no appear as an icon (w/ sketchybar-app-font) in sketchybar? [Loom issue]

### ISSUE THREAD

**Issue by wramalho** [FelixKratz/SketchyBar#473]
I use Sketchybar with one of FelixKratz's template dotfiles as an initial template, using sketchybar-app-font to draw icons to the bar. Is there a way to exclude certain apps from appearing in the bar? My use case is the Loom App. While active, it appears in all spaces (see screenshots below; first one, the app is open in menubar but not in use; second one its tooltip is open/active). It is a video capture software. By 'active', I do mean only at activate usage. If that is not possible, is there any way for Loom to only be detected in the current space?

I am available to provide any additional info. Thanks in advance. 

Best,
<img width="1920" alt="Screenshot 2024-01-06 at 22 26 42" src="https://github.com/FelixKratz/SketchyBar/assets/7698714/66affa85-e957-4348-bcc6-e400bb927e3a">
<img width="1920" alt="Screenshot 2024-01-06 at 22 26 57" src="https://github.com/FelixKratz/SketchyBar/assets/7698714/bd3829e3-70a9-4b36-a350-ab4aef1c1330">

**Comment by FelixKratz** [comment]
In the script where the icons are are gathered for the applications, you could exempt certain applications from receiving an icon, i.e. here:
https://github.com/FelixKratz/dotfiles/blob/master/.config/sketchybar/plugins/space_windows.sh
