### ISSUE TITLE
Sketchybar unhides after locking

### ISSUE THREAD

**Issue by dmlazaro** [FelixKratz/SketchyBar#477]
## Info

I use a script (which is run by an `skhd` hotkey) to hide Sketchybar using the following command:

```bash
sketchybar --bar hidden=false
```

In my `sketchybarrc`, I have the following config:

```plaintext
sketchybar --bar height=20        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=10  \
                 padding_right=10 \
                 color=0x05000000 \
                 topmost=off
```

## Problem

The command to hide works, but if the bar is hidden when I lock my device, it unhides when I log back in. Also, `sketchybar --query bar` does not contain the hidden state.

## Expected Outcome

The `hidden` state of the bar should be preserved when I log back in.

Any idea what might be going on? I've reinstalled and the issue persists.

**Comment by FelixKratz** [comment]
Indeed, the bar is reset on login and display change, hence why this property does not persists on wake or display configuration change.

This issue will be adressed during the implementation of #472
