### ISSUE TITLE
Animation scroll_texts speed

### ISSUE THREAD

**Issue by mr-scrpt** [FelixKratz/SketchyBar#478]
It seems that the animation speed is related to max_chars. If you set a large value for max_chars, the animation becomes very fast. Is there any way to adjust the animation speed separately from max_chars?

**Comment by FelixKratz** [comment]
Example usage of the new property:
```bash
sketchybar --set <name> label.scroll_duration=<positive_integer>
```
it is configurable on a per-text basis.

**Comment by mr-scrpt** [comment]
> Example usage of the new property:
> 
> ```shell
> sketchybar --set <name> label.scroll_duration=<positive_integer>
> ```
> 
> it is configurable on a per-text basis.

Thanks for your reply but I'm not getting any effect, tried putting 0.1, 1, 10, 1000 looks the same fast. I have updated the package to the latest version sketchybar-v2.20.1 
```
sketchybar --add item media e \
           --set media label.color=$COLOR_PEACH_LIGHT \
                       label.max_chars=50 \
                       scroll_texts=on \
                       label.scroll_duration=0.1 \
                       icon.padding_left=0 \
                       icon=􀑪             \
                       icon.color=$COLOR_PEACH_ACCENT  \
                       background.drawing=off \
                       script="$PLUGIN_DIR/media.sh" \
           --subscribe media media_change
```

**Comment by FelixKratz** [comment]
Its not yet released
