### ISSUE TITLE
make font smoothing a configuration option

### ISSUE THREAD

**Issue by es183923** [FelixKratz/SketchyBar#48]
I prefer having font smoothing, but one of the [commits](https://github.com/FelixKratz/SketchyBar/commit/d9977e81b5037d8e1b805d7c5f2300f62aaa86ac) has removed that.

Please make it into a customizable choice.

**Comment by FelixKratz** [comment]
Yeah, I have no retina screen, so I can't really tell what looks good on those, but on my non-retina the font smoothing makes everything super blurry. I have added it as an option in 25127523b390d3edcaaf1b874190299f888eb05e. Will be included in the next release.
