### ISSUE TITLE
Mute button doesn't produce volume_changed event

### ISSUE THREAD

**Issue by romado77** [FelixKratz/SketchyBar#481]
I see handling kAudioDevicePropertyMute event in code, but pressing on Mute button produces no event. I'm on Sonoma 14.2.1.

**Comment by FelixKratz** [comment]
Which mute button do you mean exactly?

**Comment by romado77** [comment]
yep

**Comment by WantToLearnJapanese** [comment]
For me, it happens only when the output device is set as a Bluetooth device other than the built-in speaker.

**Comment by romado77** [comment]
Confirm, it only happens with bluetooth headset. It works ok with standard output.

**Comment by FelixKratz** [comment]
Should be fixed on master.
