### ISSUE TITLE
Multiple labels for one item - Feature Request

### ISSUE THREAD

**Issue by OneComputerGuy** [FelixKratz/SketchyBar#484]
Still quite new to the software and has been amazing the customization options it gives but, could it be possible to have a way to have multiple labels for one item?

This could be particularly handy for the battery item when you want to show the percentage and the time left at the same time.

Or if not possible, can we have an x_offset property? The way I've seen multiple "labels" for a specific item is creating a nested item `(sketchybar --add item 1 --set bla bla --add item 2)`

That could give the option to have one on top of the other

**Comment by erics118** [comment]
For labels, I suppose you can use a regex to match what you want to do with the items.
https://felixkratz.github.io/SketchyBar/config/items#changing-item-properties


You can already set items on top of each other, with the `width` property. In the README, there is an example with the CPU item. The percent and the process name are shown, one on top of the other.

![CleanShot 2024-01-14 at 20 26 56](https://github.com/FelixKratz/SketchyBar/assets/52634785/c55ff2f0-bc71-4348-87c4-a4c6cf6f349b)
