### ISSUE TITLE
Global Menus

### ISSUE THREAD

**Issue by wannafedor4** [FelixKratz/SketchyBar#488]
I know that there has probably been a few trillion of these issues, but I have an idea for how it could work.

# The problem
So this is how accessing menu items works right now...
![Screenshot 2024-01-16 at 2 44 01 PM](https://github.com/FelixKratz/SketchyBar/assets/151413500/d63b3ad6-d46d-4286-a47b-b20fe4bcf269)
Absolutely disgusting I know

# A sixty-fourth-baked solution
When you click `front_app`, it should show the global menu items. I  don't know C, so I don't know how to do this in the code.
![Screenshot 2024-01-16 at 2 48 13 PM](https://github.com/FelixKratz/SketchyBar/assets/151413500/6988c841-8cec-4843-8de2-784ab3b1caa8)
I can, however, make an example config:
```bash
# some code for the front_app
sketchybar --globalmenu front_app
```
Which in english is just assigning the global menu to an item
`sketchybar --globalmenu <item>`

**Comment by erics118** [comment]
This definitely can be done with Hammerspoon's [`hs.application:getMenuItems`](https://www.hammerspoon.org/docs/hs.application.html#getMenuItems), for a relatively simple implementation

There are also C APIs (which Hammerspoon provides a Lua wrapper around) that can be used to directly integrate this into Sketchybar, but I'm not sure if it's necessary.

Also, [Menuwhere](https://manytricks.com/menuwhere/) (paid) includes basically the feature you're requesting.

[Paletro](https://appmakes.io/paletro) (paid), and [Raycast](https://www.raycast.com) (free) have this feature, but in a different UI.

**Comment by wannafedor4** [comment]
>This definitely can be done with Hammerspoon's [hs.application:getMenuItems](https://www.hammerspoon.org/docs/hs.application.html#getMenuItems), for a relatively simple implementation
>
> There are also C APIs (which Hammerspoon provides a Lua wrapper around) that can be used to directly integrate this into Sketchybar, but I'm not sure if it's necessary.

I'll look into this...
