### ISSUE TITLE
how to properly use sketchy bar app font

### ISSUE THREAD

**Issue by timchr42** [FelixKratz/SketchyBar#489]
Hi, 

I am currently using your sketchybar setup and came to realise that f.e. the WhatsApp icon is displayed with the default icon in the spaces "section" even though I have installed the 'sketchybar-app-font'. It also appears that the destined icon_map.sh is not properly working since when changing icons of other Apps (where the displaying of the icon works) they do not change. 

I am just using the font incorrectly? Where do i have to specify that sketchybar uses the sketchybar-app-font in order for this to work? 
I am really confused  and would appreciate a response :).
This is by the way the first ever 'issue' i am writing which shows that i really want this to work because sketchybar is awesome!
Thanks for making this available for anyone.

Greetings from Germany

**Comment by qns7** [comment]
Hey, have you figured it out? I have the same "problem". Grüße aus der Pfalz :)

**Comment by Signynt** [comment]
I have the same issue with WhatsApp.
Running `ps -A` confirms that the WhatsApp app is actually called that, but it's not assigning the icon.
Coincidentally I also live in Germany, maybe it's a localization issue?

**Comment by Signynt** [comment]
I've found a solution. For some reason if you place a wildcard in front of the string, it works:

```
*"WhatsApp")
  icon_result=":whats_app:"
  ;;
```

**Comment by RNBermudez** [comment]
> I've found a solution. For some reason if you place a wildcard in front of the string, it works:
> 
> ```
> *"WhatsApp")
>   icon_result=":whats_app:"
>   ;;
> ```

I think the reason is there is hidden [Left-to-right mark](https://en.wikipedia.org/wiki/Left-to-right_mark) mark (`[U+200E] char) on the leftmost part of the string.
