### ISSUE TITLE
Icons showing up as question marks in boxes

### ISSUE THREAD

**Issue by vkeshav300** [FelixKratz/SketchyBar#494]
Hi, I was recently introduced to SketchyBar by a friend of mine. After some time setting it up, it seems to be working fine except for one thing. The icons are question marks in boxes.

When searching for a solution to this, I came across another GitHub issue page (`https://github.com/FelixKratz/SketchyBar/discussions/427`). At the end of the issue, the question marks were never resolved.

I also installed the hack nerd font using what was suggested on the website:
```
brew tap homebrew/cask-fonts
brew install --cask font-hack-nerd-font
```

Still, the icons show up as question marks.
<img width="1440" alt="image" src="https://github.com/FelixKratz/SketchyBar/assets/70541603/7c00167c-f5b0-4dcb-836c-e3811f8ad2ca">

**Comment by FelixKratz** [comment]
```bash
brew install --cask sf-symbols
```

**Comment by dixonge** [comment]
installing sf-symbols did not fix it for me

(MacOS  26.5.2)

BUT! I realized that I had changed the default 'icon.font' to a font that wasn't yet installed. Installing that font fixed it (of course)

So basically nvm...
