### ISSUE TITLE
kitty icon display abnormalities

### ISSUE THREAD

**Issue by HATTER-LONG** [FelixKratz/SketchyBar#496]
Hi, I have update latest version today, but I found kitty icon not display on the tab. 
Kitty and Edge at same desktop, but it's only show Edge icon, like this:

![image](https://github.com/FelixKratz/SketchyBar/assets/31438141/8fcec880-c75c-45d9-aef6-02acfae79001)

The bar config I used your [dotfile](https://github.com/FelixKratz/dotfiles/tree/master/.config/sketchybar) it's have same problem. What could have caused this? 

Thanks for your work. Hope reply.

**Comment by FelixKratz** [comment]
You need to update the sketchybar-app-font:
```bash
curl -L https://github.com/kvndrsslr/sketchybar-app-font/releases/download/v1.0.23/sketchybar-app-font.ttf -o $HOME/Library/Fonts/sketchybar-app-font.ttf
```
it has a new icon for kitty

**Comment by HATTER-LONG** [comment]
Oh thanks, I forgot this.  😂
