### ISSUE TITLE
Duplicate keys in space_windows_change INFO

### ISSUE THREAD

**Issue by doebi** [FelixKratz/SketchyBar#498]
Hi Felix!
Thanks for this project. For me coming from more than 10 years of Linux with i3 this is a true lifesaver in getting some of the beloved features to my new mac.

While customizing sketchybar to my needs I discovered that the event "space_windows_change" produces somewhat invalid JSON for me.

These are printouts of the $INFO payload received from the event:
```
{ "space": 2, "apps": { } }
{ "space": 1, "apps": { "Brave Browser": 1, "Alacritty": 1, "Alacritty": 1, "Alacritty": 1 } }
{ "space": 4, "apps": { } }
{ "space": 3, "apps": { } }
```

It seems that it does not detect Alacritty as being the same application but detects them as individual applications. Which in itself is not actually a bad thing, my dock is behaving in a similar manner resulting in multiple icons of the same application.

<img width="421" alt="Screenshot 2024-02-01 at 13 35 27" src="https://github.com/FelixKratz/SketchyBar/assets/1591457/b7035060-6f5e-4500-be74-d2fae607235b">

The problem however is when I parse this string with `jq`it will rightfully remove all duplicate keys from the set and  I end up with wrong information.

I had a look at your code to find the root of this JSON and traced it back to this part: https://github.com/FelixKratz/SketchyBar/blob/7d121d55e2e694c2cd9655dbdfdd70f9954e626c/src/app_windows.c#L135

This kinda explains the behaviour, but leaves me quesitoning on how to solve it.
I have two thoughts:

**A: fixing the count detection**
to retain compatibility with existing setups fixing the count detection so duplicat keys are summed up would be one approach

**B: changing the format**
While looking at your code i asked myself if you wouldn't want to change the format in something more robust and potentially expandable with more metadata for future uses. For example having a window_id as key in the set or switching to an ordinary list of objects containing arbitrary data.

Let me know what you think. Cheers.

**Comment by FelixKratz** [comment]
I think JSON is very easy to work with when using `jq` from bash. Additionally, the API exposed via the mach port of sketchybar can be interacted with by different means as well. One example would be https://github.com/FelixKratz/SbarLua where all of the communication between the lua module and sketchybar is done directly via the mach ports of both processes. Here all JSON is directly translated into lua tables.
