### ISSUE TITLE
Different behaviors when run from command line or through homebrew

### ISSUE THREAD

**Issue by bustinbung** [FelixKratz/SketchyBar#499]
I recently started having this issue with my current setup. When I run sketchybar via homebrew (`brew services start sketchybar`), I get buggy colors and unexpected output from my plugins. When I run sketchybar via the command line, the behavior goes away. I've attached a screen recording that hopefully demonstrates this.

Notice:
- Multiple spaces "active" at a time
- Wrong space highlighted (space 3 (browser) highlighted when space 2 (emacs) is open)
- Colors inverted

I wasn't thinking about submitting an issue, but given that it only occurs when run through homebrew, I wonder if it isn't the fault of my (poorly written) plugin. Thanks for the help!

**EDIT:** I just made my dotfiles repository public. If you need to look at what I have running, you can look at it [here](https://github.com/bustinbung/dotfiles/tree/main/private_dot_config/sketchybar)

## **Flashing screen warning**

<details><summary>Screen recording</summary>
<p>

https://github.com/FelixKratz/SketchyBar/assets/22670587/d4cb849a-ccf1-42c2-ad13-c8cb09faf194

</p>
</details>

**Comment by FelixKratz** [comment]
Could you check what is written to the log files located in `/opt/homebrew/var/log/sketchybar`? These contain the output of sketchybar when it is run as a brew service.

**Comment by bustinbung** [comment]
Only thing I see in the logs is `sketchybar: could not acquire lock-file... already running?`. I'll see if I can move the logic out of the spaces plugin, but it'll probably be a second before I can get to it. Thanks for the tip!

Should I continue to keep this issue open? It might just be an overhead thing like you mentioned.

**Comment by bustinbung** [comment]
I went ahead and moved the logic for space labels and space selections to their own functions and that seemed to have solved the issue (see [186ada3](https://github.com/bustinbung/dotfiles/commit/186ada3b5aeac03db643bd22fad915ed37fbb89f)). I've still got some bugs to work out, but I'm going to go ahead and close this issue for now.

**Comment by bustinbung** [comment]
Thanks for clarifying, really appreciate your work in creating this for the community!
