### ISSUE TITLE
Enable Mouse.scrolled events for macbook touchpad

### ISSUE THREAD

**Issue by aspauldingcode** [FelixKratz/SketchyBar#505]
Problem:
Sketchybar allows to subscribe to mouse.scrolled() events, which allows me to use scroll for volume_change. 

However, it only works on my mouse. If I use my macbook air m1 touchpad, the two-finger scroll doesn't activate the mouse.scrolled() event in sketchybar, meaning I cannot use scroll to volume change on the go.

Solution:
allow two-finger scroll to activate mouse.scrolled() event

**Comment by FelixKratz** [comment]
Should be fixed by e9371f6
