### ISSUE TITLE
How do I join items?

### ISSUE THREAD

**Issue by FormalSnake** [FelixKratz/SketchyBar#508]
I want it to look like this
![74165](https://github.com/FelixKratz/SketchyBar/assets/90651091/c65f0c3f-41e3-4c47-ace2-4f55191d4b6e)
this is how I have it now.
<img width="613" alt="Screenshot 2024-02-19 at 15 03 41" src="https://github.com/FelixKratz/SketchyBar/assets/90651091/f12f9fa9-487b-4b81-acde-67227354b494">

**Comment by FelixKratz** [comment]
You are looking for a `bracket`:
https://felixkratz.github.io/SketchyBar/config/components#item-bracket----group-items-in-eg-colored-sections
