### ISSUE TITLE
SketchyBar not hidden on Firefox fullscreen videos

### ISSUE THREAD

**Issue by ruigomeseu** [FelixKratz/SketchyBar#509]
Fullscreening a YouTube video in Safari or Chrome works as expected: SketchyBar automatically hides once the video goes fullscreen.

When fullscreening a video using Firefox, the bar does not automatically hide.

**Comment by FelixKratz** [comment]
I think it is because firefox does not use the macOS native-fullscreen feature, but some custom "fullscreen", which probably works by ordering the fullscreen window above all other app windows.

The solution is to make sketchybar not topmost:
```bash
sketchybar --bar topmost=off
```
