### ISSUE TITLE
Alias click events?

### ISSUE THREAD

**Issue by FormalSnake** [FelixKratz/SketchyBar#510]
Hi, so I want to add some aliases in Sketchybar but when I click on one it doesn't do anything. If it is possible it would be cool that if I click on one it does whatever it would do in the normal menubar.

**Comment by FelixKratz** [comment]
It is possible to make this the click action of the item, however, as discussed in #236 it does not properly reposition the popup.

I currently have something like this for my new config with the app menus:

https://github.com/FelixKratz/SketchyBar/assets/22680421/39e3ecbd-d2ce-4058-b361-ef8393868383

**Comment by FormalSnake** [comment]
It seems to work perfectly in your demo, could you provide a snippet for that click action?
It seems great.

**Comment by lcjnil** [comment]
> It is possible to make this the click action of the item, however, as discussed in #236 it does not properly reposition the popup.
> 
> I currently have something like this for my new config with the app menus:
> 
>  demo.mp4

This is awesome, will you share your dot files in the future?

**Comment by FormalSnake** [comment]
@FelixKratz how do I use multiple aliases for the same app? I want to use some raycast menu bar items but I do not know how to specify which one must use which.

**Comment by FormalSnake** [comment]
Thank you!
