### ISSUE TITLE
Label -  Background Highlight Features

### ISSUE THREAD

**Issue by m010-cpu** [FelixKratz/SketchyBar#516]
Hi,
Would it be possible to implement the highlight features for the background color?

Thanks in advance.

**Comment by FelixKratz** [comment]
You can change all colors at any time, so the highlight feature is not really needed for anything and is only implemented for texts as a shortcut. E.g. where you could do a conditional check and choose the <color> accordingly:
```bash
sketchybar --set <name> background.color=<color>
```

**Comment by m010-cpu** [comment]
> You can change all colors at any time, so the highlight feature is not really needed for anything and is only implemented for texts as a shortcut. E.g. where you could do a conditional check and choose the `<color>` accordingly:
> 
> ```bash
> 
> sketchybar --set <name> background.color=<color>
> 
> ```

Okay thanks for your reply.
How could I implement the check of highlight with a condition as you said?
Thanks in advance.

**Comment by FelixKratz** [comment]
Here is an example from my dotfiles (only the update function):
https://github.com/FelixKratz/dotfiles/blob/7cef83fc577bb8853c01d6aae66fdc6625feb761/.config/sketchybar/plugins/space.sh#L3-L12
