### ISSUE TITLE
Wifi title disappeared after latest OS update

### ISSUE THREAD

**Issue by Cliffback** [FelixKratz/SketchyBar#517]
My sketchybar config has been working very well, but after the latest OS update (14.4), suddenly the wifi title is blanked out. 

I'm wondering if I'm the only one getting this bug, or did it happen to more people after the update?

<img width="102" alt="Screenshot 2024-03-12 at 20 40 20" src="https://github.com/FelixKratz/SketchyBar/assets/51080320/a4753664-8fd6-49d6-b179-88d5e2171c51">

My network config:

```bash
LABEL=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | awk 'NR==13 {print $2}')

sketchybar --set $NAME label=$LABEL
```

Btw. I really enjoy sketchybar, thank you so much!

**Comment by FelixKratz** [comment]
It seems apple deprecated the airport command used in the script, you can just swap it with another utility for now, see: https://github.com/FelixKratz/SketchyBar/issues/407#issuecomment-1986867413

**Comment by Cliffback** [comment]
> It seems apple deprecated the airport command used in the script, you can just swap it with another utility for now, see: [#407 (comment)](https://github.com/FelixKratz/SketchyBar/issues/407#issuecomment-1986867413)

Thank you, that did the trick!

**Comment by keikun555** [comment]
For those who found this post when upgrading to Sequoia, here's a workaround I found
https://stackoverflow.com/questions/78994709/how-to-get-the-current-wi-fi-ssid-in-swift-on-macos

**Comment by keikun555** [comment]
The approach from the above link now also shows `<redacted>`. I now use this: https://www.reddit.com/r/MacOS/comments/1ktm5bw/comment/nf9gh7w/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
