### ISSUE TITLE
customize graph colors and line thickness

### ISSUE THREAD

**Issue by es183923** [FelixKratz/SketchyBar#52]
It'd be nice to be able to customize the graph color that is below the line. Currently, it is just a bit brighter, and not customizable

**Comment by FelixKratz** [comment]
Could you specify what you mean exactly, maybe with a screenshot?

**Comment by es183923** [comment]
Currently, graphs look like this: 

<img width="200" alt="Screen Shot 2021-09-24 at 1 47 41 PM" src="https://user-images.githubusercontent.com/72744903/134718673-aadcb504-6dd2-4157-ab55-653f3c5843ca.png">

There is a line and the part below that is shaded lighter than the line itself.
I'd like for the line thickness and the shaded area below the line color to be customizable.

**Comment by FelixKratz** [comment]
Ah, yes I was planning to do exactly that for some time now, but other tings got in the way.

**Comment by FelixKratz** [comment]
Should be all customizable now e5c9e94f84f7e641b99bfdd3f653c9ae9de8bb4f
