### ISSUE TITLE
why arent the icons appearing ?

### ISSUE THREAD

**Issue by GhostTech-69** [FelixKratz/SketchyBar#529]
I just bought a mac today, and thought id try this out and it works but there are no icons appearing, did i miss something in the code ?
<img width="1440" alt="Screenshot 1445-09-23 at 5 22 27 AM" src="https://github.com/FelixKratz/SketchyBar/assets/142755636/87b9e135-258c-4f09-9215-03b69ca10978">
<img width="1440" alt="Screenshot 1445-09-23 at 5 22 27 AM" src="https://github.com/FelixKratz/SketchyBar/assets/142755636/95ec02bb-d451-4ecf-b6ee-483f1f7ed2e4">

**Comment by Fau818** [comment]
you need a [Nerd Font](https://www.nerdfonts.com/)

**Comment by Fau818** [comment]
See: https://felixkratz.github.io/SketchyBar/config/tricks#finding-icons and https://felixkratz.github.io/SketchyBar/setup#fonts
