### ISSUE TITLE
Default menu bar aliases are much bigger then other items

### ISSUE THREAD

**Issue by azuwis** [FelixKratz/SketchyBar#53]
MacBook Pro (13-inch, M1, 2020)

```
sketchybar -m config height 24
sketchybar -m add component alias 'Control Center,WiFi' right
```

<img width="245" alt="Screen Shot 2021-09-24 at 15 19 03" src="https://user-images.githubusercontent.com/9315/134634579-0fca73d6-92ff-455c-b8b5-289bb8b3b320.png">

**Comment by FelixKratz** [comment]
Thanks for reporting this, it has to do with retina displays and the way scaling works I think. I have no retina screen but will try to fix this, such that the item aliases can be scaled.

**Comment by FelixKratz** [comment]
Could you maybe try it with this commit: 6170ff34f7d587081180ddcc5ad9e5946adbb2d3.
I use a private API to capture the menu bar windows and have to reverse engineer the capture flag, but since I have no retina screen myself it makes no difference on my screen, wether the *best* or *nominal* resolution is captured, which makes this a bit difficult.

**Comment by azuwis** [comment]
Same as v1.3.0

<img width="268" alt="Screen Shot 2021-09-24 at 23 32 25" src="https://user-images.githubusercontent.com/9315/134701654-89b71928-6f94-4e1b-a342-543f381ca6c9.png">

**Comment by brogers** [comment]
I [replied on the commt](https://github.com/FelixKratz/SketchyBar/commit/6170ff34f7d587081180ddcc5ad9e5946adbb2d3#commitcomment-57014654) that I am still seeing the issue as well.

**Comment by FelixKratz** [comment]
How about now? 53ea4c913c941a23891ea3ac189a952701d2477c

**Comment by brogers** [comment]
Looks perfect!

**Comment by brogers** [comment]
<img width="329" alt="Screen Shot 2021-09-24 at 12 57 57 PM" src="https://user-images.githubusercontent.com/14743/134713019-e6643e0f-7184-4dd1-907c-c61da3637bcd.png">
It is the green lock.

**Comment by FelixKratz** [comment]
Will make a patch release with this fix.

**Comment by FelixKratz** [comment]
Btw: the default items commonly have very big paddings, you can reduce them by supplying a negative left icon padding and a negative right label padding for the alias
