### ISSUE TITLE
Issue with multiple displays 

### ISSUE THREAD

**Issue by MiragianCycle** [FelixKratz/SketchyBar#533]
<img width="1512" alt="Screenshot 2024-04-04 at 15 20 11" src="https://github.com/FelixKratz/SketchyBar/assets/58807314/df069d4b-b85e-4742-b28f-845d30a63581">

<img width="1512" alt="Screenshot 2024-04-04 at 15 20 11 (2)" src="https://github.com/FelixKratz/SketchyBar/assets/58807314/df069d4b-b85e-4742-b28f-845d30a63581">

Hello. 

Firstly, love skethybar. I use it in conjunction with skhd and Yabai, and I am very happy. 

I do however, have an issue when using with multiple displays. See image. The application windows are perfectly aligned under sketchybar on the mainscreen, a Macbook M1, while on my external display, the app windows cover sketchybar. This is the case with every application. 

Apologies if this has been asked before but I can't seem to find anything looking at the issues or on Google. 

Thank you in advance.

**Comment by MiragianCycle** [comment]
![Screenshot 2024-04-04 at 15 20 11 (2)](https://github.com/FelixKratz/SketchyBar/assets/58807314/d38d148b-ebca-43aa-a882-c2f3304dffed)

Here's a screenshot of what the sketchybar looks like on display 2.

**Comment by MiragianCycle** [comment]
![Screenshot 2024-04-04 at 15 28 48 (2)](https://github.com/FelixKratz/SketchyBar/assets/58807314/f3f9472f-92f7-4019-80e5-4208a4a249ae)

Display 2 screenshot. As you can see the browser window completely obscures sketchybar. This is the case no matter what application I have open. 

Would appreciate how to correct it. Thanks in advance.

**Comment by MiragianCycle** [comment]
![Screenshot 2024-04-04 at 15 31 14 (2)](https://github.com/FelixKratz/SketchyBar/assets/58807314/6a01503b-af7d-41c4-bf0a-9bbdb5deeac4)

Display two when it has no open application windows.

**Comment by FelixKratz** [comment]
You need to use external bar config command fron yabai, e.g.:
```bash
yabai -m config external_bar all:40:0
```
It will create room for sketchybar on all displays and will tile the app windows below the bar.

**Comment by MiragianCycle** [comment]
Solved. Thank you so much.
