### ISSUE TITLE
Icon separation

### ISSUE THREAD

**Issue by deimosfr** [FelixKratz/SketchyBar#538]
Hi,

Is it possible to have a default icon separation like dots or pipes without having to append it to each item label/icon?

I'd like to reproduce standard behavior we can find in i3blocks, i3-status-rs etc...

Thanks in advance

**Comment by FelixKratz** [comment]
There is no system in place to do this currently. However, I don't think I want to have additional text properties for items such that a common "divider" between items would need to be implemented at config level with an abstraction (e.g. a function you declare globally, which adds an item with given properties and then automatically appends another "divider" item). Furthermore, there are a multitude of background properties which could be used for visual separation.
