### ISSUE TITLE
intersecting backgrounds

### ISSUE THREAD

**Issue by es183923** [FelixKratz/SketchyBar#54]
When there are two items next to each other that both have a background, they may intersect each other

<img width="200" alt="Screen Shot 2021-09-24 at 2 17 42 PM" src="https://user-images.githubusercontent.com/72744903/134722139-7f4be64e-3513-4bae-a8f2-dc3072d1acdd.png">

This shows that the item length has increased, which should not happen.

To fix this, and allow for customization, new variables must be set to control the padding of the background:

```
|border_padding_left|icon_padding_left|icon|icon_padding_right|label_padding_left|label|label_padding_right|border_padding_right|
```

**Comment by FelixKratz** [comment]
There is an "off by one" error somewhere in my code, this exists already since the original introduction of item backgrounds, but I never took the time to search for it. I have added the background paddings however 251891006aa95fed729a148b85e43300bb1e07ed.

**Comment by es183923** [comment]
It works now. I'm closing this.
