### ISSUE TITLE
[help]get some errors in the time display

### ISSUE THREAD

**Issue by Jayden12138** [FelixKratz/SketchyBar#546]
I'm getting some errors in 'clock.sh', but i don't have any setting about 'date'

![image](https://github.com/FelixKratz/SketchyBar/assets/161050006/5bbf2674-d15c-40cd-bab2-bfa7e3425bd3)

The relevant files are configured as follows

```
// .config/sketchybar/plugins/clock.sh

#!/bin/sh

# Output the date to debug any issues
echo "$(date '+%d/%m %H:%M')"

# The $NAME variable is passed from sketchybar and holds the name of
# the item invoking this script:
# https://felixkratz.github.io/SketchyBar/config/events#events-and-scripting

sketchybar --set "$NAME" label="$(date '+%d/%m %H:%M')"

```

```
// .config/sketchbar/sketchybarrc

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

#!/usr/bin/env bash

sketchybar -m --bar blur_radius=50                                                            \
                    height=32                                                                 \
              --add item apple.logo left                                                      \
              --set apple.logo icon=􀣺                                                         \
                               icon.font="SF Pro:Black:16.0"                                  \
                               label.drawing=off                                              \
                               click_script="sketchybar -m --set \$NAME popup.drawing=toggle" \
                               popup.background.border_width=2                                \
                               popup.background.corner_radius=3                                \
                               popup.background.border_color=0xff9dd274                       \
                                                                                              \
              --default background.padding_left=5                                             \
                        background.padding_right=5                                            \
                        icon.padding_right=5                                                  \
                        icon.font="SF Pro:Bold:16.0"                                          \
                        label.font="SF Pro:Semibold:13.0"                                     \
                                                                                              \
              --add item apple.preferences popup.apple.logo                                   \
              --set apple.preferences icon=􀺽                                                  \
                               label="Preferences"                                            \
                               click_script="open -a 'System Preferences';                    
                                             sketchybar -m --set apple.logo popup.drawing=off"\
              --add item apple.activity popup.apple.logo                                      \
              --set apple.activity icon=􀒓                                                     \
                               label="Activity"                                               \
                               click_script="open -a 'Activity Monitor';                       
                                             sketchybar -m --set apple.logo popup.drawing=off"\
              --add item apple.lock popup.apple.logo                                          \
              --set apple.lock icon=􀒳                                                         \
                               label="Lock Screen"                                            \
                               click_script="pmset displaysleepnow;                           
                                             sketchybar -m --set apple.logo popup.drawing=off"


sketchybar --bar position=top height=40 blur_radius=30 color=0x40000000

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="SF Pro:Bold:16.0"
  label.font="SF Pro:Bold:16.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/mail.sh"
sketchybar --add alias "截屏,Item-0" right \
           --set "截屏,Item-0" update_freq=2

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update


```

**Comment by NoahCodeGG** [comment]
> I'm getting some errors in 'clock.sh', but i don't have any setting about 'date'
> 
> ![image](https://private-user-images.githubusercontent.com/161050006/328357100-5bbf2674-d15c-40cd-bab2-bfa7e3425bd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NjQ5MDMsIm5iZiI6MTcxNTY2NDYwMywicGF0aCI6Ii8xNjEwNTAwMDYvMzI4MzU3MTAwLTViYmYyNjc0LWQxNWMtNDBjZC1iYWIyLWJmYTdlMzQyNWJkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQwNTMwMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDlhMjBkNzM3Y2Q1NWFiMDI5ODYyZTMzNDM5MmNmNDEzNzdjMzZmNDA1ZmFjODhlZDNlNDQ2OWVkOGI3NGUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sA88b6TOo_IC6zNxc0P-eLOTwphq0lQ9SoL_diYgjcQ)
> 
> The relevant files are configured as follows
> 
> ```
> // .config/sketchybar/plugins/clock.sh
> 
> #!/bin/sh
> 
> # Output the date to debug any issues
> echo "$(date '+%d/%m %H:%M')"
> 
> # The $NAME variable is passed from sketchybar and holds the name of
> # the item invoking this script:
> # https://felixkratz.github.io/SketchyBar/config/events#events-and-scripting
> 
> sketchybar --set "$NAME" label="$(date '+%d/%m %H:%M')"
> ```
> 
> ```
> // .config/sketchbar/sketchybarrc
> 
> # This is a demo config to showcase some of the most important commands.
> # It is meant to be changed and configured, as it is intentionally kept sparse.
> # For a (much) more advanced configuration example see my dotfiles:
> # https://github.com/FelixKratz/dotfiles
> 
> PLUGIN_DIR="$CONFIG_DIR/plugins"
> ITEM_DIR="$CONFIG_DIR/items"
> 
> ##### Bar Appearance #####
> # Configuring the general appearance of the bar.
> # These are only some of the options available. For all options see:
> # https://felixkratz.github.io/SketchyBar/config/bar
> # If you are looking for other colors, see the color picker:
> # https://felixkratz.github.io/SketchyBar/config/tricks#color-picker
> 
> #!/usr/bin/env bash
> 
> sketchybar -m --bar blur_radius=50                                                            \
>                     height=32                                                                 \
>               --add item apple.logo left                                                      \
>               --set apple.logo icon=􀣺                                                         \
>                                icon.font="SF Pro:Black:16.0"                                  \
>                                label.drawing=off                                              \
>                                click_script="sketchybar -m --set \$NAME popup.drawing=toggle" \
>                                popup.background.border_width=2                                \
>                                popup.background.corner_radius=3                                \
>                                popup.background.border_color=0xff9dd274                       \
>                                                                                               \
>               --default background.padding_left=5                                             \
>                         background.padding_right=5                                            \
>                         icon.padding_right=5                                                  \
>                         icon.font="SF Pro:Bold:16.0"                                          \
>                         label.font="SF Pro:Semibold:13.0"                                     \
>                                                                                               \
>               --add item apple.preferences popup.apple.logo                                   \
>               --set apple.preferences icon=􀺽                                                  \
>                                label="Preferences"                                            \
>                                click_script="open -a 'System Preferences';                    
>                                              sketchybar -m --set apple.logo popup.drawing=off"\
>               --add item apple.activity popup.apple.logo                                      \
>               --set apple.activity icon=􀒓                                                     \
>                                label="Activity"                                               \
>                                click_script="open -a 'Activity Monitor';                       
>                                              sketchybar -m --set apple.logo popup.drawing=off"\
>               --add item apple.lock popup.apple.logo                                          \
>               --set apple.lock icon=􀒳                                                         \
>                                label="Lock Screen"                                            \
>                                click_script="pmset displaysleepnow;                           
>                                              sketchybar -m --set apple.logo popup.drawing=off"
> 
> 
> sketchybar --bar position=top height=40 blur_radius=30 color=0x40000000
> 
> ##### Changing Defaults #####
> # We now change some default values, which are applied to all further items.
> # For a full list of all available item properties see:
> # https://felixkratz.github.io/SketchyBar/config/items
> 
> default=(
>   padding_left=5
>   padding_right=5
>   icon.font="SF Pro:Bold:16.0"
>   label.font="SF Pro:Bold:16.0"
>   icon.color=0xffffffff
>   label.color=0xffffffff
>   icon.padding_left=4
>   icon.padding_right=4
>   label.padding_left=4
>   label.padding_right=4
> )
> sketchybar --default "${default[@]}"
> 
> source "$ITEM_DIR/spaces.sh"
> source "$ITEM_DIR/front_app.sh"
> 
> ##### Adding Right Items #####
> # In the same way as the left items we can add items to the right side.
> # Additional position (e.g. center) are available, see:
> # https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar
> 
> # Some items refresh on a fixed cycle, e.g. the clock runs its script once
> # every 10s. Other items respond to events they subscribe to, e.g. the
> # volume.sh script is only executed once an actual change in system audio
> # volume is registered. More info about the event system can be found here:
> # https://felixkratz.github.io/SketchyBar/config/events
> 
> source "$ITEM_DIR/clock.sh"
> source "$ITEM_DIR/volume.sh"
> source "$ITEM_DIR/battery.sh"
> source "$ITEM_DIR/mail.sh"
> sketchybar --add alias "截屏,Item-0" right \
>            --set "截屏,Item-0" update_freq=2
> 
> ##### Force all scripts to run the first time (never do this in a script) #####
> sketchybar --update
> ```
Check if clock.sh exists under the path ITEM_DIR="$CONFIG_DIR/items".
