### ISSUE TITLE
Bar flickering issue on space change when "sticky=on" and "Reduce Moution" is on

### ISSUE THREAD

**Issue by pyinto** [FelixKratz/SketchyBar#548]
As it stands in the release notes for [2.20.1](https://github.com/FelixKratz/SketchyBar/releases/tag/v2.20.1), there should not be flickering during space change animation, which is something I don't see working as intended.
> Reimplement the sticky property -- with sticky=on, the bar is now stationary during space change animations (https://github.com/FelixKratz/SketchyBar/issues/493)

There is no flickering when the `Reduce Motion` setting is switched `off`, but once it's `on`, flickering occurs as you may see in the video. If I switch `sticky` `off`  there is no visible difference, so clearly something wrong.
I see it when using:
* native swiping gesture on a Magic Trackpad,
* native Mac OS shortcuts: `Move right/left a space`
* native Mac OS shortcuts: `Switch to Desktop X`  (less flickering)

I don't have SIP disabled, so I don't have access to `yabai` commands to switch spaces and further reduce animation. Not sure if it's required for the `sticky` option to work properly, but if so, I guess it's a good idea to add it to the description.

I also tried to reinstall the `sketchybar` - no changes, as I expected, because I discovered and installed this awesome app just 2 days ago for the first time!

https://github.com/FelixKratz/SketchyBar/assets/19248049/589b70bd-2ba7-4fa2-993d-adf5541262eb

* Output for `sketchybar --query bar`:
```
{
        "position": "top",
        "topmost": "off",
        "sticky": "on",
        "hidden": "off",
        "shadow": "off",
        "font_smoothing": "off",
        "blur_radius": 100,
        "margin": 0,
        "drawing": "on",
        "color": "0xb21e1e2e",
        "border_color": "0xffff0000",
        "border_width": 0,
        "height": 26,
        "corner_radius": 7,
        "padding_left": 20,
        "padding_right": 20,
        "y_offset": 0,
        "clip": 0.000000,
        "image": {
                "value": "(null)",
                "drawing": "off",
                "scale": 1.000000
        },
        "items": [
                 "apple",
                 "front_app",
                 "space.1",
                 "space.2",
                 "space.3",
                 "space.4",
                 "space.5",
                 "space.6",
                 "space.7",
                 "space.8",
                 "space.9",
                 "space.10",
                 "space.11",
                 "space.12",
                 "space_creator",
                 "calendar",
                 "clock",
                 "keyboard",
                 "volume"
        ]
}
```

* My Environment:
```
macOS 14.4.1 (23E224)
sketchybar-v2.21.0
```

Please let me know if I am missing something, or you need me to provide something else to investigate. Thanks!

**Comment by FelixKratz** [comment]
Yeah, I think it is in the nature how apple implemented the Reduce Motion feature. They seem to blend the wallpaper on the top layer (or something criminal like that). So there is nothing we can do about that apart from not using the Reduce Motion accessibility feature.
