### ISSUE TITLE
Some Values Missing from Query System

### ISSUE THREAD

**Issue by FelixKratz** [FelixKratz/SketchyBar#55]
Please post the values missing from the query system below.

**Comment by FelixKratz** [comment]
Basic item querying introduced in 906ec7a1aa49080d35be66f005f67bb39e328667, but not done yet.

**Comment by FelixKratz** [comment]
Almost complete since 63f265c68dcfa980e532f7431e3997ef5024ba94, am I missing something?

**Comment by es183923** [comment]
type should give `item` instead of `i`, and `space` instead of `s`.

**Comment by es183923** [comment]
position should be `right` or `left` or `center` instead of `r`, `l`, and `c`

**Comment by es183923** [comment]
nospace gives `"0"` or `"1"`, while it should give `0` or `1`

**Comment by es183923** [comment]
it'd be nice to query the current defaults `sketchybar -m query default`

**Comment by es183923** [comment]
currently, doing `sketchybar -m query bar` gives the items the left items in order, the middle items in order, and the right items backward. I think that the right items should be in the logical order from left to right.

**Comment by es183923** [comment]
what do the masks mean? 
masks: `associated_bar_mask`, `associated_display_mask`, `associated_space_mask`, `update_mask`

**Comment by es183923** [comment]
query doesn't give the `script` and `click_script`.

**Comment by es183923** [comment]
You can't query graphs

**Comment by FelixKratz** [comment]
> type should give `item` instead of `i`, and `space` instead of `s`.

the type is either i: item, g: graph, s: space, a: alias. thats what I am using internally to save the type to a single char.

**Comment by FelixKratz** [comment]
> position should be `right` or `left` or `center` instead of `r`, `l`, and `c`

same as the type

**Comment by FelixKratz** [comment]
> currently, doing `sketchybar -m query bar` gives the items the left items in order, the middle items in order, and the right items backward. I think that the right items should be in the logical order from left to right.

they are listed in the order they are drawn to screen and in the same order they appear in the config. right items appear from right to left while center and left items appear from right to left.

**Comment by FelixKratz** [comment]
> what do the masks mean?
> masks: `associated_bar_mask`, `associated_display_mask`, `associated_space_mask`, `update_mask`

These are the raw bit masks, the i-th bit is the i-th association boolean value.

**Comment by FelixKratz** [comment]
> query doesn't give the `script` and `click_script`, as well as `update_freq`

Yes, those need to be escaped properly before being passed into the json type string, otherwise a big  mess is created and I thought it wouldnt be fun doing that, so I didnt. But I will do it someday for the sake of completeness.

**Comment by es183923** [comment]
> > type should give `item` instead of `i`, and `space` instead of `s`.
> 
> the type is either i: item, g: graph, s: space, a: alias. thats what I am using internally to save the type to a single char.

This makes it more difficult for the user. I think that making it give the full name only when querying would make it better. (meaning that you change `i` to `item` when outputting the query code.)

**Comment by es183923** [comment]
> > query doesn't give the `script` and `click_script`, as well as `update_freq`
> 
> Yes, those need to be escaped properly before being passed into the json type string, otherwise a big mess is created and I thought it wouldnt be fun doing that, so I didnt. But I will do it someday for the sake of completeness.

check out [json](https://github.com/nlohmann/json) and its [escape_string function](https://github.com/nlohmann/json/blob/ec7a1d834773f9fee90d8ae908a0c9933c5646fc/src/json.hpp#L4604-L4697)

**Comment by FelixKratz** [comment]
> it'd be nice to query the current defaults `sketchybar -m query default`

Possible since a26e228d96fe8d50ea67af33dcf3acf76f63f879.
```bash
sketchybar -m query defaults
```

**Comment by es183923** [comment]
> > it'd be nice to query the current defaults `sketchybar -m query default`
> 
> Possible since [a26e228](https://github.com/FelixKratz/SketchyBar/commit/a26e228d96fe8d50ea67af33dcf3acf76f63f879).
> 
> ```shell
> sketchybar -m query defaults
> ```

i don't think it works the way it should. Here is its response:

<details>
<summary><code>sketchybar -m query defaults</code></summary>
<br>

```json
{
	"name": "",
	"type": "i",
	"text": {
		"icon": "",
		"label": "",
		"icon_font": "Hack Nerd Font:Bold:16.0",
		"label_font": "SF Pro:Medium:13.0"
	},
	"geometry": {
		"position": "r",
		"nospace": 0,
		"background_padding_left": 2,
		"background_padding_right": 2,
		"icon_padding_left": 4,
		"icon_padding_right": 2,
		"label_padding_left": 2,
		"label_padding_right": 4
	},
	"style": {
		"icon_color:": "0xffffffff",
		"icon_highlight_color:": "0xff7fe5f0",
		"label_color:": "0xffffffff",
		"label_highlight_color:": "0xff7fe5f0",
		"draws_background": 0,
		"background_height": 18,
		"background_corner_radius": 0,
		"background_border_width": 1,
		"background_color:": "0xaabeefed",
		"background_border_color:": "0xffffffff"
	},
	"state": {
		"drawing": 1,
		"updates": 1,
		"lazy": 0,
		"cache_scripts": 0,
		"associated_bar_mask": 0,
		"associated_display_mask": 0,
		"associated_space_mask": 0,
		"update_mask": 0
	},
	"bounding_rects": {

	}
}
```

</details>

**Comment by FelixKratz** [comment]
> > > it'd be nice to query the current defaults `sketchybar -m query default`
> > 
> > 
> > Possible since [a26e228](https://github.com/FelixKratz/SketchyBar/commit/a26e228d96fe8d50ea67af33dcf3acf76f63f879).
> > ```shell
> > sketchybar -m query defaults
> > ```
> 
> i don't think it works the way it should. Here is its response:
> 
> `sketchybar -m query defaults`
> 
> ```json
> {
> 	"name": "",
> 	"type": "i",
> 	"text": {
> 		"icon": "",
> 		"label": "",
> 		"icon_font": "Hack Nerd Font:Bold:16.0",
> 		"label_font": "SF Pro:Medium:13.0"
> 	},
> 	"geometry": {
> 		"position": "r",
> 		"nospace": 0,
> 		"background_padding_left": 2,
> 		"background_padding_right": 2,
> 		"icon_padding_left": 4,
> 		"icon_padding_right": 2,
> 		"label_padding_left": 2,
> 		"label_padding_right": 4
> 	},
> 	"style": {
> 		"icon_color:": "0xffffffff",
> 		"icon_highlight_color:": "0xff7fe5f0",
> 		"label_color:": "0xffffffff",
> 		"label_highlight_color:": "0xff7fe5f0",
> 		"draws_background": 0,
> 		"background_height": 18,
> 		"background_corner_radius": 0,
> 		"background_border_width": 1,
> 		"background_color:": "0xaabeefed",
> 		"background_border_color:": "0xffffffff"
> 	},
> 	"state": {
> 		"drawing": 1,
> 		"updates": 1,
> 		"lazy": 0,
> 		"cache_scripts": 0,
> 		"associated_bar_mask": 0,
> 		"associated_display_mask": 0,
> 		"associated_space_mask": 0,
> 		"update_mask": 0
> 	},
> 	"bounding_rects": {
> 
> 	}
> }
> ```

Whats wrong with that?

**Comment by es183923** [comment]
```diff
{
-	"name": "",
-	"type": "i",
	"text": {
-		"icon": "",
-		"label": "",
		"icon_font": "Hack Nerd Font:Bold:16.0",
		"label_font": "SF Pro:Medium:13.0"
	},
	"geometry": {
-		"position": "r",
-		"nospace": 0,
		"background_padding_left": 2,
		"background_padding_right": 2,
		"icon_padding_left": 4,
		"icon_padding_right": 2,
		"label_padding_left": 2,
		"label_padding_right": 4
	},
	"style": {
		"icon_color:": "0xffffffff",
		"icon_highlight_color:": "0xff7fe5f0",
		"label_color:": "0xffffffff",
		"label_highlight_color:": "0xff7fe5f0",
		"draws_background": 0,
		"background_height": 18,
		"background_corner_radius": 0,
		"background_border_width": 1,
		"background_color:": "0xaabeefed",
		"background_border_color:": "0xffffffff"
	},
	"state": {
		"drawing": 1,
		"updates": 1,
		"lazy": 0,
		"cache_scripts": 0,
-		"associated_bar_mask": 0,
-		"associated_display_mask": 0,
-		"associated_space_mask": 0,
-		"update_mask": 0
	},
-	"bounding_rects": {
-
-	}
}
```

**Comment by FelixKratz** [comment]
*scripting* has been renamed to *updates*, but I forgot to update it in the default section of the README.
Otherwise this is all fine. These are the initialization values for all further items, which are only overridden by set commands (the bounding rects are created dynamically).

**Comment by FelixKratz** [comment]
Basically only the scripts are missing from the query output now or did I miss anything else?

**Comment by FelixKratz** [comment]
Popup Menus Missing

**Comment by FelixKratz** [comment]
Shadows missing

**Comment by FelixKratz** [comment]
Images missing

**Comment by FelixKratz** [comment]
Item align missing

**Comment by FelixKratz** [comment]
The querying logic will be completely rewritten soon, this will be a minor breaking change for everyone relying on the exact JSON structure of the query output. I will change the structure to reflect the classification from the documentation and I will try to include every property such that a full serialization of the bars configuration is possible.

**Comment by FelixKratz** [comment]
I believe all documented item properties can now be queried via:
```bash
sketchybar --query <name>
```
and read out via:
```bash
sketchybar --query <name> | jq '.<property>'
```
