### ISSUE TITLE
bar hidden = off disables important event

### ISSUE THREAD

**Issue by aspauldingcode** [FelixKratz/SketchyBar#550]
Hi,
I have an event to detect with sketchybar when app changes focus.
This triggers a script which detects if I am in x11.bin or not. This is the only way I can keep skhd enabled and still drag around i3 windows, and then go back to macos apps and use alt to drag around yabai windows. 

However, when I toggle sketchybar off, I didn't expect it to no longer use the event. 
This is a problem. I need that script to detect if I switch or not running all the time. Is there a better solution? Or maybe a way to keep an event running even if sketchybar is hidden?

**Comment by FelixKratz** [comment]
Did you set `updates=when_shown` for the item receiving the event (or as a default)? If so setting it to `updates=on` for this item might help you.

**Comment by aspauldingcode** [comment]
Oh, I did not see that. thanks, works!
