### ISSUE TITLE
Padding for brackets

### ISSUE THREAD

**Issue by MattressPadley** [FelixKratz/SketchyBar#556]
Maybe I'm not doing it right but I want to pad my brackets so they don't touch.

I've tried,
padding_left=5
and
background.padding_left=5

neither of which work. I though brackets used all background properties am I incorrect?

**Comment by FelixKratz** [comment]
See https://github.com/FelixKratz/SketchyBar/issues/351#issuecomment-1518829419 why I chose to not make bracket paddings available.
