### ISSUE TITLE
Native ARM Binary

### ISSUE THREAD

**Issue by FelixKratz** [FelixKratz/SketchyBar#56]
I want to move to a universal binary with both x86_64 and arm64 instructions, but have no ARM CPU at hand, I have implemented this on the branch arm64 can someone test it?

**Comment by es183923** [comment]
I'm on a M1 Mac, I can help test it!

**Comment by FelixKratz** [comment]
It is implemented [here](https://github.com/FelixKratz/SketchyBar/tree/arm64), you can clone and run *make* in the folder, then three binaries should be created, the x86 binary, the arm64 binary and the universal binary. If you run "./bin/sketchybar" it should run the native arm code automatically. You could also try the standalone arm binary.

**Comment by es183923** [comment]
everything seems to be working.

**Comment by FelixKratz** [comment]
Great! Will be included in the next release then. Do you see a performance difference between the native arm binary and the translated x86 binary?

**Comment by erics118** [comment]
Not that I can notice.

**Comment by es183923** [comment]
Nope.

**Comment by FelixKratz** [comment]
Rosetta 2 seems to work great. Either way, native code is always more efficient.

**Comment by FelixKratz** [comment]
Does the new homebrew release install ok?

**Comment by es183923** [comment]
Yes, everything so far works perfectly.
