### ISSUE TITLE
OSX switching workspaces flashes.

### ISSUE THREAD

**Issue by vegetablesalad** [FelixKratz/SketchyBar#561]
When I switch workspaces the bar disappears for couple of ms. I can see the desktop wallpaper for a tiny bit.
That is when switching directly to a # workspace. When I go to left/right with swipe or shortcut then it disappears for even longer, about 1 second. Is that normal behavior?

I'm using yabai if that is relevant.

```
sketchybar-v2.21.0
Apple M3 Pro
MacOS 14.1 (23B2073)
```

**Comment by FelixKratz** [comment]
Try the `sticky` bar property, or see #548

**Comment by vegetablesalad** [comment]
I tried the sticky option and it doesn't change anything.
I have enabled "Reduce motion" as well.


https://github.com/FelixKratz/SketchyBar/assets/2006277/9115fa77-2641-4a53-b95d-9d741163b483

**Comment by vegetablesalad** [comment]
Oh sorry. I somehow missed that comment. Yes disabling the motion fixed the issue.
