### ISSUE TITLE
volume_change event doesn't reflect external monitor

### ISSUE THREAD

**Issue by hahuang65** [FelixKratz/SketchyBar#567]
When my laptop is docked to a monitor, the volume is not change-able, and the `INFO` seems to either be empty, or `0`.

It's empty when I do a `sketchybar --reload`.

It's `0` if I change the audio output back to Macbook speakers, then back to the monitor.

Is there a way to reflect that the current audio device is not the built-in speakers?

**Comment by FelixKratz** [comment]
Some output devices have no volume control because it is only a digital audio signal. All other audio devices should work fine. I regularly use airpods and other external speakers.

**Comment by hahuang65** [comment]
I was mostly asking if we could have it reflect as such, instead of displaying a 0.
