### ISSUE TITLE
Something wrong after move to Sonoma

### ISSUE THREAD

**Issue by txl263** [FelixKratz/SketchyBar#573]
![iShot_2024-06-29_02 11 51](https://github.com/FelixKratz/SketchyBar/assets/969317/66bdf15e-9a57-4e27-bbae-225852297518)

OS : macOS 14.5 23F79 x86_64
sketchybar-v2.21.0
The configuration that worked fine on Ventura caused problems when I copied it to Sonoma after upgrading.

```
#sketchybar -c .dotfiles/.config/sketchybar/sketchybarrc
No matching processes belonging to you were found
make: 'helper' is up to date.
sketchybar configuation loaded..
[2024-06-29 02:15:15] [?] Regex: No match found for regex '/github.notification\.*/'
could not retrieve window details.
```

**Comment by FelixKratz** [comment]
You need to install sketchybar-app-font.
