### ISSUE TITLE
Battery display and sound device switch go wrong suddenly . I even don't know what happened.

### ISSUE THREAD

**Issue by xbunax** [FelixKratz/SketchyBar#574]
<img width="509" alt="image" src="https://github.com/FelixKratz/SketchyBar/assets/50800571/6126bb52-228b-4644-bca2-b979597a8e87">

<img width="312" alt="image" src="https://github.com/FelixKratz/SketchyBar/assets/50800571/5447d1e1-4bc5-466c-b192-0569fc730023">

This is my sketchybar config https://github.com/xbunax/dotfile/blob/main/sketchybar/items/widgets/battery.lua which modify FelixKratz's lua config.

This is my system info and app version 
```
sketchybar-v2.21.0
```
```
                   'c.          xbunax@MacBook-Air-4.local 
                 ,xNMM.          -------------------------- 
               .OMMMMo           OS: macOS 14.5 23F79 arm64 
               OMMM0,            Host: Mac14,2 
     .;loddo:' loolloddol;.      Kernel: 23.5.0 
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 51 mins 
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 1 (port), 275 (brew) 
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.9 
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1920x1080, 1470x956 
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua 
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: yabai 
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    Terminal: /dev/ttys003 
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   CPU: Apple M2 
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   GPU: Apple M2 
    kMMMMMMMMMMMMMMMMMMMMMMd     Memory: 2363MiB / 16384MiB 
     ;KMMMMMMMWXXWMMMMMMMk.
       .cooc,.    .,coo:.                                
                                                         
```

**Comment by pkdevel** [comment]
exact same problem here. just suddenly stopped working and i'm clueless
i tried debugging:
sbar.exec("pmset -g batt") -> empty result
sbar.exec("echo test") -> expected result 'test'

**Comment by xbunax** [comment]
> exact same problem here. just suddenly stopped working and i'm clueless i tried debugging: sbar.exec("pmset -g batt") -> empty result sbar.exec("echo test") -> expected result 'test'

Do you find some problem ? I have no idea to fix this for now.😭

**Comment by pkdevel** [comment]
i guess it's related to the lua version update mentioned here:
https://github.com/FelixKratz/SbarLua/issues/29

i will give it try

**Comment by xbunax** [comment]
> i guess it's related to the lua version update mentioned here: [FelixKratz/SbarLua#29](https://github.com/FelixKratz/SbarLua/issues/29)
> 
> i will give it try 

I compile a lua5.4.4 but it's useless

**Comment by xbunax** [comment]
> When I use lua 5.4.7 and with your lua config , the battery info seems to be wrong. <img alt="image" width="350" src="https://private-user-images.githubusercontent.com/3949397/344403959-e85352a0-9968-4ce8-a813-15363f777591.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4Mzk1ODEsIm5iZiI6MTcxOTgzOTI4MSwicGF0aCI6Ii8zOTQ5Mzk3LzM0NDQwMzk1OS1lODUzNTJhMC05OTY4LTRjZTgtYTgxMy0xNTM2M2Y3Nzc1OTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMTMwODAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmYwY2ZlMWQ2Yjg1N2IyZWY5MjdlYWU0OWYwNmM3ODQ0ZTA0ZjkzNzZlNmI1ZjM2ZWFiNjEwMzA2OTQzNTcyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.k1d7NyuaPbBKWgzhKINVSoqKC6H3ahRAAUTevevohMc">
> 
> So I recompile the lua with 5.4.4 <img alt="image" width="586" src="https://private-user-images.githubusercontent.com/3949397/344404166-d0ee6d50-6681-411e-ab47-1968c9c80108.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4Mzk1ODEsIm5iZiI6MTcxOTgzOTI4MSwicGF0aCI6Ii8zOTQ5Mzk3LzM0NDQwNDE2Ni1kMGVlNmQ1MC02NjgxLTQxMWUtYWI0Ny0xOTY4YzljODAxMDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMTMwODAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTc5YjdmMzNkODlmMWRiZThkZGFjYmI1Y2RmMWQ5MmMzNGVhMDdlMWNjN2FkNzQzNWM4MTBiZDNlZjkxMTAxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.A9UZFvAgVxpjLBgFwEEXyoFV8cRGlgFzoI03Yfo37NE">
> 
> and it works. <img alt="image" width="213" src="https://private-user-images.githubusercontent.com/3949397/344404117-10774961-c059-4b3b-a104-4bc55855358f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4Mzk1ODIsIm5iZiI6MTcxOTgzOTI4MiwicGF0aCI6Ii8zOTQ5Mzk3LzM0NDQwNDExNy0xMDc3NDk2MS1jMDU5LTRiM2ItYTEwNC00YmM1NTg1NTM1OGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMTMwODAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRiODZjM2I5ZTA4NzE5YjJkZGY3NTFjMDdlNTQ4Yjg4YTdhYmEyYTA2YzNjOGUzODQ4NDU2YjQ4NTA5NGEyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.W8tHcu69Y4MsASl02WRzHWEQy4wtJK3LXCJnb-XxxRU">
> 
> Maybe we can export it to luarocks rock spec with spec version of lua


> > i guess it's related to the lua version update mentioned here: [FelixKratz/SbarLua#29](https://github.com/FelixKratz/SbarLua/issues/29)
> > i will give it try
> 
> I compile a lua5.4.4 but it's useless

I fix this， thank you
