### ISSUE TITLE
Space icons for Godot accumulate indefinitely

### ISSUE THREAD

**Issue by DetachedHeadState** [FelixKratz/SketchyBar#577]
Hi, I'm using a space selector component to visualize the apps I have open in each space. When I use the [Godot](https://godotengine.org/) engine, it seems like each window it creates never gets destroyed as far as SketchyBar is concerned, and so after developing for some time I end up with the pager showing a big pile of windows (that aren't actually there) being shown until I quit Godot completely: 
<img width="340" alt="image" src="https://github.com/FelixKratz/SketchyBar/assets/8218598/a4f7e21c-3798-4a00-b68a-19a299097411">

Any suggestions for how I can debug or work around this issue?

**Comment by cagdassalur** [comment]
Can you share the code for this component?

**Comment by DetachedHeadState** [comment]
Hi, here is the code: https://github.com/DetachedHeadState/sketchybarrc/blob/main/items/spaces.sh

**Comment by FelixKratz** [comment]
I believe this might be a bug in Godot. They seem to never properly destroy the windows they create. What sketchybar sees is just the state of windows reported by the WindowServer, so if Godot does not actually clean up the window objects and only moves them somewhere offscreen, these windows still exist and thus they are still reported to sketchybar.
