### ISSUE TITLE
homebrew/cask-fonts was deprecated

### ISSUE THREAD

**Issue by ThatIsAPseudo** [FelixKratz/SketchyBar#580]
The documentation at https://felixkratz.github.io/SketchyBar/setup should be updated since `brew tap homebrew/cask-fonts` now returns `Error: homebrew/cask-fonts was deprecated. This tap is now empty and all its contents were either deleted or migrated.`.
`brew install --cask font-hack-nerd-font` still works though.

**Comment by FelixKratz** [comment]
Thanks! Fixed it just now.
