### ISSUE TITLE
Notch is off-centered

### ISSUE THREAD

**Issue by Capybara121** [FelixKratz/SketchyBar#585]
I'm attempting to set up a split bar design using fillers positioned at positions `q` and `e`, and am noticing that the notch appears to be off-centered. The two sides of the bar reach out to different distances away from the notch. 

![Screenshot 2024-07-29 at 7 16 11 PM](https://github.com/user-attachments/assets/17e011f6-d9d3-4b89-afa3-f0359ec99ab6)

The left bracket measures 1267 pixels wide, while the right bracket measures 1269 pixels wide.

**Comment by PhrantiK** [comment]
You have `notch_width` defined twice in your bar config, one value with an odd number.

**Comment by Capybara121** [comment]
> You have `notch_width` defined twice in your bar config, one value with an odd number.

Thanks, didn't notice that. That being said, the issue still persists as the newest value is an even number, which should have overwritten the odd number notch. Also, the behaviour for an odd-pixel notch should be that there is a one pixel difference, right?

![Uploading Screenshot 2024-08-02 at 8.45.18 PM.png…]()

**Comment by FelixKratz** [comment]
It is probably an off-by-one error I made here:
https://github.com/FelixKratz/SketchyBar/blob/c713afe574d1652eee7967ea490c6061ecca9f29/src/bar.c#L246-L250

Feel free to play with these two lines till it is symmetric and post a PR.
