### ISSUE TITLE
bug: default menubar only shows if windows opened

### ISSUE THREAD

**Issue by fschlegelone** [FelixKratz/SketchyBar#586]
Hi together, 
I discovered a bug (not sure if from sketchybar, aerospace or macos itself) where the default menubar is only shown on hover if at least one app is opened (menubar set on always hide)
If I close all apps with cmd + q, the menubar is "frozen" and stays hidden no matter how heavy I hover on it.

**Comment by FelixKratz** [comment]
Sketchybar does not do anything to the default macOS bar, so this is likely not caused by it.
