### ISSUE TITLE
Bar drawing laggy when switching spaces

### ISSUE THREAD

**Issue by jbriales** [FelixKratz/SketchyBar#590]
When swiping between spaces, the bar from sketchybar takes ~1 second to refresh/show its content.

Is this expected? How can I investigate further what's going on and fix it?
I'm in Sonoma.

**Comment by FelixKratz** [comment]
Try: `sketchybar --bar sticky=on`. Does this fix the problem you are seeing? Also turn off reduce motion if you have that enabled and see if that helps.

**Comment by jbriales** [comment]
I already had those settings.
Interestingly switching spaces via yabai is fast/immediate, so I'll stick with that (which was my eventual plan anyway).

Can close this from my side :) Thanks for the prompt answer!
