### ISSUE TITLE
Setup extra bars to autostart

### ISSUE THREAD

**Issue by jbriales** [FelixKratz/SketchyBar#591]
I'm following the instructions in https://felixkratz.github.io/SketchyBar/config/tricks#multiple-bars to add an additional sketchybar.
Running it from terminal works fine.
I wonder how to run that second bar automatically at startup too, since the instructions in https://felixkratz.github.io/SketchyBar/setup#brew-install indicate:
`brew services start sketchybar`
but doing sth like `brew services start sketchybar2` will fail.

**Comment by FelixKratz** [comment]
There are several ways. You could start the addtitional bar from the main `sketchybarrc` or you could create a separate launchd plist file for the secondary bar.

**Comment by weeebdev** [comment]
> There are several ways. You could start the addtitional bar from the main `sketchybarrc` or you could create a separate launchd plist file for the secondary bar.

how do I do that when using SbarLua? `sketchybarrc` is a lua code in this case.
