### ISSUE TITLE
Bar not displayed when using Homebrew services

### ISSUE THREAD

**Issue by realprogrammersusevim** [FelixKratz/SketchyBar#602]
I've been using sketchybar for a while now with no issues but suddenly when the bar is started by running `brew services start sketchybar` nothing is displayed, but when I open a terminal and run `sketchybar` the bar is displayed and runs correctly with no errors.

**Comment by FelixKratz** [comment]
You could check the logs found in `/opt/homebrew/var/log/sketchybar` to see if there is something we could use to investigate this further

**Comment by realprogrammersusevim** [comment]
Thank you so much for the response! There was a bug where sketchybar couldn't find the "inspect" library I called to debug a table. I didn't realize that Homebrew services kept their logs there. Perhaps this might be a good note to add to the debugging tips section on the website? Starting sketchybar directly from the command line is of course helpful to see the immediate output, but seeing the logs from the Homebrew service would be super helpful as well to diagnose Homebrew problems.

Again, thanks for the help.

**Comment by kushvinth** [comment]
how did you fix it @realprogrammersusevim

**Comment by realprogrammersusevim** [comment]
@kushvinth I think I either checked the logs for the Homebrew service or started it manually to get the output and see why my config was crashing. Sketchybar almost always tells you why it crashes if you can get the output, and you can always add some good ol' printf debugging if you still can't figure it out.

**Comment by kushvinth** [comment]
so you are saying the fixing PATH conflicts on your DOTFILES will fix
