### ISSUE TITLE
Sketchybar + macOS Sequoia: Audio & Brightness subscriptions non-functional

### ISSUE THREAD

**Issue by AdonisCodes** [FelixKratz/SketchyBar#604]
Hello!

I am mostly using the base / default configuration from @FelixKratz SketchyBar config.
I have however, updated to macOS Sequoia beta 7. Which introduced minor bugs (Or so I think)

Both of them are just marked out due to missing values.
Maybe it has something todo with premissions?

If there is a fix could someone direct me into the correct direction?
Thanks!

<img width="1800" alt="Untitled" src="https://github.com/user-attachments/assets/b44e2643-b2c7-4cb4-b429-9a3f34fe9b49">

**Comment by AdonisCodes** [comment]
Seems to only be my brightness now.
Will take a look at the permissions.

**Comment by AdonisCodes** [comment]
👋 Hi!
Problems seems to be fixe now.
Didn't update SketchyBar or anything else, guess it was some ol' permissions bug.
Thanks!

**Comment by ethanuppal** [comment]
@AdonisCodes I'm getting this after updating to 15.7.9 - how did you fix it?
