### ISSUE TITLE
Aerospace overlapping sketchbar

### ISSUE THREAD

**Issue by trobrock** [FelixKratz/SketchyBar#610]
Not too sure which project this should land with, but I just installed sketchybar. I have two monitors. On my main display the windows are being extended all the way to the top and overlapping sketchybar on my second monitor it's working fine. Any suggestions? I'm running the default config for sketchybar

Main monitor:
![Screenshot 2024-09-06 at 4 59 56 PM](https://github.com/user-attachments/assets/0cb2ad2e-32e2-44dc-9fb6-0f95a291968b)

Second monitor:
<img width="1502" alt="Screenshot 2024-09-06 at 5 00 14 PM" src="https://github.com/user-attachments/assets/9021acc6-b90c-400c-936f-39140bde15e7">

Display arrangement:
![Screenshot 2024-09-06 at 5 00 55 PM](https://github.com/user-attachments/assets/f44544db-6799-462a-ac41-078e8a9cdb35)

**Comment by trobrock** [comment]
I'm not sure if this is the intended way to fix this or if it's a bug, but for now I solved this by adjusting the outer.top gap for just my main monitor in aerospace.

**Comment by AmmarCodes** [comment]
You can adjust aerospace's outer.top gap per monitor, something like:

```toml
outer.top =        [{monitor.main = 35 }, 14]
```
