### ISSUE TITLE
idea: using a golang instead of bash scripts

### ISSUE THREAD

**Issue by lucax88x** [FelixKratz/SketchyBar#611]
so, I've finally managed to have sketchybar expecially for my aerospace configuration, and **I** really hate bash scripts, and they're *SLOW*.

so, I was thinking, why I don't make a cli to be used by sketchybarrc? 
So I have the plus that it's compiled, typed, and I can leverage on parallelism, maybe.

the idea is to use golang to produce a cli scripts, with commands like init, click, update, that can be used by sketchybarrc and events of it, instead of bashrc.

for now, it's a very alpha stage, but I've produced something like:

```go
func initCalendar(ctx context.Context, di *wentsketchy.Wentsketchy) error {
	calendar := sketchybar.ItemOptions{
		Icon: sketchybar.ItemIconOptions{
			Value: IconClock,
			Font: sketchybar.FontOptions{
				Font: iconFont,
				Kind: "Regular",
				Size: "12.0",
			},
			PaddingOptions: sketchybar.PaddingOptions{
				Right: 5,
				Left:  10,
			},
		},
		Label: sketchybar.ItemLabelOptions{
			PaddingOptions: sketchybar.PaddingOptions{
				Right: 5,
				Left:  10,
			},
		},
		Background: sketchybar.BackgroundOptions{
			BorderOptions: sketchybar.BorderOptions{
				Width: 2,
				Color: ColorBackground1,
			},
			ColorOptions: sketchybar.ColorOptions{
				Color: ColorBackground1,
			},
		},
		UpdateFreq: 30,
		Script:     "wentsketchy update calendar",
		// Click_script:            "$PLUGIN_DIR/zen.sh",
	}

	return di.Sketchybar.Run(
		ctx,
		s("--add", "item", "calendar", "right"),
		m(s("--set", "calendar"), calendar.ToArgs()),
		s("--subscribe", "calendar", "system_woke"),
	)
}
```

[link if you want to peek](https://github.com/lucax88x/wentsketchy)

what do you think?

**Comment by k2662** [comment]
> so, I've finally managed to have sketchybar expecially for my aerospace configuration, and **I** really hate bash scripts, and they're _SLOW_.
> 
> so, I was thinking, why I don't make a cli to be used by sketchybarrc? So I have the plus that it's compiled, typed, and I can leverage on parallelism, maybe.
> 
> the idea is to use golang to produce a cli scripts, with commands like init, click, update, that can be used by sketchybarrc and events of it, instead of bashrc.
> 
> for now, it's a very alpha stage, but I've produced something like:
> 
> ```go
> func initCalendar(ctx context.Context, di *wentsketchy.Wentsketchy) error {
> 	calendar := sketchybar.ItemOptions{
> 		Icon: sketchybar.ItemIconOptions{
> 			Value: IconClock,
> 			Font: sketchybar.FontOptions{
> 				Font: iconFont,
> 				Kind: "Regular",
> 				Size: "12.0",
> 			},
> 			PaddingOptions: sketchybar.PaddingOptions{
> 				Right: 5,
> 				Left:  10,
> 			},
> 		},
> 		Label: sketchybar.ItemLabelOptions{
> 			PaddingOptions: sketchybar.PaddingOptions{
> 				Right: 5,
> 				Left:  10,
> 			},
> 		},
> 		Background: sketchybar.BackgroundOptions{
> 			BorderOptions: sketchybar.BorderOptions{
> 				Width: 2,
> 				Color: ColorBackground1,
> 			},
> 			ColorOptions: sketchybar.ColorOptions{
> 				Color: ColorBackground1,
> 			},
> 		},
> 		UpdateFreq: 30,
> 		Script:     "wentsketchy update calendar",
> 		// Click_script:            "$PLUGIN_DIR/zen.sh",
> 	}
> 
> 	return di.Sketchybar.Run(
> 		ctx,
> 		s("--add", "item", "calendar", "right"),
> 		m(s("--set", "calendar"), calendar.ToArgs()),
> 		s("--subscribe", "calendar", "system_woke"),
> 	)
> }
> ```
> 
> [link if you want to peek](https://github.com/lucax88x/wentsketchy)
> 
> what do you think?

You can configure SketchyBar using lua with SbarLua.

**Comment by FelixKratz** [comment]
Nice idea! All I am providing with SketchyBar is a very flexible API accessible through a mach interface and the default way to communicate with this mach interface is the "bash-way" of invoking a process and passing it some arguments. However, there are countless other ways to interact with the mach interface, e.g. by sending messages from a compiled helper binary, or from lua, using SbarLua. I have also seen efforts to make the mach interface available through a rust package.
