### ISSUE TITLE
MacOS 15 Network Permission

### ISSUE THREAD

**Issue by litszwaiboris** [FelixKratz/SketchyBar#616]
`networksetup -getairportnetwork` do not work as network permission is not granted, and the the Wi-Fi Network is not being able to be retrieved.

Expected return of `networksetup -getairportnetwork en0`: `Wi-Fi BSSID`
Current return: `You are not associated with an AirPort network.`

**Comment by litszwaiboris** [comment]
Tried another approach: `system_profiler SPAirPortDataType | awk -F':' '/Current Network Information:/ { getline; sub(/^ */, ""); sub(/:$/, ""); print}' | awk 'NR==1 {print}'`, still does not work, instead it output an empty string

![CleanShot 2024-09-21 at 18 25 12@2x](https://github.com/user-attachments/assets/5fb075fa-9ae8-43a8-b9e7-a66b66970cd4)

**Comment by FelixKratz** [comment]
This still works:
```bash
ipconfig getsummary en0 | awk -F ' SSID : '  '/ SSID : / {print $2}'
```
However, I think that apple will eventually remove all ways to get access to the wifi SSID from an application without location permission because it might reveal your location to an untrusted app.

**Comment by chrede88** [comment]
> This still works:
> 
> ipconfig getsummary en0 | awk -F ' SSID : '  '/ SSID : / {print $2}'
> However, I think that apple will eventually remove all ways to get access to the wifi SSID from an application without location permission because it might reveal your location to an untrusted app.

I can confirm that this doesn't work anymore as of Sonoma 15.6

**Comment by haroldduan** [comment]
I can confirm that this doesn't work anymore as of Sequoia 15.6
