### ISSUE TITLE
Standalone icon logo

### ISSUE THREAD

**Issue by XavierChanth** [FelixKratz/SketchyBar#625]
I would love to display your logo on my Profile README, but there is no standalone logo without the wordmark. If there was, I could point to the GitHub raw files. I would rather point to an official logo, than anything else.

**Comment by FelixKratz** [comment]
Thanks for the suggestion, I have added a standalone icon: https://github.com/FelixKratz/SketchyBar/commit/ed1684d348fc4d4319c7f9835141524c524bacb3
