### ISSUE TITLE
display index, based on what?

### ISSUE THREAD

**Issue by lucax88x** [FelixKratz/SketchyBar#628]
ciao,  I've a question, what is the display index based on?

because  I'm trying to match the indexes from aerospace 

```shell
1 | Built-in Retina Display
2 | DELL U3425WE
```

but for some reason in sketchybar they're inverted, and I cannot figure that out.

**Comment by ozgenbaris1** [comment]
I don't know if this is a bug or related to macos built-in display indexing algorithm but in my case all of the display indexes were shifted by 1 (not inverted). To give an example, I have 3 displays plugged and this is the result of the command 

```sh
> aerospace list-monitors
1 | PA278CV
2 | LG HDR QHD
3 | Built-in Retina Display
```

but the corresponding indexes for sketchybar was in the order: [2, 3, 1]. 
so I tried to manually shift the indexes returned by aerospace by 1. (I'm using SbarLua)
I started to learn Lua this week so I don't have any experience with it. I'm sure there are better ways to write the code below. I hope this helps someone dealing with the same issue until resolved.

```lua
sbar.exec("aerospace list-monitors --format %{monitor-id}",

  function(result, _)
    local monitors = {}

    -- convert newline delimited string to Lua table
    for m in string.gmatch(result, "[^\n]+") do
      table.insert(monitors, m)
    end

    for i, monitor in ipairs(monitors) do

      -- if not the last item of the table, then shift the index by 1
      local display = monitors[i + 1]

      if i == #monitors then
        display = 1
      end

      sbar.exec("aerospace list-workspaces --empty no --monitor " .. monitor,
        function(result, _)
          for workspace in string.gmatch(result, "[^\n]+") do
            local name = "workspace." .. workspace

            sbar.add(
              "space", name, {
                icon = workspace,
                display = display,
                space = name
              }
            )
          end
        end)
    end
  end)
```

**Comment by kevindiaz314** [comment]
AeroSpace indices monitor from left to right. If you have a laptop and a monitor setup with your laptop to the left of your monitor, `aerospace list-monitors` will output:
```
1 | Built-in Retina Display
2 | <monitor>
```

**Comment by FelixKratz** [comment]
It is based on the macOS system internal display order as returned by `SLSCopyManagedDisplays`. This is the same display arrangement used in `yabai`.

https://github.com/FelixKratz/SketchyBar/blob/5b7d0e07cf41ae8413393b1bb8f5c184a6615695/src/display.c#L102-L132
