### ISSUE TITLE
Cant properly build from source

### ISSUE THREAD

**Issue by Anaritus** [FelixKratz/SketchyBar#646]
I'm on aerospace, because of that I want to turn of displays have separate spaces (it actually does increase performance by quite a lot). Thankfully there exists commit fb5923291182e5070b1aef5feaed0caaa2b36074 which should do just that, but I'm struggling to build sketchybar from source.

I am following what I found in issue https://github.com/FelixKratz/SketchyBar/issues/608#issue-2499821609 and https://github.com/FelixKratz/SketchyBar/issues/541#issue-2255284430.

Those two suggest two following steps(I skipped config step since I already have one)  to build sketchybar from source:
1.
```
git clone https://github.com/FelixKratz/SketchyBar.git
cd SketchyBar
make
mv bin/sketchybar /usr/local/bin
```
2. copy
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>git.felix.sketchybar</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/bin/sketchybar</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin</string>
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/sketchybar.out.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/sketchybar.err.log</string>
    <key>ThrottleInterval</key>
    <integer>30</integer>
    <key>ProcessType</key>
    <string>Interactive</string>
    <key>Nice</key>
    <integer>-20</integer>
</dict>
</plist>
```
into `~/Library/LaunchAgents/git.felix.sketchybar.plist`
3.
```
launchctl bootstrap gui/$UID $HOME/Library/LaunchAgents/git.felix.sketchybar.plist
launchctl load -w $HOME/Library/LaunchAgents/git.felix.sketchybar.plist
```

Not sure what step 3 does.
Also, in my `aerospace.toml` config file I configured to start sketchybar on launch and notify sketchybar about workspace change (all of that works when installing with brew)

After all that all hell breaks loose. Sketchybar keeps asking me accessibility and screen record permissions non stop and even though they are turned on in system settings sketchybar does not detect that and keeps spaming me with requests. Also, I think step 3 broke my work wifi, but it might be unrelated: it still connects, but I don't have internet access for like 5 minutes after boot, and I don't know why, extremely frustrating since every time I try to change some settings i need to restart my mac book for them to take effect

Please show me what might be wrong and how to actually configure sketchybar from source, I really like it

**Comment by PhrantiK** [comment]
To build from source and get the latest commits you can do this:

`brew install sketchybar --HEAD`

**Comment by Anaritus** [comment]
That worked flawlessly. Thank you!
