### ISSUE TITLE
Bar offset does not work on display with notch

### ISSUE THREAD

**Issue by tomassliz** [FelixKratz/SketchyBar#657]
I want to set an additional y-offset for the notch display with the `notch_offset` bar property, but it doesn't work. The value is ignored for the bar position on the right.

```bash
bar=(
  position=right
  height=40
  color=0x40000000
  y_offset=10
  notch_offset=25
  margin=10
  corner_radius=9
)

sketchybar --bar "${bar[@]}" 
```

**Comment by FelixKratz** [comment]
Position `left` and `right` are currently unsupported, hence several problems are to be expected. See #240
