### ISSUE TITLE
graphs show extraneous data

### ISSUE THREAD

**Issue by es183923** [FelixKratz/SketchyBar#67]
When the following code is run, the result is this image:
![Screen Shot 2021-10-03 at 2 57 53 PM](https://user-images.githubusercontent.com/72744903/135767654-531598e4-31c4-4557-9715-b5f969b6af3b.png)

The transparent white part should not be there. THe problem also occurs when `graph_fill_color` is not present.

```sh
echo 'creating item'
sketchybar -m batch \
    --add component graph test_graph right 40 \
        --set test_graph \
        graph_color="0xFFFFFFFF" \
        graph_fill_color="0xFFFFFFFF"

sleep 1;
echo 'filling with 1'
for i in {1..20}; do
    sketchybar -m push test_graph 1
done

sleep 1;
echo 'filling with 0.2'
for i in {1..30}; do
    sketchybar -m push test_graph 0.2
    sleep 0.01;
done
```

**Comment by FelixKratz** [comment]
Thanks for reporting this! I messed this up while restructuring the graphs and aliases in fcf5db0c07c0a8a77c574c08184fff83ae5c461d. Should be fixed as of a547bdad12dda04e2e45355647dc992164d21218.
