### ISSUE TITLE
add as homebrew service

### ISSUE THREAD

**Issue by leosolid** [FelixKratz/SketchyBar#8]
Add ability to install through brew and run as a brew service so it's easy to install and it can run  automatically on startup.

**Comment by andreicorpo** [comment]
This would be pretty cool and would make this project a lot easier to use. 😄

**Comment by FelixKratz** [comment]
I agree, but I feel that this project is still in a "beta" state as there are still many problems I want to iron out. Install via brew feels so "official" and I want this to work a bit smoother before doing that.

In the meantime, this is how I run the bar almost pain free:

At the end of my yabairc I start a screen with the bar running in it, this way I inherit all
permissions from yabai (probably not the "right" way to do things)
```bash
screen -d -m sketchybar
```
when I want to see what the bar is doing I simply run
```bash
screen -r
```

**Comment by andreicorpo** [comment]
Sure, got it! I'm not sure what the `screen` command is. 😅

**Comment by FelixKratz** [comment]
It's an awesome tool (unfortunately not preinstalled on macOS) [https://www.gnu.org/software/screen/](https://www.gnu.org/software/screen/)
simply install via
```bash
brew install screen
```

**Comment by andreicorpo** [comment]
Awesome, thank you! Can't wait for this project to reach its full potential! 😄

**Comment by FelixKratz** [comment]
I have decided to create a homebrew tap, see the README.md for more information on this. Can anyone give this a try and tell me if it is working?
It is important to remove the old installation prior to installing via brew, to uninstall
pull from master and in the folder run
```bash
make uninstall
```
Then you can install and run via brew with:
```bash
brew tap FelixKratz/formulae
brew install sketchybar
brew services start sketchybar
```
The system will ask for accessibility privileges, which are currently needed for click event handling. If you do not need that you can simply click "deny".
