### ISSUE TITLE
differentiate between different types of clicks

### ISSUE THREAD

**Issue by es183923** [FelixKratz/SketchyBar#92]
Right now, there is a `click_script` which is run when the user clicks on an item. The `mouse.clicked` event is also sent, which does the same thing. (i think)

But, this is triggered for all types of clicks, including right and middle clicks.

I propose adding a `mouse.left_clicked`, `mouse.right_clicked`, and `mouse.middle_clicked` events so it is possible to differentiate between those different types of clicks

**Comment by FelixKratz** [comment]
This is on my todo list. I want the click_script as a quick and easy way to add click scripts and the more in-depth configuration to be achieved via the event subscription system. Differentiating between different clicks and modifiers #25 will be included in the same update.
