### ISSUE TITLE
Add discrete options for icon.background, label.background, icon.highlight_background, and label.highlight_background.

### ISSUE THREAD

**Issue by SxC97** [FelixKratz/SketchyBar#96]
I posted my [current setup](https://github.com/FelixKratz/SketchyBar/discussions/47#discussioncomment-1576629) and I’ve managed to get different colors for the label and icon by adding a separate "logo" item to the bar and adjusting padding. The dotfiles and plugins can be found [here](https://github.com/SxC97/dotfiles). This would be a lot easier to accomplish if sketchybar had unique options for different colors for the label and icon.

**Comment by FelixKratz** [comment]
I have added experimental support for individual backgrounds for icon and label in  58fb08ee4989c41ecae79c42115068357f2a2c46

**Comment by johnallen3d** [comment]
Sorry to dredge up an old issue @FelixKratz. I'm looking for a way to change the background of an icon on highlight (similar to `icon.highlight_color`). Is that currently possible?

**Comment by FelixKratz** [comment]
There is no "highlight background", but it is very easily scriptable:
```bash
if [ "$HIGHLIGHT_CONDITION" = "true" ]; then
    sketchybar --set $NAME icon.background.color=0xff000000 icon.highlight=on
else
    sketchybar --set $NAME icon.background.color=0xffffff icon.highlight=off
fi
```
