### ISSUE TITLE
Add option to automatically hide sketchybar when in fullscreen apps

### ISSUE THREAD

**Issue by SxC97** [FelixKratz/SketchyBar#98]
I have managed to find a work around by adding 

`yabai -m signal --add event=space_changed action="source ~/.scripts/.hide_bar"`

to the end of my `.yabairc` file and executing the `.hide_bar` script as shown here:

### .hide_bar ###

```
if [[ $(yabai -m query --spaces --space | grep "native-fullscreen") == *"0"* ]]; then
  sketchybar -m --bar hidden=off
else
  sketchybar -m --bar hidden=on
fi
```

**Comment by FelixKratz** [comment]
This was never planned to happen and just slid in when reworking the window tags for monterey. 8598d4187c168190f8008c9aacd94dfb8ddfa5fe fixes this
